### ISSUE TITLE
The list in the doc doesn't match dockerhub

### ISSUE THREAD

**Issue by thesteve0** [CrunchyData/crunchy-containers#1]
So the list in this doc doesn't match what is in dockerhub

https://hub.docker.com/u/crunchydata/

Is there some way to get the two lists in agreement or better descriptions in DockerHUb so we can see what is deprecated

Thanks!

**Comment by jmccormick2001** [comment]
crunchy-pg is deprecated now that crunchy-postgres is open source, and pgrepl is a container that is for another project within crunchy but shares the same domain name, the crunchy-skybridge is also deprecated at this point.  I'll plan on removing the deprecated containers from the dockerhub in the next 2 weeks, after that removal, it should better match the list in crunchy-containers.
