### ISSUE TITLE
 Redundancy of "crunchy-scheduler" and "postgres-operator" Pods

### ISSUE THREAD

**Issue by hase1128** [CrunchyData/crunchy-containers#1009]
Hi,

I have question about redundancy of "crunchy-scheduler" and "postgres-operator" Pods.
These Pods are deployed only one. 

[oper@master-7 postgres-operator]$ kubectl get deployment
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
crunchy-scheduler   1/1     1            1           24d
postgres-operator   1/1     1            1           24d
test                1/1     1            1           23d
test-gweo           1/1     1            1           23d
test-pgpool         1/1     1            1           23d

I would like to scale-up these pods, but I could not find related parameters in pgo.yaml.
Is there a way to scale-up these pods?

Regards,
Jin

**Comment by jasonodonnell** [comment]
Hello @hase1128, 

Crunchy Scheduler was replaced in 3.5.0 Operator with `pgo-scheduler`.  The new scheduler pod works with Operator directly and is included in the operator deployment.  We suggest upgrading to use the new scheduler.

Scaling of these pods (operator and/or crunchy scheduler) is not possible at this time.

**Comment by hase1128** [comment]
Hi @jasonodonnell 
Thank you for the answer. I will upgrade to new version.
Do you have a plan to enable scaling of operator pod?
My concern is that no scaling of operator pod may be single point of failure.

**Comment by jmccormick2001** [comment]
the operator runs within a Deployment, so if for some reason it dies, Kube will restart it, this takes about 2 or 3 seconds on my dev box.  That said, if we start building applications that drive significant load onto the Operator API, then I could definitely see scaling the Operator to support that load being something we would need to do, thinking about that actually for some project ideas we are contemplating.  cheers.

**Comment by hase1128** [comment]
Thank you for the detail comment.
