### ISSUE TITLE
Turning off Replication

### ISSUE THREAD

**Issue by mmesbah** [CrunchyData/crunchy-containers#1016]
On crunchy-postgres-gis template, it would be appreciated if you consider an ENV VAR like `TURN_ON_REPLICATION=on|off` so that we can turn off replication whenever we want.
When setting it to `off`, you should set Postgres setting `wal_level` to `minimal`.

Right now, we can set `MAX_WAL_SENDERS=0`. However, `wal_level` in Postgres settings is still set to `replica`.

I read [crunchy-postgres-gis doc](https://access.crunchydata.com/documentation/crunchy-containers/2.3.0/container-specifications/crunchy-postgres-gis/), and I didn't find any existing ENV VAR with these needed properties.

**Comment by cahoonpwork** [comment]
Thanks for the suggestion we will look into this.
