### ISSUE TITLE
add dictionaries for full text search

### ISSUE THREAD

**Issue by david-ecc** [CrunchyData/crunchy-containers#1028]
PostgreSQL supports full text search, but needs dictionaries for each language. These dictionaries need to be installed manually (are not part of PostgreSQL) to the folder `$SHAREDIR/tsearch_data/`, but `$SHAREDIR` (i.e. /usr/pgsql-11/share/) cannot be modified.

See: https://www.postgresql.org/docs/11/textsearch-configuration.html

**Describe the solution you'd like**
Install dictionaries (distribution packages) and symlink to `$SHAREDIR/tsearch_data/`.

**Please tell us about your environment:**
postgres-operator 3.5.2

**Comment by jmccormick2001** [comment]
bash-4.2$ psql
psql (11.2)
Type "help" for help.

postgres=# \dF
               List of text search configurations
   Schema   |    Name    |              Description              
------------+------------+---------------------------------------
 pg_catalog | danish     | configuration for danish language
 pg_catalog | dutch      | configuration for dutch language
 pg_catalog | english    | configuration for english language
 pg_catalog | finnish    | configuration for finnish language
 pg_catalog | french     | configuration for french language
 pg_catalog | german     | configuration for german language
 pg_catalog | hungarian  | configuration for hungarian language
 pg_catalog | italian    | configuration for italian language
 pg_catalog | norwegian  | configuration for norwegian language
 pg_catalog | portuguese | configuration for portuguese language
 pg_catalog | romanian   | configuration for romanian language
 pg_catalog | russian    | configuration for russian language
 pg_catalog | simple     | simple configuration
 pg_catalog | spanish    | configuration for spanish language
 pg_catalog | swedish    | configuration for swedish language
 pg_catalog | turkish    | configuration for turkish language

these are installed by default it appears, does that work for your usage?
