### ISSUE TITLE
CCP_NFS_IP logic for pgpool examples/kube

### ISSUE THREAD

**Issue by NEWBEE1** [CrunchyData/crunchy-containers#1052]
Hi ,

NFS (create_storage ) , functionality is not present for pgppol expample/kube.

I need to generate pgpool debug level logs (which can be more than 8-9GB sometime)
because of that pgppool pod is getting evicted since NFS storage is not avaliable for pgpool.

Is it possible to provide NFS for pgpool?

**Comment by jasonodonnell** [comment]
Hello,

The pgpool container only exposes one volume for configuration files (`/pgconf`), so this example is working as expected as we treat the service as ephemeral.  The logs are exposed via the container logs in Kubernetes.
