### ISSUE TITLE
How to deactive logging_collector in postgresql.conf

### ISSUE THREAD

**Issue by senzacionale** [CrunchyData/crunchy-containers#1053]
I needd to deactivate logging_collector 

From DOCS some optional parameters can be changed like "MAX_CONNECTIONS" but why not "LOGGING_COLLECTOR"?

https://crunchydata.github.io/crunchy-containers/stable/container-specifications/crunchy-postgres/

How to disable logging_collector ?

**Comment by jasonodonnell** [comment]
Hi @senzacionale,

Mount a custom `postgresql.conf` to `/pgconf`.  Here's an example of doing that: https://github.com/CrunchyData/crunchy-containers/tree/master/examples/kube/custom-config

**Comment by senzacionale** [comment]
Hi,

I can not find an example how to mount custom postgresql.conf. Can you copy a code?

**Comment by jasonodonnell** [comment]
I linked an example in my previous comment.

Kubernetes example: https://github.com/CrunchyData/crunchy-containers/tree/master/examples/kube/custom-config

Docker example: https://github.com/CrunchyData/crunchy-containers/tree/master/examples/docker/custom-config

**Comment by senzacionale** [comment]
Thank you. But is there any easier way to use custom postgres.conf file. Because I don't want to pull whole project.
