### ISSUE TITLE
Broken link in Docker Hub docs for crunchy-postgres

### ISSUE THREAD

**Issue by nicktimko** [CrunchyData/crunchy-containers#1061]
Link at https://hub.docker.com/r/crunchydata/crunchy-postgres to the examples is broken:

> Examples can be found in the official Crunchy Containers GitHub repository for the project.

It directs to https://github.com/CrunchyData/crunchy-containers/examples but should go to https://github.com/CrunchyData/crunchy-containers/tree/master/examples (or whatever branch/tag desired.)

**Comment by cahoonpwork** [comment]
Thanks.  I updated the link to github example source.
