### ISSUE TITLE
Please update pgadmin4 image - its old & broken with 11.3

### ISSUE THREAD

**Issue by sauravnz** [CrunchyData/crunchy-containers#1064]
**Describe the bug**
The crunchy-pgadmin4 docker image has pgadmin v3. Also its unable to refresh the server list on successful connection. Tested with postgres 11.3

Error : 
```
psycopg2.extensions.Column' object has no attribute '_asdict'
```

**To Reproduce**
1. Go to the main screen
2. Click on servers to create a new server
3. Add a new server
4. The servers tab on the left does not refresh with the database and other objects. It fails to load anything.
5. Errors can be seen in the error_log file

**Expected behavior**
The servers tab should load with the objects as it makes a successful connection to the postgres database

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running Local
* Storage being used Host
* Container Image Tag: centos7-11.3-2.3.2
* PostgreSQL Version: 11.3
* Platform : Docker
* Platform Version: 18.09.2

**Additional context**
The problem got fixed by using the official pgadmin4 image : dpage/pgadmin4:4.6

**Comment by jkatz** [comment]
Hi -- This has been updated in the 2.4.2 release. It now uses pgAdmin 4.13.
