### ISSUE TITLE
initdb: could not access directory "/pgdata/statefulset-0": Permission denied

### ISSUE THREAD

**Issue by jiayun1997** [CrunchyData/crunchy-containers#1083]
Hello, I had a problem creating PostgreSQL cluster through yaml file in kubernetes cluster. 
Here is the error message
![image](https://user-images.githubusercontent.com/48053995/59396026-73a26700-8db9-11e9-962f-773408a5931c.png)

**Comment by jmccormick2001** [comment]
typically storage issues (permission issues) are due to the storage configuration and what the container is expecting in terms of storage.  What storage are you using for your example?  we currently test with hostPath, NFS, and dynamic storage.
