### ISSUE TITLE
Neither, postgis nor plr extensions are available in the "crunchy-postgres-gis" image version "centos7-11.x"

### ISSUE THREAD

**Issue by J-A-B-R** [CrunchyData/crunchy-containers#1096]
**Describe the bug**
As title says, neither, *postgis* nor *plr* extensions are available in the *"crunchy-postgres-gis"* image version *"centos7-11.x"*.

**To Reproduce**
1. Execute:
   ```
   docker run --rm -it -p 12000:5432 --privileged=true --name=crunchy-test --hostname=crunchy-test \
              -e PG_PRIMARY_HOST=crunchy-test \
              -e PG_PRIMARY_PORT=5432 \
              -e PG_PRIMARY_USER=primaryuser \
              -e PG_PRIMARY_PASSWORD=password \
              -e PG_MODE=primary \
              -e PG_USER=testuser \
              -e PG_PASSWORD=password \
              -e PG_ROOT_PASSWORD=password \
              -e PG_DATABASE=userdb \
              crunchydata/crunchy-postgres-gis:centos7-11.4-2.4.1
    ```
2. Wait until initialization ends.
3. Log during initializacion shows these errors:
    ```
    ERROR:  could not load library "/usr/pgsql-11/lib/rtpostgis-2.4.so": libgdal.so.20: cannot open shared object file: No such file or directory
    ERROR:  required extension "postgis" is not installed
    HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
    CREATE EXTENSION                                                                                                                             
    ERROR:  required extension "postgis" is not installed                                                                                        
    HINT:  Use CREATE EXTENSION ... CASCADE to install required extensions too.
    CREATE extension
    CREATE EXTENSION                                                                                                                             
    ERROR:  extension "plr" has no installation script nor update path for version "8.5"
    ```
4. Execute `psql -p 12000 -U testuser -c "SELECT PostGIS_full_version();" userdb`.
5. Execution fails with error:
    ```
    ERROR:  function postgis_full_version() does not exist
    LINE 1: SELECT PostGIS_full_version();
                   ^
    HINT:  No function matches the given name and argument types. You might need to add explicit type casts
    ```

**Expected behavior**
PostGis and Plr extensions are installed without errors and availabe.
Above psql command run without errors.

**Please tell us about your environment:**

* Operating System: Windows 8.1
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): Local
* Container Image Tag: centos7-11.4-2.4.1
* PostgreSQL Version: 11
* Platform (Docker, Kubernetes, OpenShift): Docker Toolbox (Running on VirtualBox)
* Platform Version: 18.09.3, build 774a1f4eee (VirtualBox version: 6.0.8)

**Additional context**
Upon container inspection, the PostGis and Plr files seem to be present. However, the GDAL 2.0 library is not installed.

I was able to install the GDAL 2 library inside the container following this [StackExchange post](https://gis.stackexchange.com/questions/263495/how-to-install-gdal-on-centos-7-4/296386#296386):
```
yum -y groupinstall "Development Tools"
yum -y install SFCGAL-devel
curl --output install-libkml-r864-64bit.tar.gz http://s3.amazonaws.com/etc-data.koordinates.com/gdal-travisci/install-libkml-r864-64bit.tar.gz
tar xzf install-libkml-r864-64bit.tar.gz
cp -r install-libkml/include/* /usr/local/include
cp -r install-libkml/lib/* /usr/local/lib \
ldconfig
curl --output gdal-2.2.3.tar.gz http://download.osgeo.org/gdal/2.2.3/gdal-2.2.3.tar.gz \
tar xzf gdal-2.2.3.tar.gz
cd gdal-2.2.3
./configure --with-libkml
make
make install
ldconfig
```

However, my linux-fu was not strong enough to make ldconfig (and hence PostGis) recognize it.

**Comment by cahoonpwork** [comment]
We are looking into this, we noticed the issue this weekend too.

**Comment by cahoonpwork** [comment]
This was an issue of the community postgres gis libraries at the time the image was built.  You can get it running but as of yesterday afternoon we tested and were able to build the image locally from source and it is working.  If you want to give that a go and see if it works for you.

**Comment by J-A-B-R** [comment]
Building from sources worked like a charm and the container is running flawlessly now. Thank you very much.

**Comment by J-A-B-R** [comment]
I spoke too soon. As we don't use it, I didn't notice that the *plr* extension still fails with the same error as before:
`ERROR:  extension "plr" has no installation script nor update path for version "8.5"`.

Weird, the latest release published is 8,4.

**Comment by onham** [comment]
Can confirm that building from source will give you all the needed extensions!

**Comment by tdamsma** [comment]
I ran into this too, would be nice if the image on dockerhub was updated as this issue is over a month old already

**Comment by mosinuga** [comment]
Is there any update on this problem? The crunchydata images don't allow you to `sudo` or `su`, so how come you're able to add packages or run `ldconfig`?

**Comment by jkatz** [comment]
Hi! I apologize for the slow reply on this.

This issue was resolved in the 2.4.2 release on Oct 15 and has been pushed out to DockerHub. For convenience, here are the pull commands:

- `docker pull crunchydata/crunchy-postgres-gis:centos7-11.5-2.4.2`
- `docker pull crunchydata/crunchy-postgres-gis:centos7-10.10-2.4.2`
- `docker pull crunchydata/crunchy-postgres-gis:centos7-9.6.15-2.4.2`
- `docker pull crunchydata/crunchy-postgres-gis:centos7-9.5.19-2.4.2`

**Comment by mosinuga** [comment]
I think the latest image has broken collect - the scrape config introduces two labels and prometheus is therefore unable to connect to pgsql database - is this being looked at?

**Comment by mosinuga** [comment]
Also, the locale and collation, by default, in previous releases is not utf-8, though the documentation says it is.
