### ISSUE TITLE
PGBOUNCER_PASSWORD doesn't create a role named pgbouncer

### ISSUE THREAD

**Issue by J-A-B-R** [CrunchyData/crunchy-containers#1097]
**Describe the bug**
Specifying the environment variable PGBOUNCER_PASSWORD does not create a role named "*pgbouncer*" as stated in the *crunchy-postgres* container specification.

**To Reproduce**
1. Execute:
    ```
    docker run --rm -it -p 12000:5432 --name=crunchy-test --hostname=crunchy-test \
            -e PG_PRIMARY_HOST=crunchy-test \
            -e PG_PRIMARY_PORT=5432 \
            -e PG_PRIMARY_USER=primaryuser \
            -e PG_PRIMARY_PASSWORD=password \
            -e PG_MODE=primary \
            -e PG_USER=testuser \
            -e PG_PASSWORD=password \
            -e PG_ROOT_PASSWORD=password \
            -e PG_DATABASE=userdb \
            -e PGBOUNCER_PASSWORD=password
            crunchydata/crunchy-postgres:centos7-11.4-2.4.1
    ```
2. Wait until initialization ends.
3. Execute `psql -p 12000 -U postgres -c "\du"`.
4. No "*pgbouncer*" role is listed.

**Expected behavior**
A role named "*pgbouncer*" should have been created.

**Please tell us about your environment:**

* Operating System: Windows 8.1
* Where is this running ( Local, Cloud Provider): Local
* Storage being used (NFS, Hostpath, Gluster, etc): Local
* Container Image Tag: centos7-11.4-2.4.1
* PostgreSQL Version: 11
* Platform (Docker, Kubernetes, OpenShift): Docker Toolbox (Running on VirtualBox)
* Platform Version: 18.09.3, build 774a1f4eee (VirtualBox version: 6.0.8)

**Additional context**
The last image where a "*pgbouncer*" role is created seems to be "**centos7-11.3-2.3.2**".

**Comment by flamingdumpster** [comment]
You are correct. This behavior was removed in version 2.4.0. You will need to create the role manually. This was an oversight in the documentation for 2.4 - we will get that updated.
