### ISSUE TITLE
Collect image needs update

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/crunchy-containers#1105]
**Describe the bug**
Latest version of Pgmonitor is 3.2. pgbackrest queries were added in 2.4 but latest image of collect centos7-10.9-2.4.1 still doesn't have those
Collect image kinda depends on pgmonitor but it's dependency is unclear
```
ADD postgres_exporter.tar.gz /opt/cpm/bin
ADD tools/pgmonitor/exporter/postgres /opt/cpm/conf
```
**To Reproduce**
1. provision pgcluster from `centos7-10.9-2.4.1` with metrics=true
2. open collect container `ls -la /opt/cpm/conf`
3. no `queries_backrest.yml`

**Comment by cahoonpwork** [comment]
We have on our list to upgrade pgmonitor and to refactor how it is pulled in.  If you look at /bin/install-deps.sh  this is what is pulled in.

**Comment by jkatz** [comment]
Hi -- this was updated in the 2.4.2 release to use pgMonitor 3.2.
