### ISSUE TITLE
s3 config in pgo.yaml not picked up ?

### ISSUE THREAD

**Issue by narayaana** [CrunchyData/crunchy-containers#1107]
**Describe the bug**
When s3 config is configured in pgo.yaml, it is not found found at create cluster time.

**To Reproduce**
1. adapt settings as per attached pgo,yaml
2. run create command with pgbackrest-storage-type=s3
3. See error
```
pgo create cluster %CD_CLUSTER% -n %CD_NAMESPACE% --pgbackrest --storage-config primary --replica-count 1 --autofail --replica-storage-config primary --pgbackrest-storage-type=s3
Error: A configuration setting for AWS S3 storage is missing from pgo.yaml. Values must be provided for 'BackrestS3Bucket', 'BackrestS3Endpoint' and 'BackrestS3Region' in order to use the 's3' storage type with pgBackRest.
```

**Expected behavior**
pgo does find the values from pgo.yaml files and creates the cluster

**Please tell us about your environment:**

* Operating System: Windows
* Where is this running ( Local, Cloud Provider): AKS
* Storage being used (NFS, Hostpath, Gluster, etc): S3
* Container Image Tag: latest
* PostgreSQL Version: latest
* Platform (Docker, Kubernetes, OpenShift): AKS
* Platform Version: 4.0.0

**Additional context**
[kubectl-edit-trom0.yaml.txt](https://github.com/CrunchyData/crunchy-containers/files/3490984/kubectl-edit-trom0.yaml.txt)

**Comment by andrewlecuyer** [comment]
@narayaana it looks like you have duplicate entries for `BackrestS3Bucket`, `BackrestS3Endpoint` and `BackrestS3Region` in your `pgo.yaml`.  I see these settings at the top of your `pgo.yaml` with the values you intended to provide, but then again after `BackrestPort` with empty values (this is where they appear in the default `pgo.yaml` file).  The empty values will override the values you provided, resulting in the error you are seeing.

If you go ahead and remove the empty `BackrestS3Bucket`, `BackrestS3Endpoint` and `BackrestS3Region` settings from your `pgo.yaml`, the Operator should pick up the proper values and no longer throw the configuration error.

**Comment by narayaana** [comment]
The makedeploy is creating the duplicates. we had no duplicates in yaml. made makedeploy and then tried to remove the duplicates and it still did not work. We have duplicates only for S3* vars

**Comment by narayaana** [comment]
besides, we tried to dynamically edit config map dynamically and the error is still the same.

**Comment by lkhomenk** [comment]
you can edit pgo-config  ConfigMap - recreate postgres-operator pod to pickup new values and rety creating your cluster without `make deployoperator`
