### ISSUE TITLE
ST_AsMVT fails with ERROR:  Missing libprotobuf-c

### ISSUE THREAD

**Issue by mhiley** [CrunchyData/crunchy-containers#1108]
**Describe the bug**
Using the Docker image `crunchydata/crunchy-postgres-gis:centos7-11.3-2.4.0`, attempts to use`ST_AsMVT` and `ST_AsMVTGeom` fail with the error:

```
ERROR:  Missing libprotobuf-c
```
I haven't yet tested on other versions of `crunchy-postgres-gis`.

It seems that `protobuf-c` and `protobuf-c-devel` need to be included at compile time. (Installing them on the running container and restarting didn't seem to help.)

**To Reproduce**
On the `crunchy-postgres-gis` image, run a query that utilizes ST_AsMVT. An example usage is described here:

http://fuzzytolerance.info/blog/2018/01/03/Faffing-about-with-ST-AsMVT/

**Expected behavior**
The query should run without error.

**Please tell us about your environment:**

* Operating System: centos7
* Where is this running ( Local, Cloud Provider): running docker image locally under Docker for Mac
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag: crunchydata/crunchy-postgres-gis:centos7-11.3-2.4.0
* PostgreSQL Version: 11.3
* Platform (Docker, Kubernetes, OpenShift): Docker
* Platform Version:

**Additional context**
It would be great if libprotobuf-c is included in a way that enables usage of ST_AsMVT on the crunchy Postgres+PostGIS image, or if you guys have any advice on how to get this working that would be awesome. Thanks! 😃

**Comment by cahoonpwork** [comment]
Let me look into MVT for you.

**Comment by pramsey** [comment]
With PostGIS 2.5.3 against centos7 it should now be possible to build with protobuf support and get at least ST_AsMVT support, even if the protobuf version is not new enough to support the ST_AsGeoBuf format. @crunchyjohn maybe knows our schedule for taking advantage of that in our packaging chain.

**Comment by thesteve0** [comment]
Thanks for taking the time to file this! We are aware of the issue and working a potential fix through our engineering right now. Hope to have a fix relatively soon. @crunchyjohn should update here when something is in place.

**Comment by jkatz** [comment]
I believe this was resolved in 2.4.2, and certainly by 4.1.1.

**Comment by mhiley** [comment]
Awesome, thanks!

@guries-earthlinginteractive @wallaceatearthling looks like ST_asMVT should work on the latest crunchy postgres image.
