### ISSUE TITLE
Crunchy-postgres-database-pvc fails to start

### ISSUE THREAD

**Issue by magick93** [CrunchyData/crunchy-containers#111]
## Description
PG Crunchy container fails to successfully deploy/startup on OpenShift

## Versions

**OpenShift Master**:  v1.5.0-rc.0+49a4a7a

**Kubernetes Master**: v1.5.2+43a9be4

## Logs
```
 trap trap_sigterm SIGINT SIGTERM
+ date
Tue Apr 11 15:03:33 UTC 2017
+ source /opt/cpm/bin/setenv.sh
++ '[' -d /usr/pgsql-9.6 ']'
++ '[' -d /usr/pgsql-9.5 ']'
++ export PGROOT=/usr/pgsql-9.5
setting PGROOT to  /usr/pgsql-9.5
++ PGROOT=/usr/pgsql-9.5
++ echo 'setting PGROOT to ' /usr/pgsql-9.5
++ export PGDATA=/pgdata/pgdatabase
++ PGDATA=/pgdata/pgdatabase
++ export PGWAL=/pgwal/pgdatabase
++ PGWAL=/pgwal/pgdatabase
++ export PATH=/opt/cpm/bin:/usr/pgsql-9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ PATH=/opt/cpm/bin:/usr/pgsql-9.5/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
++ export LD_LIBRARY_PATH=/usr/pgsql-9.5/lib
++ LD_LIBRARY_PATH=/usr/pgsql-9.5/lib
++ chown postgres /pgdata/pgdatabase /pgwal/pgdatabase
chown: cannot access '/pgdata/pgdatabase': No such file or directory
chown: cannot access '/pgwal/pgdatabase': No such file or directory
+ source check-for-secrets.sh
```
I am using NFS.

I have set the host directory to have 777 permissions. 

## Events
```
5:36:09 PM	Warning	Unhealthy 	Readiness probe failed: setting PGROOT to /usr/pgsql-9.5 chown: cannot access '/pgwal/pgdatabase': No such file or directory psql: FATAL: role "piKcAdmin" does not exist
186 times in the last 33 minutes
5:35:19 PM	Warning	Unhealthy 	Readiness probe failed: chown: cannot access '/pgwal/pgdatabase': No such file or directory psql: FATAL: role "piKcAdmin" does not exist setting PGROOT to /usr/pgsql-9.5
5 times in the last 23 minutes
5:24:19 PM	Warning	Unhealthy 	Readiness probe failed: chown: cannot access '/pgwal/pgdatabase': No such file or directory setting PGROOT to /usr/pgsql-9.5 psql: FATAL: role "piKcAdmin" does not exist
```

## Other observations
There is no deployment config created. 
On the OpenShift webcosole, when I go` <Project>` > `Resources` > `Secrets`, then select a secret such as:

- pgmaster-secret
- pgroot-secret
- pguser-secret

Then reveal the username and password, none of them have the values there were set in the OpenShift template during the create phase.

**Comment by jmccormick2001** [comment]
I'd like to recreate this, what is the name of the template you are using?

**Comment by magick93** [comment]
I think it was called `crunchy-postgres-database-pvc`.

**Comment by jmccormick2001** [comment]
ah, that template doesn't use secrets for getting the password values, did you alter the example to have it use secrets?

**Comment by magick93** [comment]
No I didnt alter the template, just filled in the details.

Ok, so secrets are not used in this. That was just an observation that I thought might have been relevant. Nonetheless, it seemed to have problems with the ` /pgdata/pgdatabase` directory.

**Comment by jmccormick2001** [comment]
cool, if you could run the following commands and show me the output it would be great: 
oc get pvc
oc get pv

also if you could tell me the name of the PVC that you used

**Comment by magick93** [comment]
I've since removed the `dc` and `pod`, and am using the OOTB postgres container. 

However the `pv` is still there.

```
# oc describe pv myproject-master-pvc
Name:		myproject-master-pvc
Labels:		<none>
StorageClass:	
Status:		Bound
Claim:		myproject/master-pvc
Reclaim Policy:	Recycle
Access Modes:	RWO
Capacity:	1Gi
Message:	
Source:
    Type:	HostPath (bare host directory volume)
    Path:	/data/myproject/master-pvc
No events.

```

**Comment by jmccormick2001** [comment]
yeah, that PV definition appears to be using a HostPath type instead of NFS type...I have some scripts under examples/pv that you can use to create either a HostPath or NFS set of PVs if you want to use that for creating your PVs...within examples/envvars.sh there is a NFS_PATH variable that needs to be filled out to match your path.  That NFS_PATH variable is used for both a HostPath and NFS configuration, I probably need to rename it to PV_PATH which I'll likely do today to avoid confusion as to its purpose.  if you want to create NFS pv's, you would run 'create-pv.sh nfs', if you want to create HostPath pv's you would run 'create-pv.sh hostpath' for example.

**Comment by magick93** [comment]
Ok, cool. Thanks.

I will try that.

**Comment by jmccormick2001** [comment]
I'll close this one out unless you still are having a problem.
