### ISSUE TITLE
Got a PostgreSQL Alpine docker version?

### ISSUE THREAD

**Issue by lucenarenato** [CrunchyData/crunchy-containers#1130]
Got a PostgreSQL Alpine docker version?
Is there any sync replica example made in alpine or possibility of doing someday?
I liked the project is very safe.
Best regards Renato Lucena.

**Comment by jkatz** [comment]
Hi @lucenarenato,

Thanks for the kind words! We provide images based on CentOS 7 in our public repository and our examples for setting up replication use that. You can find an example of setting up a primary with a single replica using Docker over here:

https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/examples/postgresql/primary-replica/

We do periodically evaluate base images that we will support running PostgreSQL on. Thank you for the recommendation!
