### ISSUE TITLE
PostgreSQL 12 is released,  time to support 12

### ISSUE THREAD

**Issue by yjhjstz** [CrunchyData/crunchy-containers#1133]
https://github.com/postgres/postgres/releases/tag/REL_12_0 , any plan ?

**Comment by jkatz** [comment]
Hi @yjhjstz,

We are aware of the PostgreSQL 12 release and are very excited to include it in the Crunchy Container Suite in the future!

PostgreSQL 12 made significant changes to how database recovery is handled, and as such, we are taking some time to evaluate these changes before we release PostgreSQL 12 as part of the suite.

Additionally, the PostgreSQL [community roadmap](https://www.postgresql.org/developer/roadmap/) indicates that PostgreSQL 12.1 will be released on November 14. 12.1 will include bug fixes that should help make it easier to include and support PostgreSQL 12 in the suite.

Thanks!

**Comment by jkatz** [comment]
Hi @yjhjstz - We have released 4.1.1 of the Crunchy Containers which includes the container for PostgreSQL 12! You can read more about it here:

[https://github.com/CrunchyData/crunchy-containers/releases/tag/v4.1.1](https://github.com/CrunchyData/crunchy-containers/releases/tag/v4.1.1)

**Comment by yjhjstz** [comment]
that's cool.
