### ISSUE TITLE
Feature-request: comma separated list of databases in template.

### ISSUE THREAD

**Issue by magick93** [CrunchyData/crunchy-containers#114]
It would be nice if the templates could take a comma separated list of databases.

In some cases, it makes more sense to have a postgres server handling more than one database. Especially considering the resource cost of one more database is smaller compared to having to run database+database server.

**Comment by jmccormick2001** [comment]
Hi,  the postgres container is built to run a single postgres server inside it...on that server you can have any number of logical databases/schemas as with a normal postgres server.  By default I create a single 'database' on that server called 'userdb' and a single 'testuser' user account...but as you have full superuser access to that server using the 'postgres' account, you can create any objects on that postgres server you require.  regards

**Comment by magick93** [comment]
Thanks, yes I understand that it is possible to create more than one database.

To clarify, I think it could be useful if the OpenShift template(s) could take a comma separated list of databases.

**Comment by jmccormick2001** [comment]
ah, so let me make sure I understand, instead of passing 'userdb' into  thePG_DATABASE env var, you would want to pass in something like this "db1, db2, nextdb"?  it would create all of those databases instead of just the single 'userdb' that I use in the examples.

**Comment by magick93** [comment]
Yes, exactly.

**Comment by jmccormick2001** [comment]
I think I've decided to not include this feature, rather I'd like to see users that need this ability to place those sort of SQL statements in a setup.sql file that is configured and mounted in the /pgconf volume mount, this way users can override the default behavior as they wish...there are some examples of overriding the default setup.sql in the examples directory.
