### ISSUE TITLE
postgres replica container start problem

### ISSUE THREAD

**Issue by l241025097** [CrunchyData/crunchy-containers#1164]
**Describe the bug**
In crunchydata/crunchy-postgres:centos7-12.1-4.1.1 image, /opt/cpm/bin/start.sh, I found(line272-278):

    # In PostgreSQL 12, "trigger_file" => "promote_trigger_file"
    echo "promote_trigger_file = '/tmp/pg-failover-trigger'" > $RECOVERY_FILE_TMP <-------------
    # the primary_conninfo string stays mostly the same
    PGCONF_PRIMARY_CONNINFO="application_name=${APPLICATION_NAME} host=${PG_PRIMARY_HOST} port=${PG_PRIMARY_PORT} user=${PG_PRIMARY_USER}"
    echo "primary_conninfo = '${PGCONF_PRIMARY_CONNINFO}'" > $RECOVERY_FILE_TMP <-------------
    # append the contents of $RECOVERY_FILE_TMP to the postgresql.conf file
    cat $RECOVERY_FILE_TMP >> $PGDATA/postgresql.conf

Echo "promote_trigger_file = '/ TMP /pg-failover-trigger'" > $RECOVERY_FILE_TMP does not work

**Comment by jkatz** [comment]
Hi @l241025097,

This is now fixed and backpatched down to the `REL_4_1` line. The fix will appear in `v4.2.0` and `v4.1.2`.

Thanks for the report!
