### ISSUE TITLE
Can't setup  PGHA_WALDIR

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/crunchy-containers#1201]
**Describe the bug**
This line overrides `initdb` from `postgres-ha-waldir.yaml`
https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres-ha/pre-bootstrap.sh#L335

**To Reproduce**
1. Add PGHA_ENABLE_WALDIR + PGHA_WALDIR
2. Check initdb block in logs or in bootstrap file

**Please tell us about your environment:**

* Container Image Tag: centos7-10.11-4.2.1
* PostgreSQL Version: 10
* Platform (Docker, Kubernetes, OpenShift): 3.11
* Platform Version: 4.2.1

**Comment by jkatz** [comment]
@lkhomenk The file was reorganized. Is this still an issue?

Ref: [https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres-ha/bootstrap/pre-bootstrap.sh](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres-ha/bootstrap/pre-bootstrap.sh) i.e. I don't see initdb being called in here.
