### ISSUE TITLE
Collect in latter images seems to be broken

### ISSUE THREAD

**Issue by olefemmy** [CrunchyData/crunchy-containers#1210]
**Describe the bug**
Collect in latter images seems not to be able to connect to itself on port 9187. This version works: centos7-11.4-2.4.1. All subsequent images I have used don't work

**To Reproduce**
1. Download and run the crunchydata/crunchy-collect:centos7-12.2-4.1.2
2. bash-4.2$ timeout 1 bash -c "</dev/tcp/127.0.0.1/9187"
bash: connect: Connection refused
bash: /dev/tcp/127.0.0.1/9187: Connection refused

**Expected behavior**
The local collect container should listen on port 9187 and should be able to connect to itself.

**Screenshots**

**Please tell us about your environment:**

* Operating System: Docker on Ubuntu (Vagrant)
* Where is this running ( Local, Cloud Provider): Local and Cloud Provider
* Storage being used (NFS, Hostpath, Gluster, etc): overlay
* Container Image Tag:centos7-12.2-4.1.2
* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Docker
* Platform Version: Docker version 19.03.6, build 369ce74a3c

**Additional context**

**Comment by jkatz** [comment]
I just tested this the other day and it worked fine for me. What are you using for your environment variables?

I believe the environmental variables changed in 2.4.2, which could be why you are seeing that. They are specified here:

[https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-collect/](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/container-specifications/crunchy-collect/)

I believe I made one clarification to it, which you can see here:

[https://github.com/CrunchyData/crunchy-containers/commit/5cb3060dda608503ccd4d3e09a0452168f3c3098](https://github.com/CrunchyData/crunchy-containers/commit/5cb3060dda608503ccd4d3e09a0452168f3c3098)

which is unreleased, and likely could cause some confusion with the deployment (esp. if coming from the previous style of adding it in)

**Comment by olefemmy** [comment]
Thanks @jkatz! My environment file was only `DATA_SOURCE_NAME=postgresql://admin:password@wsppgsql:5432/postgres?sslmode=disable
COLLECT_PG_PASSWORD=password`
This did not work with the latest version. However, once I added 
`POSTGRES_EXPORTER_PORT=9187`, it worked like a charm.
Thanks

**Comment by olefemmy** [comment]
Problem with documentation/environment variable
