### ISSUE TITLE
crunchy-master pod dissapears when there are more pods deployed Kubernetes

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [CrunchyData/crunchy-containers#124]
I am seeing a behavior where the crunchy-master pod dissappears or goes into "completion" state when there are more pods deployed to the Kubernetes cluster.  Just checking if this is normal under heavy node usage.  Is there a way to see previous log of the crunchy-master pod?  I tried with kubectl logs <POD_NAME> --previous but don't see any.

**Comment by jmccormick2001** [comment]
strange!  you might try 'kubectl get pod -a' and see if the pod shows up at all...I've not seen that happen before...you might try looking at the kube logs as well and see if anything strange is logging...if this is repeatable, you might provide me the kube version you are running and how to recreate it.  regards.

**Comment by sonamsamdupkhangsar** [comment]
I am running on CoreOS stable (1298.7.0).  My kube version says:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:57:25Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2+coreos.0", GitCommit:"3ed7d0f453a5517245d32a9c57c39b946e578821", GitTreeState:"clean", BuildDate:"2017-01-13T00:23:19Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

The crunchy-master pod disappearing has been happening quite repeatedly.  However, the replica pod remains.  I am able to run helm and installing with the replace name to reuse the data that was created in nfs.  I will try the 'kubectl get pod -a' option when master disappears again.

**Comment by sonamsamdupkhangsar** [comment]
It happened again.  The crunchy-master pod disappeared.  The replica is still alive.  I don't see anything interesting when I ran the 'kubectl get pod -'.

**Comment by jmccormick2001** [comment]
so are you saying that something is totally deleting the master pod?  or is the master pod just exiting?  if you do a 'kubectl get pod -a' does it show up at all?

**Comment by sonamsamdupkhangsar** [comment]
I tried the 'kubectl get pod -a' and the master crunchy does not show up.

**Comment by jmccormick2001** [comment]
very weird, not sure what could be deleting the pod altogether like that...I'll try to test it out today using helm on kube 1.5

**Comment by jmccormick2001** [comment]
I tested this out just now without any issues, but I'm wondering if somehow helm could be removing the master?  When this happens again, you might check the helm/tiller pod log as in this command:

kubectl logs tiller-deploy-1172528075-3hnpc --namespace=kube-system

check to see if something is causing helm to delete the master...there is probably a way to see the kube logs too and check to see if errors are popping up there.
