### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by m-jayson** [CrunchyData/crunchy-containers#1257]
I've been looking for the right answer till i found out this .
I have a cluster raspberry pi, running microk8s kubernetes. And would like to take advantage of running postgresql in my kubernetes cluster.

I tried alot of examples but none of them worked. Just wanna ask if do we have support for arm devices on this?

Thanks

**Comment by jkatz** [comment]
All of our images are based on CentOS or UBI. They can run on any platform so long as your container platfom supports them (e.g. I'm running our containers on my Mac). I have not tried running them on an ARM platform.

We have no immediate plans to build ARM based images.

**Comment by ewdurbin** [comment]
Any chance this has been reconsidered?
