### ISSUE TITLE
s3 examples

### ISSUE THREAD

**Issue by ghost** [CrunchyData/crunchy-containers#1265]
are there any examples on how to configure s3?

backrest_aws_s3_endpoint  = http://bucket.s3-eu-west-1.amazonaws.com ?

do i have to change backrest_port aswell?

getting the following error
`time="2020-08-14T12:25:06Z" level=info msg="stderr=[ERROR: [031]: 'http://bucket.s3-eu-west-1.amazonaws.com' is not valid for option 'repo1-s3-endpoint'\n       HINT: port is not a positive integer.\n]"
`

**Comment by jkatz** [comment]
This is described in the documentation for the [PostgreSQL Operator](https://github.com/CrunchyData/postgres-operator):

- [https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#using-s3](https://access.crunchydata.com/documentation/postgres-operator/latest/architecture/disaster-recovery/#using-s3)

There are also some advanced examples on the blog:

- [https://info.crunchydata.com/blog/multi-kubernetes-cluster-postgresql-deployments](https://info.crunchydata.com/blog/multi-kubernetes-cluster-postgresql-deployments)

There may also be guidance in the [release notes](https://github.com/CrunchyData/postgres-operator/releases), depending on the feature:

- [https://github.com/CrunchyData/postgres-operator/releases](https://github.com/CrunchyData/postgres-operator/releases)
