### ISSUE TITLE
repo crunchypg12 wrong name

### ISSUE THREAD

**Issue by pmpetit** [CrunchyData/crunchy-containers#1268]
Hello, i ma testing building my own image:
in conf/crunchypg12

repo name is not crunchydb12 but crunchydatadevpg12

to make it ok, i have to change
[crunchydatadevpg12] to [crunchypg12],because 

        --disablerepo=crunchypg* \
        --enablerepo="crunchypg${PG_MAJOR//.}" \

fails

**Comment by jkatz** [comment]
We support a few different repos.
