### ISSUE TITLE
 Add the ability to use custom images.

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [CrunchyData/crunchy-containers#1280]
It would be nice to make such a possibility so that you can still substitute custom images when creating a database (specifically when upgrading a database through an operator). Because the default image is not enough for various purposes. 
And when replacing in the operator with --cpp-image-prefix from default to custom, this value applies to metrics and all other images. That is, the operator tries to download all images from a custom container, instead of downloading only the specified image. (For example, the image of the base, and the rest of the images use the default)
Could you consider this proposal and possibly make changes for this possibility?

**Comment by denishpatel** [comment]
I can use this as well. I'd like to build postgis image with plperl support.

**Comment by wayne-o** [comment]
I think this is exactly what I am after - I would like to use postgres with PLV8
