### ISSUE TITLE
Add plperl extension on postgis image

### ISSUE THREAD

**Issue by denishpatel** [CrunchyData/crunchy-containers#1287]
**What is the motivation or use case for the change? **
I'm testing deployment for postgres on k8s but we need plperl and postgis on the docker image

**Describe the solution you'd like**
How can i extend existing docker image ? or is it possible to add plperl in **postgis** crunchy image?

**Please tell us about your environment:**

k8s on azure

* Operating System: CentOs
* Where is this running ( Local, Cloud Provider): Azure
* Storage being used (NFS, Hostpath, Gluster, etc): Azure file
* Container Image Tag:
* PostgreSQL Version: 12.4
* Platform (Docker, Kubernetes, OpenShift): Kubernetes on Azure
* Platform Version:

**Comment by jkatz** [comment]
This seems pretty reasonable to add, and I believe we already have the machinery to do so. I am going to do some test builds to see how much weight it would add to the image, if anything.

**Comment by denishpatel** [comment]
Thanks @jkatz !
