### ISSUE TITLE
Postgres 4.6.0 General Availability (GA) date

### ISSUE THREAD

**Issue by vinodhreddygabbireddy** [CrunchyData/crunchy-containers#1319]
Hi Team,

Can you please let us know by when Postgres 4.6.0 becomes General Availability (GA). Let us know the date?

**Comment by jkatz** [comment]
Yes. As detailed in the [Releases](https://github.com/CrunchyData/postgres-operator#releases) section of the README, you can sign up for the [Crunchy Data Developer Program Newsletter](https://www.crunchydata.com/developers/newsletter).
