### ISSUE TITLE
Incorrect CrunchyPg repo name

### ISSUE THREAD

**Issue by MarekBiolik** [CrunchyData/crunchy-containers#1323]
Repo name should be change in build/..../Dockerfile (for example: build/postgres/Dockerfile)
"--enablerepo="crunchy**pg**${PG_LBL}" \ " to "--enablerepo="crunchy**datadevpg**${PG_LBL}" "

explanation:
After downoload crunchypg12:
"curl https://api.developers.crunchydata.com/downloads/repo/rpm-centos/postgresql12/crunchypg12.repo > conf/crunchypg12.repo"

in DockerFile is copy to etc/yum.repos.d/:
"ADD conf/crunchypg${PG_LBL}.repo /etc/yum.repos.d/"

and then is install:
STEP 11: RUN ${PACKAGER} -y install --setopt=skip_missing_names_on_install=False --disablerepo=crunchypg* --enablerepo="crunchypg${PG_LBL}" postgresql${PG_LBL} && ${PACKAGER} -y clean all

but if you check before install name of repo is:
crunchy**datadevpg**12 no crunchy**pg**12
![image](https://user-images.githubusercontent.com/61433855/107759940-4d209600-6d29-11eb-9b68-dcb785c70606.png)

**Comment by jkatz** [comment]
There are multiple repositories that can be used to build the containers.
