### ISSUE TITLE
Where CRUNCHY-GPG-KEY.public can be download?

### ISSUE THREAD

**Issue by MarekBiolik** [CrunchyData/crunchy-containers#1324]
For ubi8 for which DFSET is set as "rhel" is imported "CRUNCHY-GPG-KEY.public":
https://github.com/CrunchyData/crunchy-containers/blob/master/build/base/Dockerfile#L114

but I can't find any information where I can download it. 

For example RPM-GPG-KEY-crunchydata-dev is mention in instruction:
https://crunchydata.github.io/crunchy-containers/stable/contributing/building/
so I can just download:
"curl https://api.developers.crunchydata.com/downloads/gpg/RPM-GPG-KEY-crunchydata-dev > conf/RPM-GPG-KEY-crunchydata-dev"

and then there is no problem with import:
https://github.com/CrunchyData/crunchy-containers/blob/master/build/base/Dockerfile#L113

**Comment by jkatz** [comment]
UBI/RHEL support is [discussed in the documentation](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/overview/overview/).
