### ISSUE TITLE
Is there crunchy-postgres-ha image for PostgreSQL 12 and Crunchy Postgres Operator 4.6.x?

### ISSUE THREAD

**Issue by xt99** [CrunchyData/crunchy-containers#1334]
Hello everyone,

Can you please share (or build) `crunchy-postgres-ha` image for PostgreSQL 12 and Crunchy Postgres Operator 4.6.x? I can't find any at your official Docker Hub here https://hub.docker.com/r/crunchydata/crunchy-postgres-ha/tags?page=1&ordering=last_updated 

While 4.6.x Operator versions claims support for PostgreSQL 12 (https://github.com/CrunchyData/postgres-operator/releases/tag/v4.6.1 `PostgreSQL is now at versions ... 12.6`), I can't find any images for PostgreSQL 12 (while there are images for PostgreSQL 13). 

Thanks for any help!

**Comment by jkatz** [comment]
Please review our [release cadence](https://github.com/CrunchyData/postgres-operator#releases) information here:

https://github.com/CrunchyData/postgres-operator#releases

Not all images are pushed to DockerHub. The PostgreSQL 12 images are available on the [developer portal](https://www.crunchydata.com/developers/download-postgres/containers).
