### ISSUE TITLE
Building with CCP_BASEOS=ubi8 throws CRUNCHY-GPG-KEY.public import read failed(2)

### ISSUE THREAD

**Issue by rmccarth** [CrunchyData/crunchy-containers#1336]
**Describe the bug**
Setting `CCP_BASEOS=ubi8` and then running `make postgres` throws a key read error.

**To Reproduce**
1. Build the containers as instructed in the documentation, exporting CCP_BASEOS as ubi8. 
2. Run make postgres

**Expected behavior**
The container builds successfully. 

**Please tell us about your environment:**

* Operating System: Host: Centos8
* Where is this running ( Local, Cloud Provider): Azure
* Storage being used (NFS, Hostpath, Gluster, etc): N/A
* Container Image Tag: N/A
* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Docker
* Platform Version: buildah version 1.16.7 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)

**Comment by jkatz** [comment]
You can read about support for UBI containers in the documentation:

[https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/overview/overview/](https://access.crunchydata.com/documentation/crunchy-postgres-containers/latest/overview/overview/)

**Comment by rmccarth** [comment]
Ah great OK so perhaps instead of erroring ambiguously it should return a message stating that UBI builds are for data customers.

Thanks
