### ISSUE TITLE
Missing postgresql version in 4.6.2

### ISSUE THREAD

**Issue by vxst** [CrunchyData/crunchy-containers#1339]
**Describe the bug**
There is no image for PostgreSQL 12 with pgo version 4.6.2, which should be supported according to pgo release notes.

**To Reproduce**
1. Go to 'https://hub.docker.com/r/crunchydata/crunchy-postgres'
2. Click on 'Tags'
3. There is no tag for PostgreSQL 12, which should be supported by pgo 4.6.2.

**Expected behavior**
There is an image like crunchydata/crunchy-postgres:centos7-12.6-4.6.2

**Please tell us about your environment:**

* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Dockerhub

**Comment by jkatz** [comment]
The CentOS 7 images are no longer available in the Developer Portal. This is clearly stated on the website:

[https://www.crunchydata.com/developers](https://www.crunchydata.com/developers)

**Comment by vxst** [comment]
There should be an image like crunchydata/crunchy-postgres:centos8-12.6-4.6.2
