### ISSUE TITLE
Start a cluster from WAL-E backup?

### ISSUE THREAD

**Issue by DanielFerreiraJorge** [CrunchyData/crunchy-containers#134]
I have a production postgres streaming wal to s3 via wal-e... I want to start a cluster in kubernetes and retrieve the wals... is it possible?

**Comment by jmccormick2001** [comment]
my guess is not possible unless there is a Kube Persistent Volume adapter for S3, I'm not seeing one available after some slight searching...Amazon EBS works however.

**Comment by DanielFerreiraJorge** [comment]
Thank you for replying. I think there is a little misunderstanding regarding the question. I'm talking about delegating the backup/restore process to "WAL-E" (https://github.com/wal-e/wal-e). There is no need at all to "mount" S3 as a volume in kubernetes.

**Comment by jmccormick2001** [comment]
ah, thanks for the link, I have not looked at WAL-E before, but it looks very interesting and useful, currently I don't have an integration to it but it seems very useful and will give it some thought as to how to integrate with it.

**Comment by cahoonpwork** [comment]
Future enhancement to Operator project
