### ISSUE TITLE
Missing postgresql version in 4.6.2

### ISSUE THREAD

**Issue by vxst** [CrunchyData/crunchy-containers#1340]
**Describe the bug**
There is no image for PostgreSQL 12 with pgo version 4.6.2, which should be supported according to pgo release notes.

**To Reproduce**
1. Go to 'https://hub.docker.com/r/crunchydata/crunchy-postgres'
2. Click on 'Tags'
3. There is no tag for PostgreSQL 12, which should be supported by pgo 4.6.2, and is not drop support on Developer Portal. I understand PostgreSQL 11 and CentOS 7 is not available on Developer Portal, but PostgreSQL 12 + CentOS 8 + PGO 4.6.2 should be available on Developer Portal.

**Expected behavior**
There is an image like crunchydata/crunchy-postgres:centos8-12.6-4.6.2

**Please tell us about your environment:**

* PostgreSQL Version: 12
* Platform (Docker, Kubernetes, OpenShift): Dockerhub

**Comment by jkatz** [comment]
Please see https://github.com/CrunchyData/crunchy-containers/issues/1339
