### ISSUE TITLE
postgres-gis deployment doesn't seem to work for pgo 4.6.2 w/ tag centos8-13.2-3.0-4.6.2

### ISSUE THREAD

**Issue by mikeohyan** [CrunchyData/crunchy-containers#1357]
**Describe the bug**
Trying to deploy postgres-gis to GKE cluster doesn't seem to work. There are no pods created for the primary workload and the pg-backrest workload references an image that doesn't exist.

Should  note the the vanillla postgres and `postgres-gis-ha` both seem to be running just fine with my current setup.

**To Reproduce**
Running PGO 4.6.2 with the following command:
`pgo create cluster tdbgis --namespace="testdb" --ccp-image="crunchy-postgres-gis" --ccp-image-tag="centos8-13.2-3.0-4.6.2" --pvc-size="10Gi" --storage-config="gke-pd-standard" --metrics --pgbouncer`

**Expected behavior**

**Screenshots**

**Please tell us about your environment:**

Running on GKE (+ Rancher) and using the standard persistent disk from GKE as the storage medium.
Running PGO 4.6.2 and successfully deployed other types of clusters.

**Additional context**
I have no idea why there are no pods being deployed for the primary cluster workload, but I think the pgbackrest issue stems from a malformed generation of the image URL, this is where it's trying to pull from:
`"registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest-repo:centos8-13.2-3.0-4.6.2"`
Might just be the inclusion of the PostGIS version in the string.

_NB: This is my first bug report, so if I can do anything better/more helpful, please let me know!_

**Comment by jkatz** [comment]
> NB: This is my first bug report, so if I can do anything better/more helpful, please let me know!

Logs from the Pods would be most helpful :smile:

However, the likely culprit is 

> --ccp-image="crunchy-postgres-gis"

These needs to be `--ccp-image="crunchy-postgres-gis-ha"`, in which these is an example for doing so in the docs:

[https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#create-a-postgresql-cluster-with-postgis](https://access.crunchydata.com/documentation/postgres-operator/latest/pgo-client/common-tasks/#create-a-postgresql-cluster-with-postgis)

**Comment by mikeohyan** [comment]
Thanks, had no issue w/ the `crunchy-postgres-gis-ha` deployment. Just wanted to be thorough in testing all the cases. We've been trying to compile our own w/ PostGIS 3.1 and have TimescaleDB while we wait for 4.7.0.

And thanks for the note, will include the logs in the future.
