### ISSUE TITLE
Support of Postgres 11 with crunchy containers 4.7.0?

### ISSUE THREAD

**Issue by marco-devopsdojo** [CrunchyData/crunchy-containers#1365]
**Which example are you working with?**
I try to build the current version 4.7.0 of the crunchy-containers locally by my own for PG11 following the documentation here:
https://access.crunchydata.com/documentation/crunchy-postgres-containers/4.7.0/contributing/building/ as:
 _"With the release of PGO 4.7 on May 24, 2021, Crunchy Data will no longer provide PGO 4.4 container images in the Developer Portal through the Crunchy Data Developer Program. "_ - https://www.crunchydata.com/developers

but I am not able to do this.

**What is the current behavior?**
I try to build the crunchy-containers locally following the documentation with the following modifications for version 11, as I want version 11:
```
export CCP_PGVERSION=11        # The PostgreSQL major version
export CCP_PG_FULLVERSION=11.12
export  CCP_POSTGIS_VERSION=2.5 
```

Got an error:
```
Step 35/35 : RUN if [ "$BASEOS" = "centos8" ] ; then    ${PACKAGER} -qy module disable postgresql ; fi
 ---> Running in 8251bdbe3aa3
Error: Failed to download metadata for repo 'crunchypg11': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
```

I checked the rpm URL: https://repo.developers.crunchydata.com/postgresql11/centos/EL8/x86_64/ but it reads 404 not found...

**What is the expected behavior?**
Is it possible that the build will work with version 11 and if so, what do I have to change to get the build run.

**Other information** (e.g. detailed explanation, related issues,  etc)
A related issue / question is https://github.com/CrunchyData/crunchy-containers/issues/1364 

**Please tell us about your environment:**
Operating System: Ubuntu 8
Where is this running ( Local , Cloud Provider): Local
Storage being used (NFS, Hostpath, Gluster, etc): SSD
Container Image Tag: centos8-11.12-4.7.0
PostgreSQL Version: 11.12
Platform (Docker, Kubernetes, OpenShift): Docker
Platform Version: 20.10.2

**Comment by jkatz** [comment]
There was a notice on the Developer Portal for several months in the fall, in addition to an email to the [developer portal mailing list](https://www.crunchydata.com/newsletter/) that the PG11 images would no longer be available after Dec 31, 2020.

All images + packages are still available in the customer portal.
