### ISSUE TITLE
statefulset folder missing?

### ISSUE THREAD

**Issue by khteh** [CrunchyData/crunchy-containers#1369]
** Which example are you working with? **
https://kubernetes.io/blog/2017/02/postgresql-clusters-kubernetes-statefulsets/
**What is the current behavior?**
I don't find statefulset folder here
**What is the expected behavior?**
statefulset folder with manifests in it.
**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System: Ubuntu
* Where is this running ( Local , Cloud Provider) Local
* Storage being used (NFS, Hostpath, Gluster, etc): NFS / Hostpath
* Container Image Tag: 13.3
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift): K8s
* Platform Version:

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by jkatz** [comment]
[PGO 5](https://access.crunchydata.com/documentation/postgres-operator/v5/) uses Statefulsets for Postgres instances. I would recommend using that if you are managing Postgres instances in Kubernetes.
