### ISSUE TITLE
pgbackrest should be compile with zstd support

### ISSUE THREAD

**Issue by Jean-Daniel** [CrunchyData/crunchy-containers#1394]
**What is the motivation or use case for the change? **

Actually, pgbackrest supports multiple compressions algorithms, including Zstd 

https://pgbackrest.org/configuration.html#section-general/option-compress-type

For the same compression ratio, Zstd is faster than any other supported alternative, but it must be explicitly enable at compile time.

As the pgbackrest image already include `libzstd.so`, it should be only a small change.

**Comment by jkatz** [comment]
Tracking this at https://github.com/CrunchyData/postgres-operator/issues/2706
