### ISSUE TITLE
Allow usage of TimescaleDB Community Edition

### ISSUE THREAD

**Issue by stoetti** [CrunchyData/crunchy-containers#1409]
We are using features of TimescaleDB-extension that are only available in the community edition. Due to the support for ha-operation of postgres-cluster provided by the postgres-operator we need to use the matching postgres-image. Unfortunately this image only includes the OSS-licensed version of the extension.

We are now building an image based crunchy-postgres image and uninstall the OSS-version before installing the community edition from the timescale repository directly. As others may also want to use the extended functionality of the extension it would be great if that version could be included in the image or an alternative image could officially be shipped.

Here are is the documentation of the feature comparison: https://docs.timescale.com/timescaledb/latest/timescaledb-edition-comparison/

**Comment by David-Angel** [comment]
Use this to enable the community edition by creating a custom docker image:
https://github.com/CrunchyData/postgres-operator/issues/2692#issuecomment-1687095661


It would be very nice to have this without a custom build.

**Comment by prlaurence** [comment]
Closing this thread out. As noted in the thread, we include the TimescaleDB Apache 2 Edition in our container images. The TimescaleDB Community Edition is subject to the Timescale License Agreement and as a result not something that Crunchy Data packages or distributes. There are some comments in this thread regarding approaches to modifying the container images to add the TimescaleDB Community Edition extension. Crunchy Data has not validated these approaches.
