### ISSUE TITLE
How this setup recovers already failed master?

### ISSUE THREAD

**Issue by guptaarvindk** [CrunchyData/crunchy-containers#141]
In the architecture presented, What happened to master which was failed and comes back up again?how previously failed  master recovers database and how it can be made a new slave?
Thanks,
-Arvind

**Comment by jmccormick2001** [comment]
I'm thinking now about how to implement some sort of automated failover, there are various ways and scenarios as you can imagine.  One solution would be to create a 'watcher' that would have the responsibility to watch a master's health and if it deems the master as 'failed', would trigger a failover on an available slave.  When a master runs in a Deployment, Kubernetes itself can restart the master on another node in the case of a complete node failure, this is something to consider as well.  So there is this potential race condition when kubernetes is restarting a master and when a 'watcher' would perform a failover that needs to be considered.  There is also the complication of shared storage and the case where a node is perceived to have failed but the pod is still left running, this is a dangerous situation in that a new master could be started and potentially corrupt the data files if an existing master is still connected somehow to the persistent storage which can be shared between multiple pods.  Needless to say I'm considering these options and will come up with something to support some of these situations.  Happy to hear your thoughts on this and other scenarios that you have in mind.

**Comment by jmccormick2001** [comment]
forgot to add, what exists today is the container called 'crunchy-watch', take a look at the examples for it, it performs a form of automated failover when you have deployed a master and a set of slaves...I'm going to build something more advanced in the postgres-operator project as well.

**Comment by guptaarvindk** [comment]
Thanks Jeff, really appreciate for your detailed answers. I am fairly new to postgres world, so please feel free to correct me, if I am asking any already answered question. 

I did looked at crunchy-watch container , but that only take care of switching from slave to master once original master is died. But I don't see anything where it attempt to bring the old master back up online as new slave or master. 

What I see most challenging is re-syncing the database of down master when it comes back. I was trying to setup master as replication controller so that once master pod dies, it comes back on another node some time later. But while this pod is down during that time new master would move forward and update the database. Now when this old master comes back online, there are few things need to be considered:
1) as previous role of this pod was master it will again try to become master causing conflict as there is another master now. I think solution to this problem could be that registry of master slave should be managed by an external pod (may be watch pod) not as individual env variable. So all pod will start similarly and then fight to become master with watch container. Watch can make first requester as master and rest will assume the role of slave. Once master goes down, watch can pick a new master and make old master as slave in its registry. Now when old master comes back it will query watch again that can it become master or slave, watch will tell it to be slave this time.  We also need to make watch a replication container as its going to be critical container governing others.
2) Once old master is coming back its database is behind. First way I have seen is, people recommend to start from scratch and simply make a fresh clone of the current master, which is really not a good solution for larger databases. So second better way I see is pg_Rewind function. I haven't tired it myself , but as I haven't seen it in many tutorial/articles on this, Also it need enough WAL record to recover completely, SO that makes me little skeptical if this will be full proof solution or not. As may be it works with my small database for now (less WAL records needed), but may be for larger databases it may fail. So I am not really able to find any good solution being used for this purpose.
3) pgpool will give up on old master, so how to bring it back to pool of pgpool? as I understand pgpool need modification in its config file, and will need restart. thats also little annoying as that means further downtime because of pgpool restart. 

Thanks,

**Comment by jmccormick2001** [comment]
this is some good input/ideas...I could see adding a capability to crunchy-watch to attempt to bring the failed master back into the cluster as a slave after a failover...also, I was thinking about retaining the PID within the /pgdata instead of /tmp, this way, a failed database, one that would not remove the PID after a clean shutdown, would be easy to spot, other masters that see an existing PID would not start, I could see that as useful to detect whether another master already has been started, this could occur if a kube node is considered 'down' but the pods on it are still up for example.

**Comment by guptaarvindk** [comment]
Thanks Jeff,

Sounds perfect. Yes keeping  track of master slave outside the master slave container is best way to faster detect master down and upgrade slave to master and then bring back the old master. I would be happy to try out your solution one you have.

One more question. I see in your watch container, you are directly calling "kubectl pod delete", is it safer to do? no security risk in this kind of approach? is it possible those kind of access may be blocked by kubernete/docker in future?

**Comment by jmccormick2001** [comment]
eventually the kubectl and oc commands will be replaced by client-go API calls, its in the works to do in a future version of the watch container.
