### ISSUE TITLE
helm charts

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#142]
create helm charts for a basic set of examples.

**Comment by jmccormick2001** [comment]
https://github.com/kubernetes/charts/issues/809#issuecomment-326333594

**Comment by xenophenes** [comment]
To do :

Bring the basic and primary-replica charts up to standard so they can be submitted to the official Helm repository. 

Add statefulset, template-sml charts.

**Comment by jmccormick2001** [comment]
merged.
