### ISSUE TITLE
Component for autoscaling

### ISSUE THREAD

**Issue by Tedezed** [CrunchyData/crunchy-containers#143]
I am working on a project to cover the temporary need to auto-scale the StatefulSet automatically. https://github.com/Tedezed/slug-containers/tree/master/statefulset_autoscaler/docker/slug_statefulset_autoscaler

I think it might be interesting for the crunchy-containers,  create a new component  based  on crunchy-watch. This new component would be responsible to failover and auto-scaling of the stanby nodes of PostgreSQL according to their CPU load using Heapster.

What do you think about the proposal?

Regards!

**Comment by jmccormick2001** [comment]
this sounds interesting and useful....I have a golang version of crunchy-watch which I'm planning on switching over to in an upcoming release.  Let me give this some serious thought as to how it could be integrated.

**Comment by Tedezed** [comment]
At first moment, the script can increase the number of replicas without problems. The only problem is to reduce the number of replicas, since the master should be assigned to the replica number 0 because Kubernetes will always delete from highest to lowest number of replicas.

Related to:
https://github.com/CrunchyData/crunchy-containers/blob/master/bin/watch/start.sh#L119-L132

I consider making sure that the master is always replica number 0 before reducing of replicas, although I do not know if this is in charge in this moment of the watch component.

**Comment by Tedezed** [comment]
Currently: https://github.com/kubernetes/kubernetes/issues/44033
