### ISSUE TITLE
Postgres 14 missing from crunchy-upgrade image version 5.2.0

### ISSUE THREAD

**Issue by szelenka** [CrunchyData/crunchy-containers#1478]
**Describe the bug**
It's not possible to build a custom image to upgrade to Postgres 14. 

In version 5.0.3 version 14 was introduced, and in 5.0.4 it says the cruncy-upgrade image was updated with all available Postgres versions:
https://access.crunchydata.com/documentation/postgres-operator/latest/releases/5.0.4/

However, the case statement for `$NEW_VERSION` is missing "14":
https://github.com/CrunchyData/crunchy-containers/blob/v5.2.0/bin/upgrade/start.sh

**To Reproduce**
Attempt upgrade to Postgres 14
```bash
docker run -it registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.2.0-0 bash -c 'cat /opt/crunchy/bin/start.sh'
```

**Expected behavior**
Be able to use the operator to upgrade to Postgres 14

**Comment by tjmoore4** [comment]
@szelenka It is possible to upgrade to Postgres 14 with PGO, as described in the following [blog](https://www.crunchydata.com/blog/easy-major-postgresql-upgrades-using-pgo-v51). The referenced `start.sh` script is an outdated artifact.
