### ISSUE TITLE
crunchy-pgbackrest:centos8-2.35-0 seems to be gone

### ISSUE THREAD

**Issue by benjamin-bergia** [CrunchyData/crunchy-containers#1496]
Since yesterday all my backup pods fail to schedule with an ImagePullBackoff error.
It looks like registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.35-0 is not available anymore and I am not able to list the available tags on the registry.

Has the image been removed or is there something going on with the registry?

**Comment by faraonc** [comment]
It seems like a bunch of images are gone e.g.

```
registry.developers.crunchydata.com/crunchydata/crunchy-postgres-ha:centos8-13.4-0
registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-2.33-2
```

Is there anyway we can push those images back or a way for us to build them?

**Comment by strowi** [comment]
It seems this is all related to some license/policy changes (cant' find it anymore, but showed up in some pop-up on a crunchydata website). 
`registry.developers.crunchydata.com` seems to be deprecated and there will be no more publicly available images, but instead we are supposed to build them ourselfs from this repo which is currently also doesn't work (please correct me if i am wrong!).

**Comment by andrewlecuyer** [comment]
With the release of Crunchy Postgres for Kubernetes v5.0.5 & v4.7.6, we announced that Crunchy Postgres for Kubernetes would now be built for UBI 8 only.  For instance, the release announcement for v4.7.6 contained the following:

> Crunchy Postgres for Kubernetes 4.7.6 is built and distributed on UBI 8 minimal images only, but they are completely portable for other EL-8 distributions.

This was specifically done in accordance with the end of maintenance support for CentOS 8 as of December 31, 2021, and is the reason CentOS 8 images are no longer available in the Crunchy Developer Registry.

However, we do continue to provide UBI 8 builds, which you should be able to safely migrate to if currently using CentOS 8.  We therefore recommend that you upgrade to the [latest Crunchy Postgres for Kubernetes release](https://access.crunchydata.com/documentation/postgres-operator/latest/) to leverage the latest UBI 8 containers available.

Additionally, I also recommend subscribing to the Developer Portal mailing list to stay informed about the latest Crunchy Postgres for Kubernetes releases, as well as any additional details about available containers/builds, end-of-life notices, etc.  You can find a link for signing up on the [Containers page](https://www.crunchydata.com/developers/download-postgres/containers) of the [Crunchy Developer Portal](https://www.crunchydata.com/developers).

And regarding @strowi's comment, I do want to again clarify/reiterate that we do indeed continue to make images available via the Crunchy Developer Registry (registry.developers.crunchydata.com).  Please see the following link for more information about available containers:

https://www.crunchydata.com/developers/download-postgres/containers

_If you visit the [RPM's page](https://www.crunchydata.com/developers/download-postgres/binaries), you will see that it is the Developer Portal RPM's (and not the Developer Portal Containers) that are no longer being built and maintained._

**Comment by faraonc** [comment]
> With the release of Crunchy Postgres for Kubernetes v5.0.5 & v4.7.6, we announced that Crunchy Postgres for Kubernetes would now be built for UBI 8 only. For instance, the release announcement for v4.7.6 contained the following:
> 
> > Crunchy Postgres for Kubernetes 4.7.6 is built and distributed on UBI 8 minimal images only, but they are completely portable for other EL-8 distributions.
> 
> This was specifically done in accordance with the end of maintenance support for CentOS 8 as of December 31, 2021, and is the reason CentOS 8 images are no longer available in the Crunchy Developer Registry.
> 
> However, we do continue to provide UBI 8 builds, which you should be able to safely migrate to if currently using CentOS 8. We therefore recommend that you upgrade to the [latest Crunchy Postgres for Kubernetes release](https://access.crunchydata.com/documentation/postgres-operator/latest/) to leverage the latest UBI 8 containers available.
> 
> Additionally, I also recommend subscribing to the Developer Portal mailing list to stay informed about the latest Crunchy Postgres for Kubernetes releases, as well as any additional details about available containers/builds, end-of-life notices, etc. You can find a link for signing up on the [Containers page](https://www.crunchydata.com/developers/download-postgres/containers) of the [Crunchy Developer Portal](https://www.crunchydata.com/developers).
> 
> And regarding @strowi's comment, I do want to again clarify/reiterate that we do indeed continue to make images available via the Crunchy Developer Registry (registry.developers.crunchydata.com). Please see the following link for more information about available containers:
> 
> https://www.crunchydata.com/developers/download-postgres/containers
> 
> _If you visit the [RPM's page](https://www.crunchydata.com/developers/download-postgres/binaries), you will see that it is the Developer Portal RPM's (and not the Developer Portal Containers) that are no longer being built and maintained._


I understand (at least most of us) the reasoning behind the removal. However. not everyone or company has the capacity to upgrade especially if priorities are shifting. I do understand that the provided softwares are free, and it is up to the consumers to  do diligent on backing up free softwares hence tools like Artifactory or other proxies exist.

As a developer advocate for other tools out there, I do have to stress out that deprecating the software would have been the better approach rather than removing publicly available images. This just maintains a good relationship with consumers and support/consideration for enterprise offerings.

**Comment by benjamin-bergia** [comment]
Thanky you @andrewlecuyer.

I saw the notice but when I read end of support I thought about no new images or updates to the existing images. I didn't think about the removal of the existing images.

Like @faraonc mentioned, upgrade of the operator are major operation and I didn't get around to schedule it yet.

**Comment by strowi** [comment]
@andrewlecuyer thank you for the explanation! I was testing the quickstart via the crunchy-containers, which had trouble pulling images from `https://registry.developers.crunchydata.com/` and visting that site showed me this messsage:

`{ "errors":[{"code":"404","message":"This container version is no longer available from the Crunchy Data Developer Program. For information on accessing these containers, please contact info@crunchydata.com." }]}`
