### ISSUE TITLE
update dedicated documentation

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#153]
it would be helpful to extract only the relevant container information from containers.asciidoc and repeat that information within the dedicated.asciidoc....the dedicated templates only use a few containers, not all.  So we want to tailor this document for that purpose to make dedicated.asciidoc be all a user would need as a reference.

**Comment by xenophenes** [comment]
Are all the containers that dedicated.asciidoc use already referenced within the document, or are there some that aren't already present? Are you referring to simply including the installation of Openshift as well as including Openshift tips within the dedicated document?

**Comment by xenophenes** [comment]
Issue resolved.
