### ISSUE TITLE
Cannot build postgres 15

### ISSUE THREAD

**Issue by RobKenis** [CrunchyData/crunchy-containers#1543]
**Describe the bug**
Cannot build docker image for postgres 15 because RPM sources are not present on https://repo.developers.crunchydata.com

**To Reproduce**
1. Run `make postgres`

**Expected behavior**
An image is built

**Comment by vvanouytsel** [comment]
I have also noticed the same issue.
This seems to return an empty response.
```bash
curl https://api.developers.crunchydata.com/downloads/repo/rpm-centos/postgresql15/crunchypg15.repo
```

**Comment by mjtice** [comment]
It looks like if you want RPMs for Postgres > 14 then you've got to pay up?

> Note: These RPMs are no longer being updated. If you would like more recent versions, please consider getting a [Crunchy Data support subscription](mailto:info@crunchydata.com)

https://www.crunchydata.com/developers/download-postgres/binaries

**Comment by RobKenis** [comment]
We have solved the issue by moving to another operator.
