### ISSUE TITLE
crunchy-watch: confusion in function standalone_failover

### ISSUE THREAD

**Issue by galindro** [CrunchyData/crunchy-containers#156]
I'll build crunchy-watch from sources to use it with docker swarm mode. Until [this functionality](https://github.com/moby/moby/issues/27552) is ready to use, I'll use [rexray s3fs](https://rexray.readthedocs.io/en/stable/user-guide/docker-plugins/#simple-storage-service) to mount /tmp in master and slave replicas (I have a fixed number of replicas) and share it with crunchy-watch service.

Looking at [standalone_failover function](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/watch/start.sh#L82), the lines 88 and 89 are a bit confuse:

```bash
88.	echo "creating the trigger file on " $PG_MASTER_SERVICE
89.	docker exec $PG_SLAVE_SERVICE touch /tmp/pg-failover-trigger
```

Does `pg-failover-trigger` file needs to be created in slave container right? So, the message in line 88 is wrong...

**Comment by jmccormick2001** [comment]
you are correct, that message needs to print the PG_SLAVE_SERVICE value instead of the master name.

**Comment by jmccormick2001** [comment]
just pushed a fix for this to master.  thanks for reporting this one!
