### ISSUE TITLE
client=FATAL:  data directory "/pgdata/peeking-mole-crunchy-master" has wrong ownership

### ISSUE THREAD

**Issue by ltgzs777** [CrunchyData/crunchy-containers#161]
[root@k8s-master1 kubehelm]# kubectl logs peeking-mole-crunchy-master
......
checking for PITR WAL files to recover with..
+ check_for_pitr
+ echo 'checking for PITR WAL files to recover with..'
++ ls -A /recover
temporarily starting db to run setup.sql
+ '[' '' ']'
+ echo 'starting db'
+ echo 'temporarily starting db to run setup.sql'
+ pg_ctl -D /pgdata/peeking-mole-crunchy-master start
server starting
waiting for pg to start up...
+ echo 'waiting for pg to start up...'
+ true
+ pg_isready --port= --host=peeking-mole-crunchy-master --username=master --timeout=2
peeking-mole-crunchy-master: - no response
2017-05-29 09:03:33 EDT [57]: [1-1] user=,db=,app=,client=FATAL:  data directory "/pgdata/peeking-mole-crunchy-master" has wrong ownership
2017-05-29 09:03:33 EDT [57]: [2-1] user=,db=,app=,client=HINT:  The server must be started by the user that owns the data directory.
+ '[' 2 -eq 0 ']'
+ sleep 2
+ true
+ pg_isready --port= --host=peeking-mole-crunchy-master --username=master --timeout=2
peeking-mole-crunchy-master: - no response
+ '[' 2 -eq 0 ']'
+ sleep 2
+ true
+ pg_isready --port= --host=peeking-mole-crunchy-master --username=master --timeout=2

......
[root@k8s-master1 kubehelm]#

NFS(ON the other one)：
[root@TT ~]# more /etc/exports 
/nfsfileshare2 192.168.3.0/24(rw,sync)
[root@TT ~]# 

[root@TT ~]# more /etc/passwd|grep postgres
postgres:x:26:26::/home/postgres:/bin/bash
[root@TT ~]#

[root@TT ~]# more /etc/group|grep postgres      
postgres:x:26:
[root@TT ~]# 

/etc/idmapd.conf：

[Mapping]

Nobody-User = postgres
Nobody-Group = postgres

[root@TT ~]# ll /nfsfileshare2
total 4
drwx------ 19 postgres postgres 4096 May 29 21:03 peeking-mole-crunchy-master
[root@TT ~]# 
![image](https://cloud.githubusercontent.com/assets/19546685/26551383/dcb84660-44b4-11e7-97bf-34e270c5829c.png)

**Comment by jmccormick2001** [comment]
Hi,  what version of the container are you running?  also what version of Kube are you running?  I'll try to look into this one today.  regards.

**Comment by ltgzs777** [comment]
oh，sorry！

![image](https://cloud.githubusercontent.com/assets/19546685/26613361/e98e6e08-45ec-11e7-9e10-164ad74043bd.png)


use kubeernets 1.6.x, but not use RBAC.

NFS on OS :
[root@TT nfsfileshare]# cat /etc/redhat-release 
CentOS release 6.8 (Final)
[root@TT nfsfileshare]# 

kubernetes and  Docker on OS:
![image](https://cloud.githubusercontent.com/assets/19546685/26614014/58f7e780-45f0-11e7-8a0c-5b4a31621455.png)

**Comment by jmccormick2001** [comment]
what version of the crunchy-postgres container are you running?

**Comment by ltgzs777** [comment]
get from:

root@k8s-kuserver1:~# git clone https://github.com/CrunchyData/crunchy-containers.git
Cloning into 'crunchy-containers'...
remote: Counting objects: 9720, done.
remote: Compressing objects: 100% (137/137), done.
remote: Total 9720 (delta 98), reused 92 (delta 37), pack-reused 9543
Receiving objects: 100% (9720/9720), 5.91 MiB | 851.00 KiB/s, done.
Resolving deltas: 100% (7376/7376), done.
Checking connectivity... done.
root@k8s-kuserver1:~#

**Comment by ltgzs777** [comment]
![image](https://cloud.githubusercontent.com/assets/19546685/26637741/e116412c-4652-11e7-8655-6e46f37990e6.png)

and on Kubernetes 1.5.1 use StatefulSets still error：
2017-05-25 02:36:21 EDT [38]: [1-1] user=,db=,app=,client=FATAL:  data directory "/pgdata/pgset-0" has wrong ownership
2017-05-25 02:36:21 EDT [38]: [2-1] user=,db=,app=,client=HINT:  The server must be started by the user that owns the data directory.

but，use command ”kubectl delete pod pgset-0”，Just One time only，then OK：
![image](https://cloud.githubusercontent.com/assets/19546685/26637990/9299d864-4653-11e7-8efb-7c1210e834a0.png)

and the first pgset-1，crash one time，then OK！

and use“kubectl scale statefulset pgset --replicas=3” add the second pgset-2，need crash 7times，then OK.

**Comment by jmccormick2001** [comment]
if you are running selinux you might try disabling it, I've seen weird file permission errors like that when selinux is enabled but the NFS is not labeled correctly.

**Comment by ltgzs777** [comment]
Kubernetes 1.6.x run under Ubuntu 16.04，and Ubuntu OS not install selinux：
root@k8s-kuserver3:~# sestatus -v
The program 'sestatus' is currently not installed. You can install it by typing:
apt install policycoreutils
root@k8s-kuserver3:~# 

NFS run under CentOS6.5：
[root@TT ~]# sestatus -v
SELinux status:                 disabled
[root@TT ~]#

**Comment by jmccormick2001** [comment]
did you ever resolve this?  sorry for the delay in getting back to review this.
