### ISSUE TITLE
Permissions needed for pg-watcher sa in kub example of watch

### ISSUE THREAD

**Issue by colemanserious** [CrunchyData/crunchy-containers#175]
examples/kube/watch/run.sh sets up a new serviceaccount, pg-watcher, which is then used in watch-pod.json.  run.sh doesn't do anything to set up roles or privileges for that serviceaccount.   run.sh shows some commented out commands for setting up privileges in openshift: please update to show guidance for k8s.

**Comment by jmccormick2001** [comment]
thanks, I'll take a look, I noticed yesterday that I'd left off the --token=$TOKEN from the kubectl commands within the start.sh script, I suspect that could also be causing some issues but will attempt to recreate the permission issue today.

**Comment by jmccormick2001** [comment]
curious if you are running your api server with authorization-mode=ABAC and authorization-policy-file=/etc/somepolicyfile?

**Comment by jmccormick2001** [comment]
also, if you can provide the kube version that would be useful too

**Comment by jmccormick2001** [comment]
I added some policy notes in https://github.com/CrunchyData/crunchy-containers/blob/master/docs/containers.adoc that hopefully will be helpful.

**Comment by colemanserious** [comment]
Using authorization mode of RBAC on 1.5.  Yes, I know RBAC is only alpha in 1.5.  Thanks for the policy notes.  If I read right, you've suggested that the serviceaccount should receive a clusterRoleBinding to clusteradmin?  Would request a more specific role that can be applied to a namespace.  Context: we're working in a multi-tenant K8S cluster.  The pgwatcher serviceaccount created in a specific namespace should not have privileges across the full cluster.

**Comment by jmccormick2001** [comment]
I think this might be closer to what you are looking for given your use case, this specifies the default namespace in this example:

kubectl create rolebinding my-sa-binding --clusterrole=admin --serviceaccount=default:pg-watcher --namespace=default

**Comment by colemanserious** [comment]
On 1.5, you actually need to create a RoleBinding yml/json object and do a create -f, it appears.  There's no kubectl create rolebinding command: we resolved by tracking back into a tagged version of the kubernetes documentation and finding the corollary info.

**Comment by jmccormick2001** [comment]
ah!  I've updated containers.adoc with a note about this, let me know if we need to reopen this issue but I figured it was about closed at this point.  cheers and thanks for pointing this out!
