### ISSUE TITLE
Issue with a template

### ISSUE THREAD

**Issue by thesteve0** [CrunchyData/crunchy-containers#2]
Hey there:
This template
https://github.com/CrunchyData/crunchy-containers/blob/master/examples/openshift/master-slave-dc/master-slave-rc-dc-ict.json

uses an image stream (with latest) but there is no image stream defined anywhere else. It seems almost all the other templates use an actual image with a tag rather than an image stream. 

Also, what does ict stand for. 

Can we get a readme for some of the examples so, you know, if you want to demo them or something we know which one to use ;)

I am going to pull the 1.2.1 images into my all-in-one for the workshop. Let me know if I need to rebuild my image

**Comment by thesteve0** [comment]
Same thing with the master dc slave only. I am going to give you a pull request on this one .

**Comment by jmccormick2001** [comment]
the master-slave-rc-dc-ict.json file is an example of using an Image Change Trigger (ict) and is left there just as a reference of this concept.  All the examples are documented in the docs directory:  standalone.asciidoc is for running the examples in a Docker only environment, openshift.asciidoc is for running the examples in openshift, portworx.asciidoc is for running the examples using Docker and the Portworx volume driver technology, and kubernetes.asciidoc is for running the examples in the kube environment.

**Comment by jmccormick2001** [comment]
I'm moving to a new naming convention on the container tags, it will now include the 
base image OS and the postgres version within the tag name, this should offer users a better
way to know exactly what they are running and help me offer better support when they hit issues.
so you'll see a container tag like this:  crunchydata/crunchy-postgres:centos7-9.5-1.2.1.1
which means it uses the Centos7 base image, and the Postgres 9.5 database, and is at
a release level of 1.2.1.1

I'll also transition all example templates to use the centos/9.5 version as the example image to be consistent and also this is what I push to dockerhub.  RHEL versions are built upon demand and distributed upon demand to Crunchy enterprise customers.
