### ISSUE TITLE
standardize container names

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#212]
simple task of standardizing all container names for the examples, the container name for the database container will be 'database' for example.

spec:
  containers:
  - name: database

**Comment by xenophenes** [comment]
Would you mind explaining more what you want accomplished with this?

i.e., are you asking instead of ms-master being the name of the container for the master-replica example, it should be "database"?

**Comment by jmccormick2001** [comment]
merged into master.
