### ISSUE TITLE
application not being able to connect via pgpool 

### ISSUE THREAD

**Issue by syamgk** [CrunchyData/crunchy-containers#24]
While trying to run mattermost on openshift.
It's working successfully if connects directly to master postgresql instance
and when tries connecting via pgpool it is failing and throwing the below error:

```
[EROR] Failed to retrieve user profiles
team_id=5esim8ypjpbdub75hy693nwfny, err=SqlUserStore.GetProfiles:
store.sql_user.get_profiles.app_error, read tcp
x.x.x.x:49766->x.x.x.x:5432: i/o timeout
```

**Comment by jmccormick2001** [comment]
hmmn, if you could send me the logs from when you create the pgpool container I'll take a look.

**Comment by syamgk** [comment]
build logs  and the way to build it are here,
https://pad.riseup.net/p/build_log

**Comment by jmccormick2001** [comment]
thanks, could you send next the Openshift JSON template you are using to create the pods?

**Comment by jmccormick2001** [comment]
also, your pgpool config files you are using if possible would be useful to review.

**Comment by syamgk** [comment]
Here you can find the JSON files,
https://gitlab.com/sgk/mattermost
and the pgpool conf here,
https://github.com/syamgk/crunchy-containers/tree/master/conf/pgpool

thanking you too, also please do ask if more info is needed from my side

**Comment by syamgk** [comment]
might need to change the image to the custom build one 
https://gitlab.com/sgk/mattermost/blob/master/pgpool-rc.json#L90

**Comment by jmccormick2001** [comment]
see if you can connect using the psql client as follows:

psql -h pgpool.pgproject.svc.cluster.local -U testuser userdb

here you will replace pgproject with your openshift project you have chosen.  Once you connect,
see if you can create a table and query it.

**Comment by syamgk** [comment]
I am being able to connect to the db using psql, even while running mattermost across pgpool the user-creation, chat and everything is working properly.
this is happening only while accessing system console and some other points.
Ref: http://forum.mattermost.org/t/mattermost-fails-connecting-to-pgpool/2369

And everything is working fine if run it across master container or any other single instance postgres.

**Comment by jmccormick2001** [comment]
probably what is happening is the application (mattermost) is trying to use a database/user combination that is not configured within the pgpool configuration is my guess based on this log message, probably something the app developers can take a look at.  you might look at your postgres container as the postgres user and see what databases/users the application has created if any to better debug this.

**Comment by syamgk** [comment]
all tables are owned by testuser in this case and mattermost is trying to access the db as testuser
and the same container is working fine without any errors if directly connects to master( postgres instance in the cluster). so I suspect it might be some problem happening in the pgpool area.

**Comment by jmccormick2001** [comment]
just to confirm, are **all** the mattermost tables created in the 'userdb' database and owned by the 'testuser'?  If any of the mattermost tables are in the 'postgres' or other database you'll see an error from pgpool.

**Comment by syamgk** [comment]
https://pad.riseup.net/p/pgtables
these are the tables inside userdb

**Comment by syamgk** [comment]
can also reproduce it by running on docker using docker-compose 
https://gitlab.com/sgk/mattermost-docker

**Comment by jmccormick2001** [comment]
you might turn on SQL logging in pgpool's config, this will tell you what SQL statement is triggering the error...log_statement when set to true will cause all the SQL statements to be logged inside the container to the pgpool log file.

**Comment by jmccormick2001** [comment]
just checking to see if you had any updated status?  were you able to identify the SQL statements with pgpool logging?
