### ISSUE TITLE
Incorrect environment variable name in install.asciidoc

### ISSUE THREAD

**Issue by jerrywardlow** [CrunchyData/crunchy-containers#25]
The environment variable being set in [Step 1](https://github.com/CrunchyData/crunchy-containers/blob/master/docs/install.asciidoc#step-1---project-directory-structure) of the installation docs is named incorrectly. Currently it is `CCP_IMAGE` but is referenced in the next line as `CCP_VERSION`. This causes the `pull-from-dockerhub.sh` script to fail.

**Comment by jmccormick2001** [comment]
thanks, just fixed it and pushed it to master.
