### ISSUE TITLE
pgAdmin4 container bug

### ISSUE THREAD

**Issue by the1forte** [CrunchyData/crunchy-containers#253]
When accessing pgAdmin4, the following Error message pop-up window appears:

"Error loading script - /debugger/js/debugger"
Error message
undefined

**Comment by xenophenes** [comment]
Hello! Looking into this. What platform are you on (CentOS, RHEL) and what application (Docker, OpenShift, Kubernetes)? What version of the Container Suite are you on?

**Comment by xenophenes** [comment]
Hello Chris, have you been able to figure out this issue or is the problem still occurring?

**Comment by the1forte** [comment]
Hi Sarah,
Sorry for the late reply, I don't check this email as often as I do the Crunchy email. This problem occurs consistently for us. We're in a Centos 7 environment and using version 1.4.1 of our containers. Are you able to reproduce the issue?
thanks,Chris
    On Monday, October 9, 2017, 12:51:38 PM EDT, Sarah Conway <notifications@github.com> wrote:  
 
 
Hello Chris, have you been able to figure out this issue or is the problem still occurring?

**Comment by xenophenes** [comment]
Is this across all three platforms (Docker, Kubernetes, OpenShift)? I haven't been able to reproduce the issue, but can look into it more closely if I know which platform it's occurring on. Thanks for your response!

**Comment by the1forte** [comment]
OpenShift v3.5.5.24. It's an Origin OpenShift instance on RHEL 7.3 VM. If you can't reproduce that would be good news actually.

**Comment by xenophenes** [comment]
OK, I will take a look at that environment tomorrow morning and see if I can reproduce or find out more information on the issue.

**Comment by the1forte** [comment]
Hi Sarah. Any luck? Violet is running into the same problem, although for her it shows up with a slightly different path:

"Error loading script - /backup/backup"
Error message
undefined

**Comment by vnoorani** [comment]
Hi Sarah, this is Violet. It seems that we are getting different errors, every time we try it. I had the error Chris mentioned, but later on it was:
"Error loading script - /restore/restore"
Error message
undefined.

I am running on OpenShift v3.5.5.31.24 and kubernetes v1.5.2, RHEL 7.3 VM.  Thanks for your help!

**Comment by xenophenes** [comment]
My apologies for the late response! The latest container release happened last week and took up my time. I'm building an environment now to replicate yours to see if I can replicate the problem, will get back to you shortly.

**Comment by xenophenes** [comment]
(Still installing), but actually, doing some quick research it appears that this issue is not related to the crunchy-containers suite but rather to PgAdmin4 itself:

http://www.postgresql-archive.org/pgAdmin-4-v1-3-fails-to-load-td5951102.html
https://hub.docker.com/r/meedan/pgadmin/

You might try removing the PgAdmin4 image and rebuilding if this is possible:

`docker rmi -f crunchydata/crunchy-pgadmin4:$CCP_IMAGE_TAG`
`cd $CCPROOT`
`make pgadmin4`

and seeing what errors occur (if any) when you attempt to rebuild.

**Comment by jmccormick2001** [comment]
you might verify that this bug is fixed in the upcoming version you are working on.

**Comment by jasonodonnell** [comment]
@the1forte @vnoorani The new pgAdmin4 v2 images are live and I wanted to check if this resolved your issues.  The new images have changed a bit so please see the documentation ([pgadmin-http](https://github.com/CrunchyData/crunchy-containers/blob/master/docs/examples.adoc#pgadmin4-http) and [pgadmin-https](https://github.com/CrunchyData/crunchy-containers/blob/master/docs/examples.adoc#pgadmin4-https)).  Let me know :)

**Comment by jmccormick2001** [comment]
resolved with latest version.
