### ISSUE TITLE
PG_MODE errors...

### ISSUE THREAD

**Issue by jayunit100** [CrunchyData/crunchy-containers#265]
After running the `run.sh`, I see the following : 

This appears to be 

```
+ echo 'FATAL:  PG_MODE is not an accepted value...check your PG_MODE env var'
+ '[' -f /pgconf/postgresql.conf ']'
+ date
+ postgres -D /pgdata/replica-dc-3431046797-8vphp
Mon Oct  9 15:55:55 UTC 2017
+ [[ -v PGAUDIT_ANALYZE ]]
+ wait
postgres: could not access the server configuration file "/pgdata/replica-dc-3431046797-8vphp/postgresql.conf": No such file or directory

+ echo 'exiting...at end'
exiting...at end
```

I don't see any indication that any of the PG_MODE values are 'bad', though, just 'master', and 'replica'. 

Could just be that I overlooked some things.  I filed an associated PR to make this work on our vanilla GKE boxes, where we can't install binaries - but where we can run python :).

**Comment by jayunit100** [comment]
Note i see this with old and new images alike, maybe its a config issue on my end...

centos7-9.6-1.5.1 , centos7-9.5-1.2.7

**Comment by jmccormick2001** [comment]
yep, the latest version of the PG 9.5 versions is centos7-9.5-1.5.1, try that version out, but sounds like configuration at first glance.

**Comment by jayunit100** [comment]
PG_MODE seems to be set by you guys --- 

```
{
                        "name": "PG_MODE",
                        "value": "master"
                    }
```

**Comment by jmccormick2001** [comment]
it could be you are caught between our next release, where we changed the examples to reference 'replica' instead of 'slave'...so, you will want to pull examples from the last release tag instead of master...or to test this out, just replace the PG_MODE value of 'replica' to 'slave' and see if that fixes it.  In the next release we are moving to terminology that the PG community uses which is 'replica' instead of 'slave' or other variants.

**Comment by jmccormick2001** [comment]
FYI, we are working on the next release (1.6.0) this week, should have it ready by Friday.

**Comment by jmccormick2001** [comment]
all the built versions of images will look for 'slave' instead of 'replica' for PG_MODE...starting with 1.6.0 it will look for 'replica' instead.

**Comment by jmccormick2001** [comment]
new release will be out Monday evening...I think this one is closed now.
