### ISSUE TITLE
Use Centos image as the default.

### ISSUE THREAD

**Issue by jayunit100** [CrunchyData/crunchy-containers#266]
My GKE boxes don't seem to be able to pull the default Rhel images.  

Can we use centos7-9.6-1.4.1 or similar instead ?

**Comment by jmccormick2001** [comment]
the RHEL images are available via customer subscriptions...but yes, you can pull the centos versions from Dockerhub, the latest version is centos7-9.6-1.5.1.

**Comment by jayunit100** [comment]
Thanks Jeff, ok... I'd  like to update these to use centos or fedora as the default image - if that works for you - once we get the kinks in #265 worked out ..

**Comment by jmccormick2001** [comment]
the version of image used is dictated by the CCP_IMAGE_TAG environment variable, you set that to either use the RHEL or centos version.  So, set that to deploy the desired version.

**Comment by jayunit100** [comment]
Yup... was suggested that the private RHEL image is an odd choice for a default if this is meant to be an open source project which non RHEL users are contributing to....

... how do you feel about making fedora or centos crunchy-containers the default image?  Is there a specific need to default to rhel....?

**Comment by jmccormick2001** [comment]
I'm sorry, where are you seeing the default being set to RHEL images?

**Comment by jmccormick2001** [comment]
to elaborate, we build both centos and rhel images as part of each release, they are equivalent in functionality.    The centos images are pushed to Dockerhub as part of each release.   But, we also make a RHEL version of these releases available to customers that want a RHEL base image instead of a centos base image, hope that clarifies.

**Comment by jmccormick2001** [comment]
I think this one is resolved too, centos is our only distro on dockerhub, I updated envvars.sh to have the centos version of the image as the default image, I think that might have caused this issue.
