### ISSUE TITLE
Multiple NAMESPACE environment variable exports in examples/envvars.sh

### ISSUE THREAD

**Issue by vcottagiri** [CrunchyData/crunchy-containers#272]
Comment the redundant entries in [examples/envvars.sh](https://github.com/CrunchyData/crunchy-containers/blob/master/examples/envvars.sh) to avoid confusion.

```
export NAMESPACE=myproject
export NAMESPACE=storage-project
export NAMESPACE=default
```

**Comment by jmccormick2001** [comment]
thanks for catching that, just merged a fix into master for this.

**Comment by vcottagiri** [comment]
Thanks for the quick turnaround!
