### ISSUE TITLE
implement pgadmin4-v2 on pg10

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#283]
I found various issues attempting to get this version to run...

I first had to add these lines to pgAdmin.py at the top to get it to run...

reload(sys)
sys.setdefaultencoding("utf-8")

I then had to hack the pre configured pgadmin.db to set the password....

so bottom line, there needs to be some investigation here to get this to work properly...

**Comment by jmccormick2001** [comment]
as part of this exercise, we would also want to make the containers run as USER 26 on both kube and OCP...today this is out of sync due to the way pgadmin4 works and the security settings within OCP.

**Comment by jasonodonnell** [comment]
@jmccormick2001 Ready for closing?

**Comment by jmccormick2001** [comment]
merged
