### ISSUE TITLE
Sync replica on docker swarm

### ISSUE THREAD

**Issue by kostrzewa9ld** [CrunchyData/crunchy-containers#289]
This is a feature request to enable synchronous streaming replication on docker swarm.

I've used your containers to setup sync replication on docker swarm by following your example for [docker](https://github.com/CrunchyData/crunchy-containers/blob/master/examples/docker/sync/run.sh). One issue that popped out was that transactions hanged on commit to replica. After a short investigation I found out that the problem was with replica having itself configured as standby, probably because it mirrored the configuration from master.

I am not sure how is that your example with docker works and please correct me if I'm wrong, but I suspect that it works because replica hostname matches the hostname configured as standby and probably PostgreSQL simply skips the standby if it notices it matches the current host.
Unfortunately, this doesn't work in case of swarm as hostname is the name of the container but standby name is the name of the docker service.

Since I needed a quick workaround I fixed this by removing `synchronous_standby_names` from replica in `start.sh`:
```
	if [ "$PG_MODE" == "slave" ]; then
		sed -i 's|synchronous_standby_names =.*||' $PGDATA/postgresql.conf
	fi
```
but I bet there is a nicer and more correct way to achieve that within your scripts.

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/crunchy-containers/issues/345

**Comment by jasonodonnell** [comment]
@kostrzewa9ld This was updated/fixed in #539 - appreciate you reporting this to us!

@jmccormick2001

**Comment by kostrzewa9ld** [comment]
@jasonodonnell 

Please correct me if I am wrong but I believe the example you have referenced, and the blog post by @jmccormick2001 setup async replication:
```
bash-4.2$ psql -U postgres -c 'select sync_state from pg_stat_replication' postgres
 sync_state 
------------
 async
(1 row)
```
and this ticket is about **synchronous** replication.

**Comment by jasonodonnell** [comment]
@kostrzewa9ld Not seeing it on my end, here's what I'm doing:

Using the new example, I added one new environment variable to both services in the `docker-compose.yml`

```
[~]$ diff async-docker-compose.yml sync-docker-compose.yml
19a20
>     - SYNC_REPLICA=*
45a47
>     - SYNC_REPLICA=*
```

### List replication on Primary

```
postgres=# table pg_stat_replication;
-[ RECORD 1 ]----+------------------------------
pid              | 109
usesysid         | 16396
usename          | primaryuser
application_name | *
client_addr      | 10.0.0.10
client_hostname  |
client_port      | 35288
backend_start    | 2018-03-27 10:08:15.774862-04
backend_xmin     |
state            | streaming
sent_lsn         | 0/5000060
write_lsn        | 0/5000060
flush_lsn        | 0/5000060
replay_lsn       | 0/5000060
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 1
sync_state       | potential
-[ RECORD 2 ]----+------------------------------
pid              | 83
usesysid         | 16396
usename          | primaryuser
application_name | *
client_addr      | 10.0.0.9
client_hostname  |
client_port      | 53958
backend_start    | 2018-03-27 10:04:34.055994-04
backend_xmin     |
state            | streaming
sent_lsn         | 0/5000060
write_lsn        | 0/5000060
flush_lsn        | 0/5000060
replay_lsn       | 0/5000060
write_lag        |
flush_lag        |
replay_lag       |
sync_priority    | 1
sync_state       | sync
```

### Run Queries on Primary

```
postgres=# CREATE TABLE test2(id INT);
CREATE TABLE
postgres=# INSERT INTO test2(id) VALUES(0);
INSERT 0 1
postgres=# INSERT INTO test2(id) VALUES(0);
INSERT 0 1
postgres=# INSERT INTO test2(id) VALUES(0);
INSERT 0 1
```

### Check Replicas

```
postgres=# CREATE TABLE test3(id INT);
ERROR:  cannot execute CREATE TABLE in a read-only transaction

postgres=# \dt
            List of relations
 Schema |     Name     | Type  |  Owner
--------+--------------+-------+----------
 public | primarytable | table | postgres
 public | test         | table | postgres
 public | test2        | table | postgres
(3 rows)

postgres=# SELECT * FROM public.test2;
 id
----
  0
  0
  0
(3 rows)
```
