### ISSUE TITLE
support GCE-Kube deployment

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#29]
create examples and instructions on how to run the container in a GCE-Kube environment with persistent storage

**Comment by balakrishnangithub** [comment]
+1

**Comment by rimusz** [comment]
to be more correct, we need a Helm chart for the whole pack to work on any Kubernetes as GKE, GCE, AWS setup:

```
crunchy-postgres - executes Postgres

crunchy-backup - performs a full database backup

crunchy-pgpool - executes pgpool

crunchy-pgbadger - executes pgbadger

crunchy-watch - performs a form of automated failover

crunchy-collect - collects Postgres metrics

crunchy-prometheus -stores Postgres metrics

crunchy-grafana - graphs Postgres metrics

crunchy-dns - standalone DNS server useful for standalone execution

crunchy-pgbouncer - pgbouncer connection pooler and simple form of failover

crunchy-pgadmin4 - pgadmin4 web application
```

**Comment by jmccormick2001** [comment]
thanks for the input!

**Comment by shaneog** [comment]
Is this available anywhere yet? I've just discovered this project and would love to run it on Kubernetes on GKE.

**Comment by jmccormick2001** [comment]
I've not yet verified that everything works on a GCE deployment, still something I want to do however...but I have heard of others getting most of it to work so i'm optimistic about it...I hope to get to this soon.

**Comment by Tedezed** [comment]
I have examples wich gcePersistentDisk and set of pgpool, statefulset postgres and watch on GCE cluster kubernetes. If you want, I can share it.

I'm also interested in self-scaling the statefulset cluster postgres, source: https://github.com/kubernetes/kubernetes/issues/44033

**Comment by jmccormick2001** [comment]
if you have examples you could share I'd love to pull those in to start a
new GCE folder of examples similar to the ones I have for
openshift/kube/docker.

On Thu, Apr 6, 2017 at 4:16 AM, Juan Manuel Torres <notifications@github.com

**Comment by Tedezed** [comment]
When to solve the errors, I share them.
Thanks! :)

**Comment by Tedezed** [comment]
Add gce pv example: https://github.com/CrunchyData/crunchy-containers/pull/107/commits/36c6d97fab98b0f0cf64299c8cfa3e01067d1a47

**Comment by jmccormick2001** [comment]
I've tested using GCE and updated the kube.asciidoc to note a few pointers on running on GCE...I'll create another Issue for the Helm charts work.
