### ISSUE TITLE
PG_PRIMARY_USER not changed in all files - breaking pods

### ISSUE THREAD

**Issue by dhwanilraval** [CrunchyData/crunchy-containers#298]
Looks like recent changes done on container images and openshift templates, but start.sh files in bin still refer to old PG_MASTER_USER, which is breaking starting up containers.

**Comment by xenophenes** [comment]
Please make sure you're on the latest version of the container suite; the only references to PG_MASTER_USER at this point should not break anything, but simply issue a warning:

```
if [ -v PG_MASTER_USER ]; then
	echo "WARNING:  PG_MASTER_USER is deprecated and will be removed in a future release, replace with PG_PRIMARY_USER"
	export PG_PRIMARY_USER=$PG_MASTER_USER
fi
```
All this will do is let the user know (if they are still using earlier versions of the containers) that PG_MASTER_USER is deprecated; it then exports PG_PRIMARY_USER as PG_MASTER_USER. There should be nothing breaking as a result of this.

**Comment by dhwanilraval** [comment]
Thanks xenophenes. I am on latest version of container suite; and latest image of 9.6. centos7-9.6.5-1.6.0.

I am on openshift Container Platform 3.5

Attached are steps followed and logs. Although I have tried workshop example, error is same across all templates.

[deploy.log](https://github.com/CrunchyData/crunchy-containers/files/1422192/deploy.log)
[primary.log](https://github.com/CrunchyData/crunchy-containers/files/1422193/primary.log)

pg container in pod aborting with below error:
PG_PRIMARY_PORT or PG_MASTER_PORT environment variable is not set, aborting

**Comment by xenophenes** [comment]
Ah! My apologies, I didn't realize you were talking about the PG_PRIMARY_PORT variable as being missing. That is definitely a bug; I will send a pull request shortly with the fixes for the OpenShift template examples. Thank you for reporting this.

**Comment by xenophenes** [comment]
After the PR is merged, please let us know if there's any remaining issues concerning this.

**Comment by jmccormick2001** [comment]
fixes for this example merged into master.
