### ISSUE TITLE
execute cannot be used while an asynchronous query is underway

### ISSUE THREAD

**Issue by balakrishnangithub** [CrunchyData/crunchy-containers#31]
I have created a transaction which has 1000 inserts and executed it via pgpool but before the transaction completed I force terminated the client.
Now, I can able to SELECT that table via pgpool as well as directly via master. But on replica when I execute SELECT query I get the following error.

```
execute cannot be used while an asynchronous query is underway********** Error **********
```

I installed my cluster using [kubehelm](https://github.com/CrunchyData/crunchy-containers/tree/master/examples/kubehelm/crunchy-postgres)(1 crunchy-master, 3 crunchy-replicas) and [pgpool](https://github.com/CrunchyData/crunchy-containers/tree/master/examples/kube/pgpool) seprately. I don't even added persistent volumes. Its been a while now but I'm still getting the same error.

logs:

```
$ kubectl logs pgpool
...
2016-10-28 10:49:43: pid 29: LOG:  statement: BEGIN
2016-10-28 10:49:43: pid 29: LOG:  statement: 
2016-10-28 10:49:43: pid 29: LOG:  statement: INSERT INTO "public"."test" ("text") VALUES (E'0')
...
2016-10-28 10:51:15: pid 29: LOG:  statement: 
2016-10-28 10:51:15: pid 29: LOG:  statement: INSERT INTO "public"."test" ("text") VALUES (E'502')
2016-10-28 10:51:15: pid 29: ERROR:  unable to read data from frontend
2016-10-28 10:51:15: pid 29: DETAIL:  socket read failed with an error "Connection reset by peer"
2016-10-28 10:51:30: pid 30: LOG:  new connection received
2016-10-28 10:51:30: pid 30: DETAIL:  connecting host=gke-cluster-1-default-pool-14ed9ed5-r6c7.c.container-1372.internal port=53435
...
```

Then I also truncated that table and inserted 1000 records in single INSERT via using pgpool. It successfully completed and I can able to SELECT the inserted records via pgpool and master. But still having error on replica.

```
$ kubectl logs pgpool
...
2016-10-28 10:56:41: pid 30: LOG:  statement: INSERT INTO "public"."test" ("text") VALUES (E'0'),(E'1'),(E'2'),(E'3')
...
(E'9996'),(E'9997'),(E'9998'),(E'9999')
2016-10-28 10:57:27: pid 30: LOG:  statement: 
```

**Comment by jmccormick2001** [comment]
thanks for entering this issue, I'll see if I can recreate it, could be a problem in pgpool but I'm unsure at this point.

**Comment by balakrishnangithub** [comment]
@jmccormick2001 thanks for your reply one side note is that I accessed pgpool using HeidiSQL, which behaves different from pgadmin. pgadmin sends the whole query but HeidiSQL sends one by one i.e. semicolon seprated as one query so it gives more than enough time to interrupt the process.

**Comment by balakrishnangithub** [comment]
@jmccormick2001  before I ran the transaction I manually deleted the 3 replica pods just to check weather the replication controller recreates it(actually playing cockpit-kubernetes topology ui). As expected pods gets recreated and also data in master and replica are equal so no problem at this point.

**Comment by jmccormick2001** [comment]
thanks, I'll close this one out.  cheers.

**Comment by balakrishnangithub** [comment]
@jmccormick2001 sorry, I'm actually trying to say that replication is not the suspect but what happen next to replication is, which is  _insert transaction_ that I mentioned. I don't know what caused this issue and also I can't able to find a solution so I just reinstalled the crunchy postgresql.
