### ISSUE TITLE
remove dependency

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#310]
I think we can replace envsubst and the related gettext dependnecy with this bash script:

https://github.com/CrunchyData/crunchy-containers/blob/master/bin/expenv.sh

test this theory out by creating a clean kube/openshift VM, do NOT install the gettext (envsubst) dependency, replace occurances of envsubst in the various run.sh scripts with $COROOT/bin/expenv.sh and see if the examples work as before.

**Comment by xenophenes** [comment]
I believe there's an error with the expenv.sh script - keep getting an error:

`error: json: line 1: invalid character 'a' looking for beginning of object key string`

I'll try to figure out what's going on - prioritizing the other issues in the meantime (focusing primarily on install.adoc & examples.adoc).

**Comment by jmccormick2001** [comment]
I updated the script to be simpler...the usage is now something like this 'cat my.json | $CCPROOT/bin/expenv.sh | kubectl create -f -'

**Comment by xenophenes** [comment]
How would the usage work for this context?

`envsubst < /opt/cpm/conf/passwd.template > /tmp/passwd`

Like this?

`/opt/cpm/conf/passwd.template | $CCPROOT/bin/expenv.sh | > /tmp/passwd`

**Comment by xenophenes** [comment]
This issue can be closed.
