### ISSUE TITLE
documentation - install doc - update

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#312]
in the install guide it lists this command as part of the installation:

sudo yum -y install golang git docker postgresql-server

this is not what we want for Openshift installations...for example, Openshift 3.6 is our current standard, in that installation they require docker 1.12-6 to be installed per their docs.   Therefore, we want to instead point the user to the Openshift installation documentation on how to install the correct version of Docker.  This version probably applies to Kube as well since we only support a Centos installation.

Also, we will want to point the user to installing Postgres from the PGDG repo instead of using
the version that Redhat/Centos provides (e.g. 9.2).  So, the docs would tell the user how to
add the PDGD repo and install Postgres from that repo, specifically version PG 10 since that
is the latest version we support.

For golang, in the case of a RHEL box that is set up to run Openshift, you have to add 
this repo to install the Redhat packaged golang:

[root@jeffocp ~]# subscription-manager repos --enable=rhel-7-server-optional-rpms

**Comment by xenophenes** [comment]
> Therefore, we want to instead point the user to the Openshift installation documentation on how to install the correct version of Docker. This version probably applies to Kube as well since we only support a Centos installation.

Is it necessary to do this? "yum install docker" installs the correct version of Docker (1.12-6) already. It shouldn't be necessary to do more than add a "*Note*:" mentioning to be sure of the version, and if it's not the correct version, visit x link. 

Making the other changes!

**Comment by xenophenes** [comment]
This issue can be closed.
