### ISSUE TITLE
documentation - step 5 of installation 

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#313]
this example needs to either specify a 'hostpath' or 'nfs' parameter...the install guide should probably make a decision as to which storage type it will install, so for example, it should tell the user, "we are going to assume you want to configure your system to use NFS..."

and then the create.pv line would be

create.pv nfs

instead of....

Step 5 - Persistent Volume Claims

For running the examples that require persistent volumes, you will need to run the following script:

cd $CCPROOT/examples/pv
./create-pv.sh

also, related, the NFS instructions seem to be taken from the post documentation, we need to either remove the link to the blog post or remove the duplicated lines in the install guide...

**Comment by xenophenes** [comment]
After merge of PR #319 this should be good to close, unless you want further changes.
