### ISSUE TITLE
documentation - install guide - selinux on kube notes

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#314]
these appear out of date:

sudo PATH=$PATH ALLOW_PRIVILEGED=true ./hack/local-up-cluster.sh
Note: specifying ALLOW_PRIVILEGED=true is required if you are running in SELinux enforcing mode. This allows you to specify the following in your pod spec to run the container as privileged:

"securityContext": {
	"privileged": true
},

lets assume and state that our install guide is based on a kubeadm install of kubernetes, then look for revised guidance on how to enable selinux in a kubeadm installation.

**Comment by xenophenes** [comment]
In my testing, I haven't found the use of this section to be necessary at all. I'll revise the install guide to assume kubeadm and remove that section you mentioned entirely, if that's OK.

**Comment by xenophenes** [comment]
This issue can be closed.
