### ISSUE TITLE
documentation - examples - cleanup

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#315]
see if you can refactor or reduce the amount of duplication in the various examples...for example, the 'run a single database' appears to repeat many of the same bullets for Helm, Kube, and Openshift such as what is getting created (service, pod)...Docker is the odd-ball here in that it doesn't map to what is created per se by the others (kube, openshift)...

**Comment by xenophenes** [comment]
After merge of PR #319 this should be good to close, unless you want further changes.
