### ISSUE TITLE
postgres log aggregation example

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#316]
for openshift and kube environments, document and test the best way to perform postgres log aggregation.

**Comment by jmccormick2001** [comment]
https://www.youtube.com/watch?v=wSarix-DRyg

**Comment by jmccormick2001** [comment]
logging_collector = off

now, when you do that, you can use the Openshift container log aggregation documented
here:

https://docs.openshift.com/container-platform/3.6/install_config/aggregate_logging.html

**Comment by jmccormick2001** [comment]
what I'm looking for here is documentation and potentially a blog on setting up log aggregation, no code should be required on this, looking for best solution on both kube and OCP 3.10.

**Comment by altondinsmore** [comment]
Got it

**Comment by jmccormick2001** [comment]
no worries Alton, I was assigning this to Jason.

**Comment by altondinsmore** [comment]
Oh that works... Sorry should have looked at it before hitting reply...
