### ISSUE TITLE
PG_MASTER_USER deprecation bug

### ISSUE THREAD

**Issue by the1forte** [CrunchyData/crunchy-containers#318]
The PG_MASTER_USER environment setting does not work, forcing a switch to the PG_PRIMARY_USER setting. Currently only a deprecation warning is issued, implying that PG_MASTER_USER can still be used. 

This is not a problem for the other deprecated settings.

**Comment by xenophenes** [comment]
Can you explain exactly how it's not working? It's configured similarly to the other deprecated settings, where it exports the new variable to what the old one was set to:

`if [ -v PG_MASTER_HOST ]; then`
	`echo "WARNING:  PG_MASTER_HOST is deprecated and will be removed in a future release, replace with PG_PRIMARY_HOST"`
	`export PG_PRIMARY_HOST=$PG_MASTER_HOST`
`fi`

**Comment by the1forte** [comment]
I did some digging and saw that this was actually caused by the fact we were using an outdated setup.sql file as part of a configmap. Our setup.sql was still using PG_MASTER_USER, so we've updated it to PG_PRIMARY_USER. Thanks, this issue can be closed.
