### ISSUE TITLE
trap the SIGTERM and pass SIGINT to the postmaster

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#33]
for cleaner postgres shutdown, trap the SIGTERM and pass
SIGINT to the postmaster, handle docker stop/kill cases and docker daemon shutdown case

**Comment by jconway** [comment]
Looks correct to me.

**Comment by jmccormick2001** [comment]
combined the start-pg-wrapper.sh and start.sh scripts into a single start.sh script to be consistent other containers in the suite, added a change to start.sh script to exec postgres, this allows SIGTERM (docker stop) to reach postgres whereby a clean postgres shutdown can be achieved.

**Comment by jconway** [comment]
Converting SIGTERM to SIGINT is important. See:

  https://www.postgresql.org/docs/9.5/static/server-shutdown.html

If you send SIGTERM, postgres will wait on any existing connections, which means it could wait a very long time. If that happens docker stop times out and postgres gets killed as before.

With SIGINT, a "fast shutdown" is done. This produces a clean shutdown while not waiting on existing connections. SIGINT is what we need here.

**Comment by jmccormick2001** [comment]
ah!

**Comment by jmccormick2001** [comment]
it appears to be working now..I put an explicit trap in the script to catch both INT and TERM
signals, when caught, it will send SIGINT to the postgres to stop it....

the pg log shows the following message to indicate the shutdown...

2016-11-02 11:52:33 EDT [27]: [4-1] user=,db=,app=,client=LOG:  received fast shutdown request

**Comment by jconway** [comment]
Perfect -- thanks!
