### ISSUE TITLE
Does pgpool support more than 2 replica servers?

### ISSUE THREAD

**Issue by xqianwang** [CrunchyData/crunchy-containers#335]
As I can see from source code, it looks like crunchydata-pgpool only support 1 primary and 1 replica. Besides, if we have 2 users with 2 schemas in single database,  our application cannot see tables inside schema.

**Comment by jmccormick2001** [comment]
the pgpool configuration we use assumes if you have more than 1 replica, say 2, that both of those replicas will be fronted by a single replica service, the replica service is what is specified in the pgpool configuration as 'replica'.  The service round robin load balances for you to multiple replicas.

The example pgpool configuration assumes a 'testuser' can connect to a 'userdb'.  If you want to confiigure pgpool for multiple or different users, you can do that by providing a custom pgpool configuration file which is also supported.

regards.

**Comment by xqianwang** [comment]
hey @jmccormick2001, thanks a lot for reply. That is what I am thinking for replica servers. I think we did something wrong for replica server as we are creating different replica services for replica servers.
