### ISSUE TITLE
documentation : consider a storage document

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#344]
given the number of storage options and configurations, a storage document or a section in the existing documentation would merge existing ceph/cluster docs plus other storage documentation.

**Comment by xenophenes** [comment]
Should I add this to my to-do list as part of the docs rehaul?

**Comment by jmccormick2001** [comment]
I think for now, the 'Configure Storage' section of the install.adoc will suffice, I'm adding all the storage config changes there for now...will revisit a separate doc later on.
