### ISSUE TITLE
Crunchy-Watch might lead to multiple primary pods (OpenShift / Kubernetes)

### ISSUE THREAD

**Issue by beevelop** [CrunchyData/crunchy-containers#347]
Using your OpenShift-Failover example, I experienced two cases where the failover via Crunchy-Watch did not work as intended. Consider the following scenario:

0. Primary, 2 Replicas, Crunchy-Watch & PGPool are running properly
1. Connectivity issue causes unreachable service (in this case `primary-dc`; e.g. due to shitty internal network)
2. Crunchy-Watch triggers failover routine
3. The original primary is still available and the former replica gets promoted to be the new master now.
4. Now we do have 2 Primaries within the same service
5. You chance is 50/50 to hit the right database with your queries. 🎲 

Additionally we experienced Crunchy-Watch spawning unlimited Primaries, when the checked service won't get up. It keeps promoting replicas to primaries and spawning new ones until the namespace / cluster is out of resources.

Is there a way to make sure, there is no more than 1 pod associated with `primary-dc`service?

**Comment by abrightwell** [comment]
This is functionality we are currently working on and hoping to incorporate into future versions. Unfortunately, those updates are not ready/available at this time.

However, in the meantime, you could possibly handle these cases through the use of a 'pre' failover hook.

**Comment by beevelop** [comment]
Thank you for the fast response. You don't have a development branch with those changes by any chance? If I got your examples right, I should be able to use the `WATCH_PRE_HOOK` or `WATCH_POST_HOOK` environment variables. From there I could trigger the respective cleanup procedures / prevent the failover in the first place?

**Comment by jmccormick2001** [comment]
you should be able to try out the PRE/POST hooks with the current released version

**Comment by jmccormick2001** [comment]
I've added code to the upcoming release which performs a 'kubectl delete pod <<old primary>>' as part of a failover, this will be the default action of a failover going forward...the same will apply to openshift as well when completed.

**Comment by jmccormick2001** [comment]
merged into 1.8.0

**Comment by beevelop** [comment]
Awesome. Thank you 👍

**Comment by jmccormick2001** [comment]
we are pushing 1.8.0 out here in a few hours as well, forgot to mention that.  cheers.
