### ISSUE TITLE
how to set a username for db connection

### ISSUE THREAD

**Issue by dimthe** [CrunchyData/crunchy-containers#348]
hello 
how do i set a custom username for the db connection ? In values.yaml i see primary and user .
which one would i need to change.. ?

**Comment by jmccormick2001** [comment]
the user names are set in the Chart.yaml...there is a default set of usernames created by the postgres container (postgres, primaryuser, testuser).  If you wanted to change the testuser user name, you would have to use a custom setup.sql file and specify it using an override mechanism as shown here:  crunchy-containers/examples/openshift/custom-config

there is currently not a Helm chart example of using a custom config so you'll have to construct one yourself using that example.

**Comment by jmccormick2001** [comment]
https://github.com/CrunchyData/crunchy-containers/tree/master/examples/helm/custom-config

check out that new example we added, I think it might be what you were looking for.
