### ISSUE TITLE
Watch postgres container got permission denied while trying to connect to the docker daemon

### ISSUE THREAD

**Issue by LuisGAngel** [CrunchyData/crunchy-containers#351]
**Scenario**
I have three nodes in a docker swarm: dic15-test-1, dic15-test-2, dic15-test-3.
The nodes have this labels:
- dic15-test-1: {admin=true, type=pimary}
- dic15-test-2: {type=replica}
- dic15-test-3: {type=replica}

<img width="1092" alt="screen shot 2017-12-18 at 1 21 53 am" src="https://user-images.githubusercontent.com/7827171/34094236-f6ef3a6c-e391-11e7-937b-9ff06184b8c5.png">

I'm using a primary container, a replica container, a pgpool container and a watch container.
Everything is working amazingly so far but the automatic failover.

When all the services are running and I stop the primary container, the watch container fails to do the automatic failover.

**Steps to trigger the problem:**
--in a docker swarm with three nodes--
deploy the containers: `docker stack deploy -c stack.yml set` 
stack file -> https://paste.ofcode.org/NWxh5RYwXUJpuNG5ug7EX9

remove the primary container
`docker service rm set_unified-primary-db`

**Expected to happen**
The watch container complete the automatic failover successfully

**What happens instead**
The watch container fails the automatic failover. It seems to be a permission issue with the docker socket. (see below the service logs)

Last logs in the set_unified-watch-db service:
_set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + echo 'Standalone failover...'
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + standalone_failover
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + echo 'Standalone failover is called!'
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + export DOCKER_API_VERSION=1.20
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + DOCKER_API_VERSION=1.20
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + echo 'creating the trigger file on ' unified-replica-db
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + docker exec unified-replica-db touch /tmp/pg-failover-trigger
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | exiting after the failover has been triggered...
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.20/containers/unified-replica-db/exec: dial unix /var/run/docker.sock: connect: permission denied
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + echo 'exiting after the failover has been triggered...'
set_unified-watch-db.1.nkokgptovve7@dic15-test-1    | + exit 0_

**docker info**
Client:
 Version:      17.09.1-ce
 API version:  1.32

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)

**Extra information**
I suspect the denied problem is because a service can't be run in a privileged mode. Check this issue for more information: https://github.com/moby/moby/issues/24862

**Comment by jmccormick2001** [comment]
//var/run/docker.sock   you might check the file permissions of that docker socket, your container will need read/write access to that socket, its how it sends commands to the docker daemon.

**Comment by LuisGAngel** [comment]
Thanks for the response @jmccormick2001. 
The default permissions are `srw-rw---- 1 root docker 0 Dec 18 17:43 docker.sock=`
After changing to `srw-rw-rw- 1 root docker 0 Dec 18 17:43 docker.sock=` in every node (a bit pain in the ass because you don't know where the container will be placed) the container got access to the docker socket, although changing the permissions seems an antipattern.

**Comment by LuisGAngel** [comment]
Now that the watch container is getting access to the docker socket I'm getting this error. `Error: No such container: unified-replica-db`. 

The reason for this is that the failover is assuming a 1 host deployment. According to this [https://github.com/CrunchyData/crunchy-containers/blob/master/bin/watch/start.sh](url) the action for the failover(line 109) is `docker exec $PG_REPLICA_SERVICE touch /tmp/pg-failover-trigger`.

Is there any plan to support a multi-host environment? It seems that the purpose of HA Postgres architecture is broken by this 1-host failover.

**Comment by jmccormick2001** [comment]
I'll make a note of that, we use metadata labels in Kube to offer up a means of knowing who all the replicas are in a Kube environment, we would need something similar to that lookup mechanism for the Docker/Swarm mode I think to make it work is a similar manner.  We are currently working on a new version of crunchy-watch where we can do more sophisticated fail-overs so this is a use case we can look at more.

**Comment by LuisGAngel** [comment]
Thanks for the response @jmccormick2001. Is there any tentative date for this functionality?

Let me know if I can help in any way(dev, testing, etc)

**Comment by martinspaeth** [comment]
Thank you for publishing your work here! 

I am facing the same
Problem (multi host Environment). So I want to add my two cents...

The docker swarm listener (key component for docker flow)
https://github.com/vfarcic/docker-flow-swarm-listener might be a good inspiration when implementing swarm capabilities including label system via env cars!

Any estimate for a full docker swarm support already?

**Comment by jmccormick2001** [comment]
thanks for the input, I'm considering revising our Docker Swarm support/examples given the interest.

**Comment by martinspaeth** [comment]
Hi just a little bump about this topic any news so far?
best regards

**Comment by davecramer** [comment]
@martinspaeth thx for the bump. I'll have to spend some time looking at this

**Comment by jmccormick2001** [comment]
watch features now live in the crunchy-watch repo, if this feature is still interesting to folks, please enter it there and we'll prioritize.
