### ISSUE TITLE
Exposure of sensitive information due to talkative scripts

### ISSUE THREAD

**Issue by beevelop** [CrunchyData/crunchy-containers#353]
Some scripts do currently use (`#!/bin/bash -x` or `set -x`) to print out the executed commands. In case of the Postgres initialization itself (see https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/start.sh#L1), this leads to exposure of sensitive information in the application's logfiles (all necessary passwords and user configs). This is critical when using central logging tools like ELK, as different parties might be able to access them.

I propose to make the „talkative“ settings configurable with e.g. a `DEBUG` env.

**Comment by jmccormick2001** [comment]
thanks!  this will be implemented.

**Comment by jasonodonnell** [comment]
Good to close @jmccormick2001 ?

**Comment by beevelop** [comment]
@jasonodonnell Awesome, thank you!
