### ISSUE TITLE
Crunchy-Watch: Wrong failure count logic

### ISSUE THREAD

**Issue by beevelop** [CrunchyData/crunchy-containers#357]
Using Crunchy-Watch on OpenShift we experienced inconsistent behaviour for the failover procedures. Combing through the logs revealed that the failure count does not seem to be reset on a successful check.

This might lead to unnecessary failovers even though the `MAX_FAILURES` have technically not been reached. The current Crunchy-Watch implementation does reflect this behaviour at Line 232: https://github.com/CrunchyData/crunchy-containers/blob/master/bin/watch/start.sh#L232

The count of failures should also be reset on a successful check, shouldn't it?

**Comment by jmccormick2001** [comment]
you are correct, I'll add this to the list of corrections and updates we are making to crunchy-watch, a new version should be out very soon.  thanks for reporting this!

**Comment by jmccormick2001** [comment]
verified this is fixed in the upcoming new release.  Once released I'll close this Issue.  I expect the new release to be out in the next 10 days.

**Comment by beevelop** [comment]
@jmccormick2001 Is the fix included in the recently released 1.7.1 of crunchy-watch?

**Comment by jmccormick2001** [comment]
should be fixed with this release yes.  With this release you will see that some of the parameter names have changed, if you use previous version examples, they should still work but you'll see some warning messages in the logs about deprecated env vars.
