### ISSUE TITLE
Master/Slave labels still exist

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#361]
In some examples we are still using `master/slave` notation:

[ms-primary](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=ms-primary&type=)
[ms-replica](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=ms-replica&type=)
[ms-replica-2](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=ms-replica-2&type=)
[m-s-rc-pvc-primary](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=m-s-rc-pvc-primary&type=)
[m-s-rc-pvc-replica](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=m-s-rc-pvc-replica&type=)
[m-s-rc-pvc](https://github.com/CrunchyData/crunchy-containers/search?utf8=%E2%9C%93&q=m-s-rc-pvc&type=)

**Comment by jmccormick2001** [comment]
merged
