### ISSUE TITLE
Unable to pull from Docker v1 Registry

### ISSUE THREAD

**Issue by orondon** [CrunchyData/crunchy-containers#371]
Hi CrunchyData team

Recently upgraded to:

docker version
Client:
 Version:      17.05.0-ce
 API version:  1.29
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.05.0-ce
 API version:  1.29 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   89658be
 Built:        Thu May  4 22:06:25 2017
 OS/Arch:      linux/amd64
 Experimental: false

When trying to pull postgres image, I'm getting
 
docker pull crunchydata/crunchy-postgres
Using default tag: latest
Error response from daemon: manifest for crunchydata/crunchy-postgres:latest not found

An option is to use the flag disable-legacy-registry, but from https://docs.docker.com/edge/engine/reference/commandline/dockerd/#description
"The disable-legacy-registry configuration option has been removed and, when used, will produce an error on daemon startup."

Are you planning to update to a higher version docker registry?
Could you suggest any workaround?

Thanks!
Ornella

**Comment by jmccormick2001** [comment]
Hi, we don't create a 'latest' tag any longer, instead pull a specific version then you can tag it locally if you want to refer to a 'latest' tag in your project.  Hope that helps.  cheers.
