### ISSUE TITLE
add extra values ike max_connection and shared buffers

### ISSUE THREAD

**Issue by dimthe** [CrunchyData/crunchy-containers#379]
hello
how can i increase max_connection , shared_buffers and kernem.shmmax ? where and how would i define those values ? thanks

**Comment by jmccormick2001** [comment]
for some reason these env vars were not documented!  they are now...
https://github.com/CrunchyData/crunchy-containers/blob/master/docs/containers.adoc

TEMP_BUFFERS - default is 8MB, set this value to override this PostgreSQL configuration setting
MAX_CONNECTIONS - default is 100, set this value to override this PostgreSQL configuration setting
SHARED_BUFFERS - default is 128MB, set this value to override this PostgreSQL configuration setting
WORK_MEM - default is 4MB, set this value to override this PostgreSQL configuration setting
MAX_WAL_SENDERS - default is 6, set this value to override this PostgreSQL configuration setting

not sure about kernem.shmmax, that sounds like a kernel setting? or perhaps set via a docker configuration?

**Comment by dimthe** [comment]
thanks it worked
