### ISSUE TITLE
helm-statefulset example - replicas created with name pg-primary-X 

### ISSUE THREAD

**Issue by tomerweisman** [CrunchyData/crunchy-containers#388]
Hi
When I run your example in k8s cluster using helm all the replicas are created with name pg-primary-X
so the pg-replica service cannot find them as endpoints. 
what is the desired name the replicas should be created with ?
is it a problem with your templates \ values? 
thank you 
![capture](https://user-images.githubusercontent.com/17765396/35035054-c7e36744-fb78-11e7-95bb-7379ee4d93f2.JPG)

**Comment by xenophenes** [comment]
Hello!

My apologies for the long wait in a response. I'll be taking a look at this within the next few days and will get back to you once the issue is fixed so you can try this again.

Thank you for your patience!

**Comment by xenophenes** [comment]
@tomerweisman The latest PR should fix the issue. Please let me know if you continue seeing any problems. Thanks again!
