### ISSUE TITLE
support pgaudit 

### ISSUE THREAD

**Issue by prlaurence** [CrunchyData/crunchy-containers#39]
add support for pgaudit extension [https://github.com/pgaudit/pgaudit](url)

**Comment by jmccormick2001** [comment]
also add the ability to offloading the logs through syslog

**Comment by jmccormick2001** [comment]
merged into master, will land in the 1.2.6 release, this change adds pgaudit to the crunchy-postgres container, enables it by default in setup.sql and within the default postgresql.conf file.
