### ISSUE TITLE
Feature Request: Point in Time Recovery (PITR)

### ISSUE THREAD

**Issue by bdurrow** [CrunchyData/crunchy-containers#4]
I am interested in brining up production postgres databases in OpenShift (Origin). Part of our requirements include Point In Time Recovery (PITR) but I don't see any this feature in crunchy-postgresql.  Is it on the roadmap?  I have done some work with pghoard (https://github.com/ohmu/pghoard) to have it work in a docker and plan to do more work to allow it to serve archived WALs for recovery out of a docker (with object store backing).  Does this fit architecturally with crunchy-postgresql?  Do you have other ideas to provide PITR?

**Comment by jmccormick2001** [comment]
thanks for your interest!  yes indeed, supporting some form of incremental backup or PITR is on the roadmap...currently the crunchy-backup container performs only a full basebackup and persists to some form of persistent storage....I do like what I see in pghoard and it might be indeed possible to use that as a PITR implementation.  I was also going to look at pgbackrest as well.  Tentatively, I'm looking at the next 2 months or so to have this sort of feature integrated into the container set.

**Comment by jmccormick2001** [comment]
I've written the initial PITR support, see pitr.asciidoc for details on how this works.  This feature will land in the 1.2.3 release which is to be dropped soon.
