### ISSUE TITLE
Expose via Service Broker to enable managing databases via the OpenShift Service Catalog

### ISSUE THREAD

**Issue by donovanmuller** [CrunchyData/crunchy-containers#400]
Are there plans to expose the Crunchy functionality as a [Service Broker](https://github.com/openservicebrokerapi/servicebroker) implementation so that provisioning/deprovisioning/binding  can be accomplished through the OpenShift [Service Catalog](https://docs.openshift.org/latest/architecture/service_catalog/index.html)?

Similar to this example using an APB via the Ansible Service Broker: https://www.youtube.com/watch?v=kslVbbQCZ8s

**Comment by donovanmuller** [comment]
More specifically, similar to: https://pivotal.io/platform/services-marketplace/data-management/crunchy

**Comment by jmccormick2001** [comment]
thanks, yes, this topic has been discussed recently...I think its something we are considering.

**Comment by cahoonpwork** [comment]
Closing, look at OSB project https://github.com/CrunchyData/pgo-osb
