### ISSUE TITLE
Copy the "secrets" example from OpenShift over to Kubernetes

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#401]
The Kubernetes Secrets example needs to have a Kubernetes equivalent (it's only available for OpenShift at this time). 

https://github.com/crunchydata/crunchy-containers/tree/master/examples/openshift/secret
https://github.com/crunchydata/crunchy-containers/blob/master/docs/examples.adoc#secrets

**Comment by xenophenes** [comment]
I have this ready to go, waiting until latest two PRs are merged first to avoid conflicts.

**Comment by jmccormick2001** [comment]
merged into master
