### ISSUE TITLE
Copy the "ssl" example from OpenShift over to Kubernetes

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#402]
Kubernetes needs an equivalent example for customer-config-ssl authentication.

https://github.com/crunchydata/crunchy-containers/blob/master/docs/examples.adoc#ssl-authentication
https://github.com/CrunchyData/crunchy-containers/tree/master/examples/openshift/custom-config-ssl

**Comment by jasonodonnell** [comment]
Done in #501

**Comment by jmccormick2001** [comment]
merged
