### ISSUE TITLE
configmaps usage

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#416]
review all examples, where configmaps can be used, update examples (e.g. custom-config)

**Comment by jmccormick2001** [comment]
this might already be done, but a review of all the examples would be good to close this one off.

**Comment by xenophenes** [comment]
I believe this one can be closed out. 

To clarify, I'm assuming you are asking that any examples that make use of configuration files should use a ConfigMap to organize them. The following examples are already making use of configuration files and are mapping them using a ConfigMap:

- primary-deployment
- custom-config
- postgres-sshd
- pgpool
- backrest

The only example that does not follow this setup is *custom-config-ssl*, and it looks like it's being mapped using a Secret.

Looks good to me. Please let me know if you wanted something more specific or wanted something different checked in relation to this issue.

**Comment by jmccormick2001** [comment]
yep, this issue was just to convert any remaining examples over to using config maps instead of other file system based means (e.g. NFS paths).
