### ISSUE TITLE
limit job restarts

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#422]
if possible add a setting to all jobs that would limit the number of restarts for the job.  In the event of a bug or broken container, this would prevent starting endless numbers of errored jobs.

**Comment by xenophenes** [comment]
It looks like you can specify `restartPolicy` as a value of `Never` or `OnFailure` to make it stop retrying on first failure. Also `backoffLimit` can be set in combination with these.

**Comment by jasonodonnell** [comment]
`backoffLimit` is only available in Kubernetes 1.8+

**Comment by jmccormick2001** [comment]
dupe, captured by newer issue
