### ISSUE TITLE
1.8.0 testing crunchy watch panics on docker

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#428]
Chrunchy Watch 1.8.0 was not found so modified the run.sh and changed last line to
-d $CCP_IMAGE_PREFIX/crunchy-watch:centos7-10.1-1.7.1
When running run.sh it looks good but issuing docker logs watch reviles it failed with a panic.

docker logs watch
WARNING: PG_PRIMARY_SERVICE is deprecated and will be removed in a future release, use CRUNCHY_WATCH_PRIMARY instead.
WARNING: PG_PRIMARY_PORT is deprecated and will be removed in a future release, use CRUNCHY_WATCH_PRIMARY_PORT instead.
WARNING: PG_REPLICA_SERVICE is deprecated and will be removed in a future release, use CRUNCHY_WATCH_REPLICA instead.
WARNING: PG_PRIMARY_USER is deprecated and will be removed in a future release, use CRUNCHY_WATCH_USERNAME instead.
WARNING: PG_DATABASE is deprecated and will be removed in a future release, use CRUNCHY_WATCH_DATABASE instead.
WARNING: WATCH_PRE_HOOK is deprecated and will be removed in a future release, use CRUNCHY_WATCH_PRE_HOOK instead.
WARNING: WATCH_POST_HOOK is deprecated and will be removed in a future release, use CRUNCHY_WATCH_POST_HOOK instead.
WARNING: SLEEP_TIME is deprecated and will be removed in a future release, use CRUNCHY_WATCH_HEALTHCHECK_INTERVAL instead.
Starting crunchy watch
Started...
panic: runtime error: index out of range
goroutine 1 [running]:
main.main()
	/opt/cdev/src/github.com/crunchydata/crunchy-watch/main.go:170 +0x1497

**Comment by jmccormick2001** [comment]
@davecramer  please verify this is still a bug

**Comment by davecramer** [comment]
Yes, it is still a bug

**Comment by davecramer** [comment]
Much more than just this see https://github.com/CrunchyData/crunchy-watch/issues/43 for real issues

**Comment by davecramer** [comment]
fixed in https://github.com/CrunchyData/crunchy-watch/pull/47
