### ISSUE TITLE
1.8.0 testing Docker Only Proxy fails on comnect

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#430]
Proxy starts with no error but upon connection receive:
psql -h localhost -p 12432 -U postgres postgres
INFO[2018-02-12T19:17:43Z] Client: 172.17.0.1:59556 - authenticating    
ERRO[2018-02-12T19:17:43Z] An error occurred connecting to the master node 
ERRO[2018-02-12T19:17:43Z] Error dial tcp: missing address              
ERRO[2018-02-12T19:17:43Z] Client: 172.17.0.1:59556 - authentication failed 
ERRO[2018-02-12T19:17:43Z] Error: dial tcp: missing address

**Comment by jmccormick2001** [comment]
wont' fix for now, until crunchy-proxy is back to a maintained state
