### ISSUE TITLE
1.8.0 NFS mount location not specified

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#431]
During the creation of PGBouncer we want the NFS mount to be at /mnt/nfsfileshare but the web page we direct people to has the NFS at /nfsfileshare. We should probably make note that it should be at /mnt/nfsfileshare.

Additionally, the example assumes you have an NFS share path of /mnt/nfsfileshare/.
NFS is required to mount the pgbouncer configuration files which are
then mounted to /pgconf in the crunchy-pgbouncer container.

**Comment by xenophenes** [comment]
So if you look at the instructions (I'm assuming you're talking about [this document](https://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-setup-nfs-server-on-centos-7-rhel-7-fedora-22.html) referenced in install.adoc), you'll see that you are instructed to create a /nfsfileshare folder on the **server** but when you create the equivalent folder on the **client** you create it under /mnt/nfsfileshare:

> Now, create a mount point to mount the shared folder ‘/nfsfileshare’ which we’ve created before in the server.
> 
> [root@client ~]# mkdir /mnt/nfsfileshare
> Use below command to mount a shared directory “/nfsfileshare” from NFS server “192.168.12.5” in “/mnt/nfsfileshare” on client-server.
> 
> [root@client ~]# mount 192.168.12.5:/nfsfileshare /mnt/nfsfileshare
> Verify the mounted share on client server using “mount” command.

If you're referring to something else please let me know, but hopefully this clears things up. If it does, please comment to let us know so this issue can be closed!

**Comment by altondinsmore** [comment]
Yes it does. I noticed this in the code from Jason on another issue. Should have closed it at that point.
