### ISSUE TITLE
1.8.0 PGBouncer error on Docker

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#432]
PGBouncer starts and is connected to primary. After doing a "docker stop primary" get errors.

primary:5432 - accepting connections
primary:5432 - no response
Could not reach primary @  Mon Feb 12 20:14:55 UTC 2018
standalone failover.....
standalone failover is called
creating the trigger file on  replica
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.20/containers/replica/exec: dial unix /var/run/docker.sock: connect: permission denied
exiting after the failover has been triggered...
logger: 2018/02/12 20:14:55 bounce.go:37: bounce : starting
logger: 2018/02/12 20:14:55 bounce.go:46: opening /tmp/pgbouncer.ini
logger: 2018/02/12 20:14:55 bounce.go:50: open /tmp/pgbouncer.ini: no such file or directory
reloading pgbouncer config file
2018-02-12 20:14:55.435 11 LOG Got SIGHUP re-reading config

**Comment by jasonodonnell** [comment]
@jmccormick2001 This has indirectly been fixed since we disabled the failover script on bouncer.
