### ISSUE TITLE
1.8.0 Metrics Grfana dashboard import location

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#434]
We should explain how to import the dashboard from the config directory

**Comment by xenophenes** [comment]
This is done already in metrics.adoc: 
https://github.com/crunchydata/crunchy-containers/blob/master/docs/metrics.adoc#grafana-dashboard

@jmccormick2001 do you want the information repeated in examples.adoc or a reference in that document stating that it exists in metrics.adoc?

**Comment by altondinsmore** [comment]
I would say that the example should advise people that we have a Grafana dashboard available for import and to refer to document metrics.adoc for instructions.

**Comment by jmccormick2001** [comment]
lets go with a reference in examples.adoc to point this out to the users.

**Comment by xenophenes** [comment]
I went to go add this reference and found it's already there. 

https://github.com/crunchydata/crunchy-containers/blob/master/docs/examples.adoc#metrics-collection

> All metrics collected by this set of containers in addition to details on accessing the custom Grafana dashboards provided are fully described in this document.

**Comment by jmccormick2001** [comment]
ah, ok, I think that covers this one, closing out.
