### ISSUE TITLE
1.8.0 PITR Docker function pg_xlog_replay_resume() does not exist

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#439]
Missing function....
psql -h 127.0.0.1 -p 12001 -U postgres postgres -c 'select pg_xlog_replay_resume()'
Password for user postgres: 
ERROR:  function pg_xlog_replay_resume() does not exist
LINE 1: select pg_xlog_replay_resume()
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by jmccormick2001** [comment]
merged into master
