### ISSUE TITLE
1.8.0 PITR Docker pg_xlog_replay_resume not found

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#441]
xlog has changed in PG 10. It is now wal.

select pg_xlog_replay_resume();
select pg_wal_replay_resume();

https://www.dbrnd.com/2017/12/postgresql-10-important-name-change-from-xlog-to-wal-and-location-to-lsn/

**Comment by jmccormick2001** [comment]
merged
