### ISSUE TITLE
1.8.0 testing sshd Docker No ssh_host_rsa_key found in /sshd.

### ISSUE THREAD

**Issue by altondinsmore** [CrunchyData/crunchy-containers#442]
No matter how I try to change things it still can't find the sshd keys.

Checking for SSH Host Keys in /sshd...
No ssh_host_rsa_key found in /sshd.  Exiting..
[cmaster@dock18 postgres-sshd]$ ls /sshd
id_rsa.pub  ssh_host_ecdsa_key.pub  ssh_host_ed25519_key.pub  ssh_host_rsa_key.pub

from sshd.conf
Port 2022
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

HostKey /sshd/ssh_host_rsa_key
HostKey /sshd/ssh_host_ecdsa_key
HostKey /sshd/ssh_host_ed25519_key

**Comment by jasonodonnell** [comment]
@altondinsmore You need to mount the private keys, not the public keys.  This is an sshd service, the private keys are used in the handshake.

**Comment by jasonodonnell** [comment]
@altondinsmore It also appears that on your host where you are trying to execute the examples, you've made an actual `/sshd` directory.  

The `/sshd` is inside the container, you can mount any directory on your host to that container.

For example: [we generate the ssh keys in the local directory $(pwd)/keys](https://github.com/CrunchyData/crunchy-containers/blob/master/examples/docker/postgres-sshd/run.sh#L24-L27) and then [mount the files in that directory the `/sshd` directory](https://github.com/CrunchyData/crunchy-containers/blob/master/examples/docker/postgres-sshd/run.sh#L43) inside the container.

**Comment by jmccormick2001** [comment]
no changes necessary.
