### ISSUE TITLE
Streaming replication does not work with multiple replicas in a stateful set

### ISSUE THREAD

**Issue by harshal-shah** [CrunchyData/crunchy-containers#453]
While trying to use the statefulset example [described here](https://github.com/CrunchyData/crunchy-containers/blob/master/docs/examples.adoc#statefulsets) , the replication works fine when replica count is 2 but when we scale the statefulset to 3 replicas, the replication still happens to one pod only. 

For example : 

~~~
ubuntu@ip-172-31-16-198:~/harshal-ws/crunchy$ k get po -n devstg
NAME      READY     STATUS    RESTARTS   AGE
pgset-0   1/1       Running   0          19m
pgset-1   1/1       Running   0          19m
pgset-2   1/1       Running   0          18m
~~~

When querying `pg_stat_replication` on pgset-0, we see following : 

~~~
postgres=# select * from pg_stat_replication;
 pid | usesysid |   usename   | application_name |  client_addr   | client_hostname | client_port |         backend_start         | backend_xmin |   state   | sent_location | write_locat
ion | flush_location | replay_location | sync_priority | sync_state
-----+----------+-------------+------------------+----------------+-----------------+-------------+-------------------------------+--------------+-----------+---------------+------------
----+----------------+-----------------+---------------+------------
  56 |    16396 | primaryuser | pgset-2          | 100.100.117.13 |                 |       37700 | 2018-02-21 02:17:13.625351-05 |              | streaming | 0/50003A8     | 0/50003A8
    | 0/50003A8      | 0/50003A8       |             0 | async
(1 row)
~~~

We expected two rows since there are two read replicas.

**Comment by jmccormick2001** [comment]
thanks,I'll take a look into this.

**Comment by jmccormick2001** [comment]
I definitely see a bug in the statefulset logic that has surfaced since kube 1.6...I'll create a fix for this, should land in the 1.8.2 release of the crunchy-postgres container.

**Comment by harshal-shah** [comment]
Thanks @jmccormick2001. I should have specified the k8s version I was running, yes we are trying with kubernetes 1.8.6. Looking forward to get a solution for this.

**Comment by jmccormick2001** [comment]
https://hub.docker.com/r/jmccormick2001/crunchy-postgres/

the fix for this appears to work on my kube box...above is a test version of the postgres container with that fix applied...

if you run the examples/kube/statefulset example in the master branch it would be a good test if you have time to make sure this works for you.

regards.

eventually this fix will land in the 1.8.2 official release which should be in a couple of weeks I hope.

**Comment by harshal-shah** [comment]
Sorry for the delay, I shall test it over this week and update.

**Comment by jmccormick2001** [comment]
checking in to see if this is still an issue...thanks.
