### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#454]
The following images have no dependency on Postgres version:

* DBA
* Grafana
* Prometheus
* Promgateway
* Sim
* Vacuum

We should build these separately without a Postgres version tag to reduce duplicate builds.

**Comment by abrightwell** [comment]
Seems reasonable to me. I think it would have a benefit on multiple fronts. However, we would need to make sure that a proper transition plan/guidance is in place for those using the current convention. Should be simple enough, but I think the effort is worth it to prevent/minimize breaking environments.

**Comment by jmccormick2001** [comment]
I'm testing a change for this currently.  It performs the build one time, but will still create the 3 tags for each of them.  I want to retain the current CCP_IMAGE_TAG convention for various reasons but also like the idea of not building these needlessly.
