### ISSUE TITLE
pgbadger - fix nss_wrapper error

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#463]
need to fix the badger container to not get this error...probably needs the nss_wrapper added to the container now that ose_hack is common.

[suite@kube18 postgres-gis]$ kubectl logs badger -c badger
waiting for badgerserver to catch signal...
ERROR: ld.so: object '/usr/lib64/libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.

The badger app still works but the error needs resolving.

**Comment by jasonodonnell** [comment]
[Needs](https://github.com/CrunchyData/crunchy-containers/blob/master/rhel7/10/Dockerfile.pgbadger.rhel7#L34-L37) EPEL, nss_wrapper and gettext.

**Comment by jmccormick2001** [comment]
merged
