### ISSUE TITLE
adding a custom extension to postgresql - timescaledb

### ISSUE THREAD

**Issue by MattMacGillivray** [CrunchyData/crunchy-containers#464]
I probably missed it, but it isn't clear how to add a custom postgres extension, specifically timescaledb - http://docs.timescale.com/v0.8/getting-started/installation/linux/installation-yum

**Comment by jmccormick2001** [comment]
Hi, sorry for the long wait...currently we don't include FDWs within the main postgres image, we will likely do so soon.  For now, if you need a particular FDW you would need to extend the base Dockerfile for postgres we provide, add your extension, and build it for your use.  We will evaluate timescaledb's extension however when we look at exactly the set of FDWs we want to include as a default.  Those FDWs will be baked into the image and not be mounted externally.  regards.

**Comment by k1ng440** [comment]
can you give me an example how to do it?
