### ISSUE TITLE
pitr - update

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#465]
we need to update all the PITR examples and docs to use the latest terms/naming conventions, also the pitr.adoc needs to be updated with step-by-step things to perform when testing this from start to end.  The referenced blog is also out of date, so we need to drop that reference or update the redhat site with new information or post a new crunchy hosted blog on this topic.

**Comment by xenophenes** [comment]
To be clear, what naming conventions and terms are you referring to that you want updated?

**Comment by jmccormick2001** [comment]
I think the pitr.adoc can be merged into the pitr docs within examples.adoc at this point..

**Comment by xenophenes** [comment]
OK, will take that into account!
