### ISSUE TITLE
postgres startup.sh does not appear to be Kubernetes namespace aware

### ISSUE THREAD

**Issue by chrismellard** [CrunchyData/crunchy-containers#472]
There are a couple of kubectl commands in the startup.sh file for postgres that label the primary and replicas. This is required so I can get failover working using pgbouncer. As it stands these label commands fail when using namespaces within Kubernetes as `kubectl label` fails to find the pods if they are in any namespace other than default.

I've not started trying to fathom for a solution for this yet. Just posting this on the off chance I've missed something in my understanding.

Relevant line from startup.sh

`kubectl label --overwrite=true pod $HOSTNAME  name=$PG_PRIMARY_HOST`

To re-create this....

1. Fire up the Stateful Set example located at `crunchy-containers\examples\kube\statefulset`
2. Expected behaviour is `kubectl get pods --selector=name=$PG_PRIMARY_HOST` should return the pod you created.
3. Actual behaviour is `No resources found`

Consequently if using pgbouncer then the watch script here fails to find replicas to trigger a failover on.

**Comment by jmccormick2001** [comment]
#453 is going to cause trouble ....  I've created a fix for this, a test postgres image is out on dockerhub, this fix requires you add a PG_REPLICA_HOST env var to your stateful set and also I tweaked the labels in the statefulset, see the example/kube/statefulset example in master branch...would be great if you could test this against your use case and see if it fixes the issue.  regards.

**Comment by jmccormick2001** [comment]
merged into develop branch
