### ISSUE TITLE
pgAdmin4 Failing RH Scans

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#474]
[This line of code](https://github.com/CrunchyData/crunchy-containers/blob/master/rhel7/10/Dockerfile.pgadmin4.rhel7#L64) is causing the pgAdmin4 to fail certification scans.  

Explore what it would take to configure apache to use a different directory that doesn't require permission changes.

**Comment by jmccormick2001** [comment]
merged
