### ISSUE TITLE
replica readiness script fails

### ISSUE THREAD

**Issue by davecramer** [CrunchyData/crunchy-containers#479]
/opt/cpm/bin/setenv.sh
setting PGROOT to  /usr/pgsql-10
chown: cannot access '/pgwal/pr-replica-wal': No such file or directory

A simple solution is to put a check to see if we are in 'ARCHIVE_MODE' in the script

**Comment by xenophenes** [comment]
This looks like this was addressed in issue #523 when refactoring the start scripts. The error you're seeing came out of /bin/postgres/start.sh where it attempts to set the -wal directory, which is now handled like this:


```
if [[ -v ARCHIVE_MODE ]]; then
    if [ $ARCHIVE_MODE == "on" ]; then
        mkdir -p $PGWAL
        chmod 0700 $PGWAL
        echo_info "Creating wal directory in ${PGWAL?}.."
    fi
fi
```

This issue should be good to resolve @jmccormick2001 .
