### ISSUE TITLE
standardize all example file names

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#503]
create a naming convention for the example file components

currently we have standards in some of the file names like run.sh or cleanup.sh
but other files need a standard naming convention.

**Comment by xenophenes** [comment]
One example of this might be having simple names that are easy to type for example directories - for example, 
- pgpool-deployment -> pgpool. 
- pgdump-job -> pgdump
- pgrestore-job -> pgrestore
- vacuum-job -> vacuum
- backup-job -> backup
- primary-restore -> restore
- postgres-sshd -> sshd
- primary-deployment -> deployment

Another, docker/basic -> docker/primary to match the openshift/kube equivalents (after they're also renamed).

Also, JSON files should be consistently named. Should be the name of the folder .json for deployments or templates, and append the json type after the name for specifics.

We could also look at condensing the pgadmin4-http and -https examples into one folder (just pgadmin4).

**Comment by xenophenes** [comment]
Another example, most pods in the examples have simple names wherever possible. Some are outliers like **badger-example** - should be consolidated to **pgbadger**.
