### ISSUE TITLE
BADGER_TARGET needs to be documented properly

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#513]
The pgbadger example seems to work without setting it, but the logs warn that BADGER_TARGET is not set. Something should be mentioned in example.adoc about this warning and containers.adoc should contain an example of how to set it and what you would set it to. Potentially, this warning should be removed altogether and the variable made optional as long as pgbadger is actually targeting the postgres database in the pod.

**Comment by jasonodonnell** [comment]
@xenophenes Does this not suffice? https://github.com/CrunchyData/crunchy-containers/blob/master/docs/containers.adoc#environment-variables-6

**Comment by xenophenes** [comment]
1) To avoid confusion when the warning comes up, a note should be made in examples.adoc that clarifies the container **is** being targeted without the variable being set. My initial reaction was to assume badger wasn't working and wasn't targeting a database container. I'm likely not going to be the only one. 

2) "Potentially, this warning should be removed altogether and the variable made optional as long as pgbadger is actually targeting the postgres database in the pod."

**Comment by jasonodonnell** [comment]
Agreed, I think the warning log sends the wrong impression.
