### ISSUE TITLE
Consistency - some containers "echo" when starting, others don't

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#523]
**I'm submitting a ...**

 
 - [ ] bug report
 - [x] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Some container examples currently report their status when starting up...

`echo "Starting postgres-gis container..."`

...while others don't.

**What is the expected behavior?**

It should be one or the other.

**What is the motivation or use case for changing the behavior?**

We need to determine if it's worthwhile to echo the starting statement and either have all of the containers reflect that or none of them.

**Comment by jasonodonnell** [comment]
These need the common_lib updates:

https://github.com/CrunchyData/crunchy-containers/tree/master/bin/backrest_restore
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/backup
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/bench
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/pgdump
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/pgpool
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/pgrestore
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/postgres-gis
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/postgres
https://github.com/CrunchyData/crunchy-containers/tree/master/bin/upgrade

**Comment by jasonodonnell** [comment]
I am doing `backrest_restore` as part of a different effort @xenophenes
