### ISSUE TITLE
pgDump container not setting file extension

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#548]
**I'm submitting a ...**

 
 - [X] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behavior?**

The pgDump container [sets the file extension based on format specified](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/pgdump/start-pgdumpjob.sh#L158-L171) (PGDUMP_FORMAT).  However, [this extension is never actually used by the code](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/pgdump/start-pgdumpjob.sh#L273), which results in a file without an extension.

**If the current behavior is a bug, please provide the steps to reproduce:**

```bash
#!/bin/bash

mkdir -p /tmp/pgdump

docker network create --driver bridge pgnet

docker run \
    --name=primary \
    --hostname=primary \
    --publish=5432:5432 \
    --network="pgnet" \
    --env=PG_MODE=primary \
    --env=PG_PRIMARY_USER=primaryuser \
    --env=PG_PRIMARY_PASSWORD=password \
    --env=PG_PRIMARY_HOST=primary \
    --env=PG_PRIMARY_PORT=5432 \
    --env=PG_DATABASE=userdb \
    --env=PG_USER=testuser \
    --env=PG_PASSWORD=password \
    --env=PG_ROOT_PASSWORD=password \
    --detach crunchydata/crunchy-postgres:centos7-10.3-1.8.2

sleep 10

docker run \
    --name=pgdump \
    --hostname=pgdump \
    --network="pgnet" \
    --volume=/tmp/pgdump:/pgdata:z \
    --env=PGDUMP_HOST=primary \
    --env=PGDUMP_DB=userdb \
    --env=PGDUMP_USER=testuser \
    --env=PGDUMP_PASS=password \
    --env=PGDUMP_PORT=5432 \
    --env=PGDUMP_LABEL=mybackup \
    --env=PGDUMP_FORMAT=plain \
    --env=PGDUMP_VERBOSE=true \
    --env=CRUNCHY_DEBUG=true \
    --detach crunchydata/crunchy-dump:centos7-10.3-1.8.2

sleep 10

ls $(find /tmp/pgdump/primary-dumps -type d -name '2018*' | head -n 1)
```

**What is the expected behavior?**

`pgdump` file should be `pgdump.sql`

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

[`PGDUMPEXT`](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/pgdump/start-pgdumpjob.sh#L273) should be changed to `PGDUMP_EXT`

**Comment by xenophenes** [comment]
This issue has been resolved in a prior PR by Jason: https://github.com/CrunchyData/crunchy-containers/commit/7422d383946eb1c9901d8a410181485598e7527f @jmccormick2001
