### ISSUE TITLE
Bring Docker examples in line with Kube/OCP examples

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#553]
**I'm submitting a ...**

 
 - [x] feature request

**What is the current behavior?**

The Docker examples are now inconsistent with the naming convention used in the Kube/OCP example folder. For example, the PITR example between the two environments have different created resource names. These should be made the same. Folder and file names should also be replicated.

**What is the motivation or use case for changing the behavior?**

In line with the goals of 1.8.3, improving consistency and usability throughout the project.

**Comment by jmccormick2001** [comment]
thanks for catching this...
