### ISSUE TITLE
remove examples/pv

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#561]
verify that it is safe to remove examples/pv 

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by xenophenes** [comment]
At this point, I've done a full test of the Kube examples using HostPath storage without using the create-pv script (when addressing a separate issue). Additionally, examples/pv is no longer referenced anywhere anymore - it's not in the Install document at this point. 

Do you feel additional testing is necessary, or should I go ahead and remove the folder?
