### ISSUE TITLE
example/helm/primary-replica, failed to write on persistent volume

### ISSUE THREAD

**Issue by zcui99** [CrunchyData/crunchy-containers#563]
**I'm submitting a ...**

 - [X ] bug report

**What is the current behavior?**

When I use persistent volume for pgdata and backup,  start.sh simply cannot create directory: 

Wed Apr  4 21:20:29 UTC 2018
setting PGROOT to  /usr/pgsql-9.6
chown: cannot access '/pgdata/cui-postgres-primary': No such file or directory
chown: cannot access '/pgwal/cui-postgres-primary-wal': No such file or directory
pgpguser does exist
pgroot does exist
pgprimary does exist
mkdir: cannot create directory '/pgdata/cui-postgres-primary': Permission denied
chmod: cannot access '/pgdata/cui-postgres-primary': No such file or directory
rm: cannot remove '/pgdata/cui-postgres-primary/postmaster.pid': No such file or directory
User id is...
uid=26(postgres) gid=26(postgres) groups=26(postgres)
...

**If the current behavior is a bug, please provide the steps to reproduce:**

1. create a persistent volume with RWO and persistent volume claim:
   Persistent volume is dynamic provisioned by underneath NFS storage provisioner.

2. create the persistent volume claim:

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cui-postgres-primary-pgdata
  labels:
    name: cui-postgres-primary
    chart: "primary-replica-1.0.0"
    release: "cui-postgres"
    heritage: "Tiller"
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "8Gi"3. 

3. use the persistent volume claim for pgdata in primary-pod.yaml:

  volumes:
  - name: pgdata
    persistentVolumeClaim:
      claimName: cui-postgres-primary-pgdata
  - name: backup
    emptyDir: {}

No securtyContext is used.

**What is the expected behavior?**

postgres DB shall be up and running

**What is the motivation or use case for changing the behavior?**

persistent volume is recommended way in k8s to store the data.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System: centos7
 - Container Image Tag: centos7-9.6.8-1.8.2
 - PostgreSQL Version: 9.6
 - Platform (Docker, Kubernetes, OpenShift): kubernetes
 - Platform Version:1.6.9

Note: My kubernete cluster node is running Ubuntu16.04 LTS.

**Comment by xenophenes** [comment]
Thanks for submitting this bug report - I'll be taking a look at this early next week and determining what the issue is, and will follow up then.

**Comment by zcui99** [comment]
No, it won't help. The issue is that start.sh as postgres user 26 cannot create the directory on 
/pgdata/<pvc-name>, which is sitting on a pv.  I even set: 
   securityContext:
      allowPrivilegeEscalation: true
it still won't help

**Comment by xenophenes** [comment]
The permission errors you're seeing are being caused by the persistent volume settings or perhaps the NFS mount settings. It may help if we could view your export settings for NFS on your system:

`cat /etc/exports`

**Comment by xenophenes** [comment]
Specifically, the NFS export settings should be set to something similar to the following: 

`/nfsfileshare 10.0.0.0/24(rw,sync,no_root_squash)` 

It is possible the permission errors are being caused by export settings including `root_squash` instead of `no_root_squash`.

It is also worthwhile to note that `/nfsfileshare` is owned by `nfsnobody:nfsnobody` or `65534`. 

When supplementalGroups is defined as [65534], the pod will include the nfsnobody group in the list of groups for the pod user.

**Comment by xenophenes** [comment]
Hello! Just checking in - did you have a moment to check this out?

**Comment by zcui99** [comment]
could you tell me what the changes are. 
The reason DB fail to start is because of permission on /pgdata and /backup, which is still owned by root instead of "postgres",  dockerfile "centos7/9.6/Dockerfile.postgres.centos7 " is supposed to change persmission of the volumes to "postgres:postgres":

RUN chown -R postgres:postgres /opt/cpm /var/lib/pgsql \
    /pgdata /pgwal /pgconf /backup /recover /backrestrepo

But when I map /pgdata and /backup to NFS based persistent volume in primary-pod.yaml
and start the pod, go inside the pod, you can see:

$kubectl --namespace ns-cui-postgres exec pg-primary -it /bin/bash
bash-4.2$ ls -l /
total 24
-rw-r--r--   1 root     root     15712 Dec 14  2016 anaconda-post.log
drwxr-xr-x   2 postgres postgres     6 Apr 20 19:41 backrestrepo
**drwxr-xr-x   2 root     root      4096 Apr 20 19:41 backup**
lrwxrwxrwx   1 root     root         7 Dec 14  2016 bin -> usr/bin
drwxr-xr-x   5 root     root       360 Apr 20 19:41 dev
drwxr-xr-x  89 root     root        66 Apr 20 19:41 etc
drwxr-xr-x   2 root     root         6 Nov  5  2016 home
lrwxrwxrwx   1 root     root         7 Dec 14  2016 lib -> usr/lib
lrwxrwxrwx   1 root     root         9 Dec 14  2016 lib64 -> usr/lib64
drwx------   2 root     root         6 Dec 14  2016 lost+found
drwxr-xr-x   2 root     root         6 Nov  5  2016 media
drwxr-xr-x   2 root     root         6 Nov  5  2016 mnt
drwxr-xr-x   7 root     root        17 Apr 20 19:06 opt
drwxr-xr-x   2 postgres postgres     6 Apr 20 19:41 pgconf
drwxr-xr-x   2 root     root      4096 Apr 20 19:41 pgdata
drwxrwxrwt   3 root     root       120 Apr 20 19:41 pgprimary
**drwxrwxrwt   3 root     root       120 Apr 20 19:41 pgroot**
drwxrwxrwt   3 root     root       120 Apr 20 19:41 pguser
drwxr-xr-x   2 postgres postgres     6 Apr 20 19:41 pgwal
dr-xr-xr-x 575 root     root         0 Apr 20 19:41 proc
drwxr-xr-x   2 postgres postgres     6 Apr 20 19:41 recover
dr-xr-x---   3 root     root        18 Mar 29 20:24 root
drwxr-xr-x  13 root     root        21 Apr 20 19:41 run
lrwxrwxrwx   1 root     root         8 Dec 14  2016 sbin -> usr/sbin
drwxr-xr-x   2 root     root         6 Nov  5  2016 srv
drwxr-xr-x   2 root     root         6 Apr 20 19:41 sshd
dr-xr-xr-x  13 root     root         0 Jan 17 20:01 sys
drwxrwxrwt   7 root     root       131 Apr 20 19:42 tmp
drwxr-xr-x  21 root     root       113 Mar 29 20:44 usr
drwxr-xr-x  31 root     root        17 Apr 20 19:46 var

**Comment by jasonodonnell** [comment]
@zcui99 Your NFS Server is changing the permissions to root when the volume is mounted.  As @xenophenes mentioned, you need to change the export settings *on your NFS server*.  This is not a problem with the containers but rather NFS server export settings.

Specifically we suggest these export options on your NFS server (`/etc/exports`): 
`/nfsfileshare 10.0.0.0/24(rw,sync,no_root_squash)`

Note: 10.0.0.0/24 is an example subnet

After changing these settings you have to refresh the exports: `sudo exportfs -r`

Next, if there are any folders already on the NFS mount that are owned by root, you need to clean those up in order for new directories to be created with the right permissions (from your example this would most likely be a `pg-primary` directory on the nfs mount owned by root).

**Comment by zcui99** [comment]
I know the cause. Since I mount /pgdata and /backup  in my pod to persistent volumes, centos7/9.6/Dockerfile.postgres.centos7  shall not /pgdata and /backup in its VOLUME directory, neither it shall create /pgdata and /backup  in this docker file.

I didn't change this dockerfile before.  After I made above change, rebuild the image, it works fine. 
Thanks a lot
