### ISSUE TITLE
liveliness and readiness probe broken in openshift

### ISSUE THREAD

**Issue by fer-marino** [CrunchyData/crunchy-containers#57]
hi,
as the subject says, those probes are broken in the examples with image tag centos7-9.5-1.2.5.

it looks like you have to manually pass the username to the commands to make them work.

I've tested it with the latest version of minishift (0.9.0) and openshift (1.3.1) with the test environment you get with oc cluster up.

regards,
fernando

**Comment by jmccormick2001** [comment]
Hi,

what error are you seeing in your logs?

**Comment by fer-marino** [comment]
psql: local user with ID 1000080000 does not exist

that id is randomly generated by openshift. The probes shall uses the username to work:

      psql -U $PG_USER .....

**Comment by jmccormick2001** [comment]
ah, good catch, I'll work on this fix today.

**Comment by jmccormick2001** [comment]
I changed the probes now to be bash scripts, in those scripts they can reference vars like PG_USER, I've updated the openshift and kube examples to use those scripts, merged into master...the next release will include this by default, probably end of the month 1.2.6 will be tagged/pushed.  thanks for pointing this bug out!  cheers.
