### ISSUE TITLE
Enviroment variable SLAVE_TO_TRIGGER_LABEL not used in watch kube example

### ISSUE THREAD

**Issue by App-247** [CrunchyData/crunchy-containers#58]
Environment variable **SLAVE_TO_TRIGGER_LABEL** declared in **watch-pod.json** but not used in **start-watch.sh**.

**Comment by jmccormick2001** [comment]
thanks for pointing this out...somehow this env var got lost!  I've recreated the logic for supporting this env var, updated the docs and examples...this will require a new container image build to pull in this fix...the feature will land in the upcoming 1.2.6 release when we push out new container images.
