### ISSUE TITLE
Integrate pgmonitor into metrics stack

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#582]
**I'm submitting a ...**

 
 - [X] feature request

**What is the motivation or use case for changing the behavior?**
pgMonitor offers a lot more metrics and better dashboards.

**Comment by pmereddy1** [comment]
pg_stat_activity_count metrics exported by collect container are not accurate.
You will see only one active session regardless of the activity on the postgres cluster.
Upon investigation, I learned that collect container is using primaryuser to gather information on session activity and this db user is not authorized to check session activity. Thanks Jason.

**Comment by jmccormick2001** [comment]
please see Keith Fiske for their 2.0 tag soon to land, if possible, integrate that new version.

**Comment by jasonodonnell** [comment]
@jmccormick2001 Spoke with Keith, 2.0 uses the newest version of Grafana (5).  You cool with me updating to that version?

**Comment by jmccormick2001** [comment]
yep, lets upgrade.
