### ISSUE TITLE
Add pg_cron extension to crunchy-postgres and crunchy-postgres-gis images

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/crunchy-containers#584]
**I'm submitting a ...**

 
 - [ ] bug report
 - [X ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
No database job scheduler in crunchy-postgres images

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**
Application users can schedule jobs to perform maintenance activities.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
pg_cron is a postgresql database extension available at https://github.com/citusdata/pg_cron

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
crunchy-postgres, crunchy-postgres-gis
 - PostgreSQL Version:
10.0 or later
 - Platform (Docker, Kubernetes, OpenShift):
Kubernetes 1.8+
 - Platform Version:

**Comment by jmccormick2001** [comment]
closed due to packaging issues.  Will readdress with probably a different solution or alternative.

**Comment by senzacionale** [comment]
Do we have any solution how to use  pg_cron with Docker and your crunchy-postgres?
