### ISSUE TITLE
Permission denied in Crunchy Watch failover function

### ISSUE THREAD

**Issue by App-247** [CrunchyData/crunchy-containers#59]
Hi, running crunchy-watch in Google Cloud Platform, pod logs shows error:
```
no trigger slaves found...using any slave
++ cut -f1 '-d '
++ kubectl get pod --selector=name=replica --no-headers
/opt/cpm/bin/start-watch.sh: line 91: /opt/cpm/bin/kubectl: Permission denied
```
Permissions in **/opt/cpm/bin**:
```
bash-4.2$ ls -l /opt/cpm/bin
total 54764
-rw-r--r-- 1 root root        0 Nov 17 15:17 kubectl
-rwxr-xr-x 1 root root 56066588 Nov 17 15:17 oc
-rwxrwxr-x 1 root root     5245 Nov 16 20:09 start-watch.sh
```

**Comment by jmccormick2001** [comment]
I see the problem, the kubectl command was not included correctly in the image, I'll push out a fix today for this.

**Comment by jmccormick2001** [comment]
ok, just pushed a new 1.2.5 watch  container to dockerhub, this one will also include the fixes for the SLAVE_TO_TRIGGER env var as well.
