### ISSUE TITLE
Error connecting primary-master in statefulset example

### ISSUE THREAD

**Issue by geoxanadu** [CrunchyData/crunchy-containers#596]
**I'm submitting a possible bug**

 
 - [x ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
ubuntu@k8s-master:~/crunchy-containers/examples/helm/psql-gis/templates$ psql -h pgset-primary -U postgres
psql: could not translate host name "pgset-primary" to address: Name or service not known

**If the current behavior is a bug, please provide the steps to reproduce:**

install the example as described in git. The example is installed on a kubernetes cluster with 3 nodes.
even if I choose the cluster-ip I am not able to connect to the database. 
the same applies for your master-replica example, although I can connect here using the cluster up adress

**What is the expected behavior?**

access the master and replica pgset respectively

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

do understand corretly that your master-replica example does not provide loadbalancing (pgpool)? or what is the difference between the statefulset and the master-replica. I would like to have an automated scalable database system with HA, synchronous streaming replication, and loadbalancing the queries to the slaves.

**Please tell us about your environment:**

 - Operating System: Ubuntu 16.04 TLS
 - Container Image Tag: centos7-10.3-1.8.2
 - PostgreSQL Version: 10.3 (crunchy-postgres-gis)
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: v1.8.9

**Comment by jpreed2** [comment]
I believe you must be logged into one of your pods for the hostname to resolve properly.

Having said that, I am having a similar problem.  The example includes 3 different services, one each for primary and slave with nodePort: 0, and one general one with clusterIP: None.  I can't access either the master or slave as the documentation suggests:

`# psql -h pgset-primary -U postgres postgres`
`psql: could not connect to server: Connection refused`
`        Is the server running on host "pgset-primary" (10.96.116.164) and accepting`
`        TCP/IP connections on port 5432?`

However, I can access the general service:

`# psql -h pgset -U postgres postgres`
`Password for user postgres:`
`psql (9.6.8)`
`Type "help" for help.`

I'm not sure which instance the general service is connecting to and/or how I can connect specifically to the master or slave instances.  It seems something is incorrect in either the documentation or configs (or both).

Thanks!
