### ISSUE TITLE
Issues with getting container cluster on minikube to run properly

### ISSUE THREAD

**Issue by sp1ze** [CrunchyData/crunchy-containers#60]
Hi,

I'm currently trying to setup crunchy-containers/examples/kubehelm/crunchy-postgresql-cluster/ on minikube. It seems that my master pod never gets created properly. It is is status "Waiting: ContainerCreating"

I'm following this tutorial by Jeff McCormick: http://blog.kubernetes.io/2016/09/creating-postgresql-cluster-using-helm.html?m=1

There is only one line in the logs for the master pod:
"container "server" in pod "gone-dog-crunchy-master" is waiting to start"

Everything else seems to been created properly. Am I doing something wrong with the setup?

**Comment by jmccormick2001** [comment]
Hi,

could be the image is not on that host for some reason, do a 'docker images' and make sure the crunchy container image with that tag is there.  Also, if you could supply the output of a 'kubectl get pod xxx -o yaml' I'll see if I spot anything there.

**Comment by sp1ze** [comment]
Hi Jeff and thanks for the quick reply.

The image exists on the host:
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
crunchydata/crunchy-postgres   centos7-9.5-1.2.5   2fa835097be0        3 weeks ago         652.2 MB

I noticed one thing during the day, and that is the use of NFS volume in the values.yaml
I hosted my own NFS server that i could connect to externally and updated my values in the values.yaml. After one more helm installation i got the following output from the 'kubectl describe pod xxx-crunchy-master':
  
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  3m		3m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned garish-tiger-crunchy-master to minikube
  1m		1m		1	{kubelet minikube}			Warning		FailedMount	Unable to mount volumes for pod "garish-tiger-crunchy-master_default(1e3048d2-c20c-11e6-9607-aa4923bfe162)": timeout expired waiting for volumes to attach/mount for pod "garish-tiger-crunchy-master"/"default". list of unattached/unmounted volumes=[pgdata]
  1m		1m		1	{kubelet minikube}			Warning		FailedSync	Error syncing pod, skipping: timeout expired waiting for volumes to attach/mount for pod "garish-tiger-crunchy-master"/"default". list of unattached/unmounted volumes=[pgdata]

So i started to search for the timeout issue when mounting volumes for kube and minikube, and it seems to be a common issue.

Here is my 'kubectl get pod xxx -o yaml' output
[output.txt](https://github.com/CrunchyData/crunchy-containers/files/652027/output.txt)

Maybe I should try creating the pv with hostPath instead of NFS? This as I will use the environment for development purpose.

**Comment by jmccormick2001** [comment]
you might want to check out the
PVC status, run 'kubectl get pvc', see if the PVC is bound to the PV...also you can run 'kubectl get pv' to see if the PV was created...you can also run a test of your NFS client locally to see if NFS is working...check out the docs here for NFS:  http://www.itzgeek.com/how-tos/linux/centos-how-tos/how-to-setup-nfs-server-on-centos-7-rhel-7-fedora-22.html

that link shows how to test NFS locally.

**Comment by sp1ze** [comment]
PV has been created:
kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   STATUS    CLAIM                              REASON    AGE
master-nfs-pv                              400M       RWX           Bound     default/master-nfs-pvc                       1h

PVC is bound to the PV:
kubectl get pvc
NAME                       STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
master-nfs-pvc             Bound     master-nfs-pv                              400M       RWX           1h

I run the NFS server on  the same computer as i run minikube (can there be any issues with this setup?). I have tried to mount the NFS server with a client on another computer and that works fine. I'm currently running ubuntu. But I will take a look at your link and let you know if I might get it to work.

**Comment by jmccormick2001** [comment]
the best guess I have right now is that minikube appears to only support hostPath persistent volumes.  The helm example uses NFS, so you might have to modify the example to instead use hostPath PVs.

**Comment by sp1ze** [comment]
Yeah I saw there where some open issues in the kubernetes project related to NFS and minikube not working properly.

I tried to use hostPath and the path was created successfully in the minikube singel node. Also the master pod started to create this time. 

But somewhere it seems to be some kind of permission issue for the postgres pod to work with the hosPath.

I have attached the pod logs for more information below:
please notice "mkdir: cannot create directory '/pgdata/opinionated-iguana-crunchy-master': Permission denied"
[pod.txt](https://github.com/CrunchyData/crunchy-containers/files/656851/pod.txt)

This seems to also be a common issue. I guess the pod is not running as sudo inside the minikube node?

**Comment by jmccormick2001** [comment]
the pod should be running as the postgres user (uid=26), so the hostPath that gets mounted would need to be writable by the UID=26 user, you might check the permissions of the hostPath that minikube is using.  If I can get some time today I'll try it out but that is what I'd look for next.

**Comment by jmccormick2001** [comment]
any update?  I'll likely close this out unless I hear back as I think it is the way minikube is configured to work instead of anything in the example itself.

**Comment by sp1ze** [comment]
I agree. It seem to exist some limitations within minikube.
