### ISSUE TITLE
split out crunchy-postgres-gis from crunchy-postgres

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#61]
probably a good time to split out the GIS packages into a separate container when users need a postgres+postgis container....the postgres-gis would inherit from the postgres container to avoid duplication...

**Comment by pvacca** [comment]
Sure. I've got a minor refactor for 9.6 just waiting to check in. Can split postgis out, too. Just as soon as the upgrade demo script runs beginning to end... 
Github doesn't seem to be letting me assign to myself for some reason.

**Comment by jmccormick2001** [comment]
lets do a separate PR for the 9.6 support, then another PR for the upgrade container, if both of those get done, reviewed, merged, I'd like to add those into 1.2.6 next week.  After all that is done, we can address this one, probably for the 1.2.7 release.

**Comment by thesteve0** [comment]
Are you going to do that with other extensions as well?

If I understand right this will produce a new container in DockerHub right?

**Comment by jmccormick2001** [comment]
yep, this would move the postgis+pgrouting extensions which are quite heavy into a new crunchy-postgres-gis container...the other extensions like pgaudit and pg_stat_statements and backrest are smaller, simpler, and not GIS related so I might leave them in the base pg container for the first cut.  This split would allow us to greatly extend the postgres-gis container in the future too.

**Comment by thesteve0** [comment]
Sounds good.
What about a more generic way to load other extensions?

http://pgxn.org/

https://github.com/dhamaniasad/awesome-postgres#extensions

Would S2I help with that?

**Comment by jmccormick2001** [comment]
maybe, I definitely would like a smarter way to add extensions rather than having to add the packages directly within the Dockerfile, I'll take a look at these other techniques.

**Comment by pvacca** [comment]
I actually have an idea on making the extensions more configurable at build
time with a docker in docker technique. Let's get the postgis extension
split out as discussed, and I can explain this in more detail after the
coming release is tested and ready to go.

**Comment by jmccormick2001** [comment]
merged in new dockerfiles for a new container, *crunchy-postgres-gis*, it is identical to *crunchy-postgres* except it includes the PostGIS and pgrouting packages...after this, the *crunchy-postgres* image no longer includes the GIS packages.  This will land in the upcoming 1.2.7 release.
