### ISSUE TITLE
standardize all ocp templates to use storage classes and add docs

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#611]
for the current ocp templates, add docs in examples.adoc that describes what each template is for and what it does/builds...also, assume that these example templates will have access to a storage class, allow the template user to specify a storage class name.  Allow the templates to use default names that do not conflict with each other if all defaults are taken.  Apply naming conventions for PVCs, svcs, etc that mimic our current naming conventions in the kube examples.

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jmccormick2001** [comment]
please verify this is completed or not.  thanks.

**Comment by xenophenes** [comment]
@jmccormick2001 

Docs were added for the following container examples:

- single primary
- primary restore
- primary restore secrets 
- primary backup
- primary backup secret 
- postgres replicated
- pgadmin4

All docs look standardized and complete, with consistent information.

All examples look as if they have consistent naming schemes for the PVCs and are now open for use for multiple storage classes.

Looks good to me to close this issue.
