### ISSUE TITLE
PostgreSQL Readiness/Liveliness Probes

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#614]
**I'm submitting a ...**

 
 - [X] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behavior?**

The readiness and liveliness probes use `$PG_USER` for executing health checks.  This should be the `postgres` user instead.

**What is the motivation or use case for changing the behavior?**

 In environments where `pg_hba.conf` locks down local connections to `peer` authentication (instead of trust), only the `postgres` user would be allowed to connect locally.

**Comment by jmccormick2001** [comment]
as discussed last week or the week before this value needs to remain configurable and not be hard coded.
