### ISSUE TITLE
Primary Deployment permission denied on OpenShift

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#616]
**I'm submitting a ...**

 
 - [X] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behavior?**

This example is very old and doesn't work correctly on OCP due to permission denied error:

```bash
mkdir: cannot create directory '/pgdata/primary-deployment': Permission denied
chmod: cannot access '/pgdata/primary-deployment': No such file or directory
primary-deployment-3797989868-tpz57:5432 - no response
primary-deployment-3797989868-tpz57:5432 - no response
primary-deployment-3797989868-tpz57:5432 - no response
primary-deployment-3797989868-tpz57:5432 - no response
primary-deployment-3797989868-tpz57:5432 - no response
primary-deployment-3797989868-tpz57:5432 - no response
....
```

**What is the motivation or use case for changing the behavior?**

This example needs to be updated to include correct volume locations, persistence and security context.

**Comment by jangel97** [comment]
I am facing this issue and don't know what to do.
![image](https://user-images.githubusercontent.com/38217290/77083270-85c2cd00-69fd-11ea-8bda-7566f9885a11.png)
I used the following env variables:
export CCP_SECURITY_CONTEXT=""
export CCP_STORAGE_PATH=/data
export CCP_STORAGE_MODE=ReadWriteMany
export CCP_STORAGE_CAPACITY=400M

**Comment by jkatz** [comment]
Ensure your `fsGroup` is set to 26.

**Comment by jangel97** [comment]
I moved to the nfs storage and it worked!
