### ISSUE TITLE
watch example doesnt work on openshift

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#618]
bug in watch example when running on openshift.  see kube/watch example, execute on OCP.

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by jasonodonnell** [comment]
The current example sets the following env: https://github.com/CrunchyData/crunchy-containers/blob/master/examples/kube/watch/watch.yaml#L29

@abrightwell pointed out that OpenShift has a specific variable: https://github.com/CrunchyData/crunchy-watch#openshift

Probably why this isn't working on OpenShift.

**Comment by jmccormick2001** [comment]
merged fix into master branch.
