### ISSUE TITLE
Primary Example doesn't match documentation 

### ISSUE THREAD

**Issue by ValClarkson** [CrunchyData/crunchy-containers#626]
**I'm submitting a ...**

 
 - [x ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
-p 12000:5432 \
-p 5432:5432 \
I looked in the code and it looks like the port forwarding was changed.
in the documentation it states in the docker section "connect to your local host as follows:"
psql -h localhost -p 12000 -U testuser -W userdb

this is no longer valid
**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by xenophenes** [comment]
This was addressed in a recent pull request. This issue should be good to close.
