### ISSUE TITLE
Configure crunchydata thru helm

### ISSUE THREAD

**Issue by kiranmudemela** [CrunchyData/crunchy-containers#636]
Hi .. 
Can you share the doc/link for configuring crunchydata thru helm chart ?

**Comment by xenophenes** [comment]
Hello! 

All Helm examples are located in the $CCPROOT/examples/helm directory, along with their associated README documents. Currently, five examples are provided out of the entire collection of Container Suite examples.

https://github.com/CrunchyData/crunchy-containers/tree/master/examples/helm/

Hopefully that helps!

**Comment by kiranmudemela** [comment]
We are planing to have it in kubernetes. Could you pls share the right link ?

**Comment by xenophenes** [comment]
I'm sorry, I'm not quite sure what you're asking for - are you no longer interested in the Helm documentation?

If you're planning on running in a Docker, Kubernetes, or OpenShift environment, the documentation for the project is available here: https://crunchydata.github.io/crunchy-containers/

That should lead you in the right direction for installing in either of the above three listed environments and running all examples.

The Helm documentation that I linked you before is the only aspect of the documentation not available on that above website.

**Comment by xenophenes** [comment]
Please let me know if this resolves the issue.

**Comment by kiranmudemela** [comment]
we are yet to configure in Oracle Kubernetes (using helm ) on Oracle Linux. Will this work ?

**Comment by xenophenes** [comment]
Most likely, yes. This has not been tested, however.

**Comment by kiranmudemela** [comment]
Alrite. Could you provide me the list of steps for Kubernetes thru helm charts ?

**Comment by xenophenes** [comment]
I'm afraid I'm not quite sure of what you're asking - are you asking how to install Kubernetes, Helm, or the Container Suite?

**Comment by kiranmudemela** [comment]
Thanks Sarah. Pls close this.
