### ISSUE TITLE
Missing volume definition in pgrestore doc

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#644]
The [pgrestore](https://crunchydata.github.io/crunchy-containers/container-specifications/crunchy-pgrestore/) is missing a section on `volumes`.  It should have something similar to [pgdump](https://crunchydata.github.io/crunchy-containers/container-specifications/crunchy-pgdump/#volumes).

**Comment by xenophenes** [comment]
This can be closed, @jmccormick2001
