### ISSUE TITLE
documentation updates

### ISSUE THREAD

**Issue by cahoonpwork** [CrunchyData/crunchy-containers#648]
While reviewing the official documentation for container specifications I noticed several minor issues that need to be updated:
Crunchy-pgpool: has "can only have" should be "only has"
Crunchy-pgadmin4: package references crunchy-pgrestore image name instead of crunchy-pgadmin4
Crunchy-sim: package references crunchy-pgrestore image name instead of crunchy-pgadmin4

Architecture Diagram needs the following updates:
Crunchy-dump needs to be relabeled to match container name of crunchy-pgdump
Crunchy-restore needs to be relabeled to match container name of crunchy-pgrestore

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by xenophenes** [comment]
This issue is resolved with my latest PR. The only thing not *fully* addressed:

> Crunchy-pgpool: has "can only have" should be "only has"

The previous noun is plural (applications), so I corrected it to "only have" and just removed the "can" for better readability.
