### ISSUE TITLE
PostgreSQLDetails dashboard not working in grafana image 1.8.3

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/crunchy-containers#649]
**I'm submitting a ...**

 
 - [ x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I see the following error message when using PostgreSQLDetails dashboard
**Templating init failed
Internal server error****

**If the current behavior is a bug, please provide the steps to reproduce:**
I have used metrics example and set it up on tectonic sandbox. 
My metrics pod contains the prometheus and grafana containers with the following images

crunchydata/crunchy-grafana centos7-10.4-1.8.3
crunchydata/crunchy-prometheus centos7-10.4-1.8.3

**What is the expected behavior?**
Dashboard loads properly and displays graphs in the panels.

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
CentOS-7 in container.

 - Container Image Tag:
crunchydata/crunchy-grafana centos7-10.4-1.8.3
crunchydata/crunchy-prometheus centos7-10.4-1.8.3

 - PostgreSQL Version:
10.4
 - Platform (Docker, Kubernetes, OpenShift):
Kubernetes
 - Platform Version:
1.8.7-tectonic.2

**Comment by jmccormick2001** [comment]
Val/Sarah, can you verify this is a bug, please test on Kube not tectonic as the initial test.

**Comment by xenophenes** [comment]
@jmccormick2001 on a new setup/VM, 

- OpenShift
- CentOS 7
- HostPath

built new images, ran the metrics example, was able to successfully reach PostgreSQLDetails in Grafana with no issues. would you prefer I test this from Tectonic to see if it's OS-specific?

**Comment by jmccormick2001** [comment]
questions to help me understand the bug, is promethueus working?  is it collecting the metrics ok?  is this bug just related to grafana?  what is the persistence type being used?  Does grafana work wth a custom query/graph when not using the default dashboard?

**Comment by pmereddy1** [comment]
tectonic prometheus uses different labels and this is causing the dashboard "PostgreSQL Details" to fail during initialization. 
After i re-created the template variables with correct values, the dashboard is working.
