### ISSUE TITLE
evaluate alternative proxies for pgadmin4 container

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#660]
see if apache can be replaced with something more stable and maybe smaller in footprint, recommend a better alternative for proxying to pgadmin4, needs to support TLS similar to what currently apache is doing.

 
 - [ ] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by flamingdumpster** [comment]
Looking at using something like HAProxy as its pretty easy to setup in a container to terminate ssl.

**Comment by jasonodonnell** [comment]
Biggest thing to keep in mind is the deescalation model we use - i.e the container doesn't run as the root user.

**Comment by flamingdumpster** [comment]
It is possible to bind with escalated privilege (for ports < 1024 ) and then de-escalate so haproxy itself runs as non-root user...but thats done only if you need to proxy a port < 1024. If not, then its not run in an escalated state.

**Comment by flamingdumpster** [comment]
Opened issue 3543 with pgAdmin team as it appears this is a problem internal to the pgAdmin server. After some number of login page requests, the application starts producing an Internal Server Error (500).

https://redmine.postgresql.org/issues/3543
