### ISSUE TITLE
Update DockerHub Documentation

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#663]
The [DockerHub documentation](https://hub.docker.com/u/crunchydata/) was refactored prior to our official documentation website.  These READMEs should point to the container definition and examples in our source control so we don't have to continually update these docs outside of source control.

**Comment by xenophenes** [comment]
Just need some clarification - what are you looking for?

1) The entire DockerHub documentation for each container replaced with a link to the official documentation, or

2) Update the DockerHub documentation and point the links in the following section to the new anchors:

> More Examples
> For more examples, see the official Crunchy Containers GitHub repository.

**Comment by jasonodonnell** [comment]
@xenophenes I would just keep the general description on each doc and point to our official documentation for relevant examples for that image.  Mostly trying to stop us from having to maintain multiple sources of documentation.

**Comment by xenophenes** [comment]
@jmccormick2001 @cahoonpwork This should be ready to close.
