### ISSUE TITLE
Update ocp-templates

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#666]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the motivation or use case for changing the behavior?**

The ocp-templates folder will need to be tested and updated with the latest 2.0 images after release.

**Comment by jmccormick2001** [comment]
we removed the ocp-templates from the public repo.
