### ISSUE TITLE
Update Helm charts

### ISSUE THREAD

**Issue by xenophenes** [CrunchyData/crunchy-containers#667]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the motivation or use case for changing the behavior?**

The Helm folder will need to be tested and updated with the latest 2.0 images after release.

**Comment by cahoonpwork** [comment]
Closing issue as they have been updated in 2.2.0 release.
