### ISSUE TITLE
single deployment config for master and slaves

### ISSUE THREAD

**Issue by fer-marino** [CrunchyData/crunchy-containers#68]
Hi,
I'm playing for a while with your container and I quite like it, anyway there is something that still bother me on how you handle master-slave streaming replication in your openshift examples.

I would simply use a single deployment config for all postgres instances, and then decide in the startup script if it is a master or a slave using a simple master election algorithm (lowest ip for example).
This would give me the power of deployment config which are much more flexible than a static pod.
I would use a similar mechanism in pgpool to discover all the running instances of a service and configure them.

To do so you would need to use kubernetes api to discover the available instances:

       POSTGRES_HOST=$(curl -s --cacert ${CRT_PATH} -H "Authorization:Bearer $(cat ${TOKEN_PATH})" https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/${API_PATH} | jq -r '.subsets[].addresses[].ip' | grep -v -e "^${MY_HOST}$") ;

If they are not yet ready (readyness probe return false) then the ip are in `.subsets[].notReadyAddresses[].ip` .

The user shall also have permission to query kubernetes:

      oc policy add-role-to-user view system:serviceaccount:myproject:default

Some more thought are needed to cover all the cases, anyway I'm wondering why you didn't go with this solution from the beginning, as it looks to me that kubernetes/openshift enforce this approach for easier scaling and lifecycle control. 

regards,
Fernando

**Comment by jmccormick2001** [comment]
thanks Fernando,

subsets and even service accounts and petsets too were not around when I initially wrote some of this, and  given that postgres can't scale masters I found it easier to implement them in separate pods.  I also use a master service and a replica service to front the cluster.  When I create the master, it is labeled to match the master service, the replicas are labeled to use the replica service.

but you are onto a good idea and I've been thinking about other alternatives...some have suggested I incorporate my own etcd within the containers and they form consensus using that, but I like the IP address idea you suggested.

One complication is that I'm finding some users want to place the master on a specific node
and use labels to constrain that placement.  That goes against the idea that all containers are the 
same, so I'm still thinking about what is possible here and also weighing what new features 
are coming down from Kube that I can take advantage of.

I'll definitely give this some thought, thanks for the ideas.

**Comment by jmccormick2001** [comment]
I've been thinking this weekend about your ideas on how a single deployment would work, I don't think it will be that much code to implement this and will work on a prototype of it, I'll make it an optional form of deployment to also support the current style of deployment.  With crunchy-watch, I already change the labels on a node to make it become a master so this should be pretty straightforward to do in this case.  I'll try to get this into the next release (1.2.7).

**Comment by fer-marino** [comment]
Hi, 
thank you for your answer. I've actually already done something myself:

    function master_discovery() {
        TOKEN_PATH="/var/run/secrets/kubernetes.io/serviceaccount/token";
        CRT_PATH="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt";
        # PG_SERVICE is a new env variable that holds the postgres service name
        API_PATH="api/v1/namespaces/${OPENSHIFT_BUILD_NAMESPACE}/endpoints/${PG_SERVICE}";
        MYIP=$(ip a | grep inet[^6] | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | egrep -v '127.0.0.1');
    
        PG_MODE='master';
        PG_MASTER_HOST=${MYIP};
    
        HOSTS_READY=$(curl -s --cacert ${CRT_PATH} -H "Authorization:Bearer $(cat ${TOKEN_PATH})" https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/${API_PATH} | jq -r '.subsets[].addresses[].ip') ;
        HOSTS_NOTREADY=$(curl -s --cacert ${CRT_PATH} -H "Authorization:Bearer $(cat ${TOKEN_PATH})" https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}/${API_PATH} | jq -r '.subsets[].notReadyAddresses[].ip') ;
        HOSTS_READY=(${HOSTS_READY// / });
        HOSTS_NOTREADY=(${HOSTS_NOTREADY// / });
    
        if [ -n "$HOSTS_READY" ] && [ ${#HOSTS_READY[@]} -gt 0 ]; then
            # one of them is the master. Look for it with `select pg_is_in_recovery()`
            echo "Discovering master...";
            export PGPASSWORD=${PG_MASTER_PASSWORD};
            for host in "${HOSTS_READY[@]}"
            do
               IS_SLAVE=$(psql -h ${host} -U ${PG_MASTER_USER} -d ${PG_DATABASE} -c 'SELECT pg_is_in_recovery()' | head -n3 | tail -n1);
               if [[ ${IS_SLAVE} == ' f' ]]; then
                    PG_MASTER_HOST=${host};
                    PG_MODE='slave';
                    echo "Master found: ${PG_MASTER_HOST}";
                    break;
               fi;
            done
        else
            if [ -n "$HOSTS_NOTREADY" ] && [ ${#HOSTS_NOTREADY[@]} -gt 0 ]; then
                echo "Master election...";
                for host in "${HOSTS_NOTREADY[@]}"
                do
                    if [[ ${host} < ${PG_MASTER_HOST} ]]; then
                        PG_MASTER_HOST=${host};
                    fi;
                done
                echo "Master elected as ${PG_MASTER_HOST}";
                if [[ ${MYIP} == ${PG_MASTER_HOST} ]]; then
                    PG_MODE='master';
                else
                    PG_MODE='slave';
                fi;
            fi;
        fi;
    }

I call this function in the start script of the postgres container. It basically set PG_MODE and PG_MASTER_HOST. To do that it uses two variables: OPENSHIFT_BUILD_NAMESPACE, which is specific to openshift and contains the current namespace, and PG_SERVICE, which is the name of the associated headless service used for discovery. You can call this code if PG_MODE is not set to keep backward compatibility. What you might want to do is not relying on openshift specific variables, and maybe add an error message in case the user forgot to add the view authorization to the service account.

Currently I'm working on the pgpool container. I want to make it so he knows all the running pods and not just the service name for master and slave. I also want pgpool admin installed, and I found that having a apache+php running on openshift quite tricky :(

Regards,
Fernando

**Comment by jmccormick2001** [comment]
I had some luck this week building a statefulset example that provides the clustering in a similar style to your example.  I use the ordinal value of the set to discover who should become the master.  I use PG_MODE=set as a value to indicate the deployment is within a statefulset.  I include the kubectl and oc commands within the postgres container to change the label on the master pod.  The example for this is in the examples/kube/statefulset directory.  Once I have this working for openshift, I'll add the same example there.  Thanks for your input on this, it really helped shape what I came up with.  regards.

**Comment by jmccormick2001** [comment]
the next Origin release will be rebased on Kube 1.5, at that point I'll create a similar example that runs in Origin, apparently Openshift 3.5 is slated to be based on Kube 1.5 and is expected this summer.
