### ISSUE TITLE
CUSTOM_OPTS envs cannot use quotes

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#701]
BADGER_CUSTOM_OPTS and BACKREST_CUSTOM_OPTS allow users to inject custom parameters, however, bash does not like when quotes are in these variables.

We need to either find a work around or change how we approach these.

**Comment by cdave-git-zz** [comment]
This is Important to be able to use of PITR capabilities.

**Comment by cahoonpwork** [comment]
This was completed in milestone 2.1.0 while working another issues.

**Comment by jasonodonnell** [comment]
There's still work to be done on this one (badger prefix flag)
