### ISSUE TITLE
missing required environment variable PG_PRIMARY_PORT in official documentation

### ISSUE THREAD

**Issue by hitech73** [CrunchyData/crunchy-containers#706]
**I'm submitting a ...**

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**What is the current behavior?**
missing documentation

**If the current behavior is a bug, please provide the steps to reproduce:**
when you start up a crunchydata/crunchy-postgres container it fails to run with error PG_PRIMARY_PORT environment variable is not set. When set it starts. So this variable should be part of the required environment variables in the official documentation

**Comment by cahoonpwork** [comment]
@hitech73  Can you provide the error message you get?   You shouldn't have to set an environment variable for the Port for that example.

**Comment by hitech73** [comment]
My crunchy-postgres pod has an Error in the minishift gui.
When I look at the logs for that pod there is an error :

Thu Jul 26 17:13:55 UTC 2018 ERROR: PG_PRIMARY_PORT environment variable is not set, aborting.

**Comment by cahoonpwork** [comment]
@ValClarkson  Please verify in OCP.

**Comment by ValClarkson** [comment]
I ran the crunchy-postgres container out on ocp using the primary example.  it worked fine b/c we have the port set.  we need to document PG_PRIMARY_PORT as a requirement

**Comment by cahoonpwork** [comment]
fixed in PR #709
