### ISSUE TITLE
Question on initdb in crunchy

### ISSUE THREAD

**Issue by mornindew** [CrunchyData/crunchy-containers#727]
**I'm submitting a question**

 
 - [ ] bug report
 - [ ] feature request
 - [ x] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

I am using "crunchydata/crunchy-postgres:centos7-10.3-1.8.2" in kubernetes.   Everytime a pod is started it will create a new data_directory (e.g. /data/db-5f97d6b77-f5hrg) and not recognize the already created one (mounted from a PersistentVolume).   I assume this is due to the initdb.  Is it possible to configure it to pick up the existing data file if it already exists?

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

I would expect that it sees a database already there and doesn't create a whole new one.

**What is the motivation or use case for changing the behavior?**

Allows me to have a mounted persistent volume and if I have to restart the pod then data is maintained.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
 - Container Image Tag: crunchydata/crunchy-postgres:centos7-10.3-1.8.2
 - PostgreSQL Version: 
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version:

**Comment by jmccormick2001** [comment]
I think you will want to use the PGDATA_PATH_OVERRIDE env var in the resource definition, this way you can specify a fixed name, like mydatabase, which will cause the container to create and look for a /pgdata/mydatabase, whether or not its running as a pod from a Deployment, ReplicaSet, or other controller.
