### ISSUE TITLE
Example documentation restructure

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#733]
I'd like to propose to change the way we do example documentation.  The current example doc resides in a giant file in the `hugo` directory.  This has several disadvantages:

* This file changes a lot which is prone to merge conflicts (we have lost doc this way)
* It's separated from the actual examples, which makes it an afterthought and hard to keep updated
* In our rendered documentation webpage, the only way you can drill down is via the generated TOC at the top of the page, instead of having drop downs on the menu.

In my opinion, we should put a README in every single example folder and have hugo pull in all the files and generate the doc.  This has several advantages:

* The doc is closer to the example, which makes it easier to change when you update an example
* Doc for changes in examples are a lot less likely to merge conflict since each example has its own doc
* There's no need for an example doc that blends both docker and kube examples - by having the example doc separated we can grab them and make distinct sections for each of the platforms: `Getting Started->Docker->pgBouncer` and `Getting Started->Kube/OCP->pgBouncer`.  This let's users drill down faster via the menu rather then opening a giant document page
* Faster load times: you only have to download the document page you want rather then a massive page

Additionally, we should move to using markdown instead of adoc.  Although we generate the webpage, when users open the example directories in GitHub, the documentation will also be there for users to understand the example.

**Comment by cahoonpwork** [comment]
documentation has been restructured.
