### ISSUE TITLE
Postgresql pgcrypto extension

### ISSUE THREAD

**Issue by kkalugerov** [CrunchyData/crunchy-containers#741]
Is there a way to add `pgcrypto` extension to postgresql 10 image which have integrated `postgis ` extension :?

**Comment by jasonodonnell** [comment]
@kkalugerov `pgcrypto` is a part of contrib, which is [already installed](https://github.com/CrunchyData/crunchy-containers/blob/develop/centos7/10/Dockerfile.postgres-gis.centos7#L30).

```bash
[~/postgres-gis] psql -U postgres -d postgres -h 0.0.0.0 -p 5432 \
    -x -c "SELECT * FROM pg_available_extensions WHERE name = 'pgcrypto'"
-[ RECORD 1 ]-----+------------------------
name              | pgcrypto
default_version   | 1.3
installed_version |
comment           | cryptographic functions
````

```bash
[~/postgres-gis] psql -U postgres -d postgres -h 0.0.0.0 -p 5432 \
    -x -c "CREATE EXTENSION pgcrypto"
CREATE EXTENSION
```

**Comment by kkalugerov** [comment]
Yes, I know how to install the extension but is there a way to be a global for all users ? Also would like to ask is there a way to create superuser like `postgres` without connecting to database ?

**Comment by jasonodonnell** [comment]
@kkalugerov Extensions are only available in the database you install them in (my above example, that would be `postgres` db).  As a regular user, I can use the functions provided by pgcrypto in that database without alteration:

```bash
[~/postgres-gis] psql -U testuser -d postgres -h 0.0.0.0 -p 5432 /
    -x -c "select crypt('12345', gen_salt('bf', 8));"
Password for user testuser:
-[ RECORD 1 ]-------------------------------------------------------
crypt | $2a$08$ZdcchvqBTWuXG7P3gMIxquB9PycF3wcD4srbNZ3oc1yup1afugB4e
```

As for creating a superuser without connecting, during the creation of the container you can mount a `setup.sql` file to `/pgconf` to run custom SQL.

See these examples for custom configuration:
- [Kube](https://github.com/CrunchyData/crunchy-containers/tree/develop/examples/kube/custom-config)
- [Docker](https://github.com/CrunchyData/crunchy-containers/tree/develop/examples/docker/custom-config)
- [Container documentation](https://crunchydata.github.io/crunchy-containers/container-specifications/crunchy-postgres-gis/#custom-configuration)

**Comment by kkalugerov** [comment]
Ok thanks , also can you tell me please how can I use modified file by me like `pg_hba.conf` ( I add one more condition inside it ) which you copy in `/opt/cpm/conf` while building the image :? If I build new image with modified config file and the run the master database and go inside the container and `cat` this particular config file it still shows me outdated configuration not the new one :? Any help ??

**Comment by jasonodonnell** [comment]
@kkalugerov No need to edit the image.  Same as `setup.sql`, just mount a modified version to `/pgconf`.  Unlike `setup.sql`, though, this file will always be applied during every start of the container.

You can see in the `configs` directory of the following example that `pg_hba.conf` is one of the mounted custom configuration files: 

- [Docker](https://github.com/CrunchyData/crunchy-containers/tree/develop/examples/docker/custom-config)

```bash
[~/Git/crunchy-containers/examples/docker/custom-config] cat configs/pg_hba.conf
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5
host    replication     primaryuser     0.0.0.0/0               md5
host    all             kkalugerov      192.168.1.50/32         md5
```

```bash
[~/Git/crunchy-containers/examples/docker/custom-config] docker exec -ti \
    custom-config cat /pgdata/custom-config/pg_hba.conf
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            md5
host    all             all             0.0.0.0/0               md5
host    replication     primaryuser     0.0.0.0/0               md5
host    all             kkalugerov      192.168.1.50/32         md5
```

**Comment by kkalugerov** [comment]
Is there a way to make all of this files :
ADD bin/postgres /opt/cpm/bin
ADD bin/postgres-gis /opt/cpm/bin
ADD bin/common /opt/cpm/bin
ADD conf/postgres /opt/cpm/conf
to be main configuration files while building the image and running it ?
Because when I modified them it seems like those changes got no effect when building the image and cannot be used after that..

**Comment by kkalugerov** [comment]
Even if I remove the creation of `testable` from both files `postgres/setup.sql` and `posgres-gis/setup.sql` it does not take effect on newly built image. Can you explain me how can I use modified configuration files like mentioned ones while build the image :?

**Comment by jasonodonnell** [comment]
@kkalugerov Two things come to mind:

* you might be hitting the docker cache, try a build with the `--no-cache` flag: `docker build -- no-cache`
* if you are mounting a volume that postgres was initialized on already, `setup.sql` will not run.   Try without volumes mounted

**Comment by kkalugerov** [comment]
Finally I did it ! Thanks a lot for your time !
