### ISSUE TITLE
Being able to search for 2 letter terms on the docs like oc and pv.

### ISSUE THREAD

**Issue by scrummyin** [CrunchyData/crunchy-containers#748]
**I'm submitting a feature request.**

 
 - [ ] bug report
 - [x] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Searching for 2 letter terms like `pv` or `oc` on the documentation will not return any results.

**If the current behavior is a bug, please provide the steps to reproduce:**
1.) Put `pv` or `oc` into the search box on the documentation page. 
1.) Wait... (nothing will popup)
1.) Hit ENTER (nothing will happen)

NOTE: You can work around this by adding a space so `pv ` and `oc ` work, but this is not intuitive.

**What is the expected behavior?**
That either enter will force the search for those terms or 2 letters will lookup the term placed in the bar.

**What is the motivation or use case for changing the behavior?**
I need to currently open all pages of the docs and search manually to make sure I did not miss any commands around those terms. This does not always work correctly since sometimes those are in collapsed boxes.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
Not sure it will be fixable because it might be an inherited hugo problem.

**Comment by cahoonpwork** [comment]
Integrate Docsearch as the new search tool:

https://community.algolia.com/docsearch/

**Comment by xenophenes** [comment]
I applied for the Docsearch JavaScript snippet (filled out the form with the documentation URL and my email after ensuring we met the checklist requirements). It apparently can take "up to a few days" to receive the snippet of code for this, as their software needs to crawl the website.

**Comment by cahoonpwork** [comment]
on hold for upcoming documentation solution.

**Comment by cahoonpwork** [comment]
This will be handled in the new documentation solution with that is being worked.
