### ISSUE TITLE
Add NSS_WRAPPER envs to all images

### ISSUE THREAD

**Issue by jasonodonnell** [CrunchyData/crunchy-containers#749]
To support OpenShift we require NSS_WRAPPER to override PAM with the random UID for the container user. 

Today if you do an exec command against a pod in OpenShift using a binary that is sensitive to permissions (ex: backrest), it's required to set the `NSS_WRAPPER` flags so that backrest understands the UID assigned to the container.  We export these variables in our scripts, however, scripts run in their own session and exec cannot see them.  This makes exec commands a lot more complicated (ex: [test-harness backups](https://github.com/CrunchyData/crunchy-containers/blob/develop/tools/test-harness/backrest_test.go#L30-L33))

To combat this we need to put the following entry into every Dockerfile:

```Dockerfile
ENV LD_PRELOAD="/usr/lib64/libnss_wrapper.so" \
    NSS_WRAPPER_PASSWD="/tmp/passwd" \
    NSS_WRAPPER_GROUP="/tmp/group"
```

**Comment by jasonodonnell** [comment]
A good way to test if this worked would be to run the following command against an OpenShift deployed PostgreSQL pod with backrest enabled:

```bash
oc exec -ti <mypod> -- pgbackrest --stanza=db backup
```

**Comment by jmccormick2001** [comment]
export PATH=/usr/pgsql-9.*/bin:/opt/cpm/bin:$PATH
export LD_LIBRARY_PATH=/usr/pgsql-9.*/lib

please verify those lines are not needed by anything in the .bashrc conf file, if needed still, clearly its not correct for PG 10, if not needed, please remove.

**Comment by jasonodonnell** [comment]
We'll definitely want the binaries to be in path (probably makes sense in dockerfile), but should be smarter then this.

Ex:
```bash
export PGROOT=$(find /usr/ -type d -name 'pgsql-*')
export PATH=/opt/cpm/bin:$PGROOT/bin:$PATH
```

Having the binaries in path makes exec easier (think about things like psql and pgbench).

`LD_LIBRARY_PATH` is important for PostGIS, but I'm unsure if it'll effect the end user after its already been installed.  I can't think of any exec issues we might run into here.  It certainly needs to be set prior to us running `CREATE EXTENSION postgis`
