### ISSUE TITLE
Issue with setup on docker swarm, is the server running locally and accepting connections?

### ISSUE THREAD

**Issue by ziedbf** [CrunchyData/crunchy-containers#751]
First thanks for the amazing setup of containerized postgres instances. I am working on setting up cluster on the top of docker swarm and i found the following examples very helpful https://info.crunchydata.com/blog/easy-postgresql-cluster-recipe-using-docker-1.12

I setup a docker swarm cluster on top of gcloud and managed to get the different servivce up and running by executing the following commands:
 
1. primary service: 
`docker service create --mount type=volume,src=pg-primary-vol,dst=/pgdata,volume-driver=local  --name primary --network locations --constraint 'node.labels.type == primary' --env PG_HOST=/tmp --env MAX_CONNECTIONS=10 --env MAX_WAL_SENDERS=5 --env PG_MODE=primary --env PG_PRIMARY_USER=primaryuser --env PG_PRIMARY_PASSWORD=primarypassword --env PG_DATABASE=falcon --env PG_USER=testuser --env PG_PASSWORD=testpassword --env PG_ROOT_PASSWORD=testpassword --env PG_PRIMARY_PORT=5432  crunchydata/crunchy-postgres:centos7-10.3-1.8.2`

2. replica service: 
`docker service create --mount type=volume,src=pg-replica-vol,dst=/pgdata,volume-driver=local  --name replica --network locations --constraint 'node.labels.type != primary' --env PG_HOST=/tmp --env MAX_CONNECTIONS=10 --env MAX_WAL_SENDERS=5 --env PG_MODE=replica  --env PG_PRIMARY_HOST=primary --env PG_PRIMARY_USER=primaryuser --env PG_PRIMARY_PASSWORD=primarypassword --env PG_DATABASE=falcon --env PG_USER=testuser --env PG_PASSWORD=testpassword --env PG_ROOT_PASSWORD=testpassword --env PG_PRIMARY_PORT=5432  crunchydata/crunchy-postgres:centos7-10.3-1.8.2`

but when i try to execute and test the configuration by connecting to docker instance to execute the replication test i got the following error:

```
root@swarm-worker-1:/home/zied# docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
4b2427429ab1        crunchydata/crunchy-postgres:centos7-10.3-1.8.2   "/opt/cpm/bin/start.s"   24 minutes ago      Up 24 minutes       5432/tcp            primary.1.6kfaea68y2ojjje2uzugnaoft
root@swarm-worker-1:/home/zied# docker exec -it 4b2427429ab1 /bin/bash
bash-4.2$ psql -U postgres -W                                                                                                                                                                                  
Password for user postgres: 
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

I tried to proceed further but i really have no clue as i am new to both docker swarm and postgres areas

**Comment by jasonodonnell** [comment]
You are trying to connect locally, so `psql` is looking for the unix socket to do that.  We don't use the standard location, so you need to specify it as a host: ` psql -U postgres -h /tmp -W`

For a more permanent solution so you don't need to specify this in every call, you can set the `PGHOST=/tmp` env on your Docker deployment.

Hope that helps.

**Comment by ziedbf** [comment]
Thanks @jasonodonnell what a stupid mistake i made by specifying `PG_HOST` instead of `PGHOST`. Thanks for the amazing work made by crunchyData
