### ISSUE TITLE
Kubernetes Statefulset with watcher creates duplicate Primary Pod

### ISSUE THREAD

**Issue by Seeron** [CrunchyData/crunchy-containers#755]
- [x] bug report
 - [ ] feature request
 - [ ] support request

Good day,

i currently try to set up crunchy in a kubernetes cluster, using the statefulset example and watcher. 

**What is the current behavior?**
I start up both examples, the database starts up as intended, with statefulset-0 as primary, and the healthchecks of watcher work. If I now kill the pod statefulset-0, watcher detects it and sets statefulset-1 as the new primary. The problem comes when statefulset-0 is restarted by kubernetes, because it also restarts as a primary. 

**If the current behavior is a bug, please provide the steps to reproduce:**

kubectl create -f examples/kube/statefulset/
kubectl create -f examples/kube/watch
<Wait for pods to start>
kubectl delete po statefulset-0

**What is the expected behavior?**
Either statefulset-1 should be demoted to replica or statefulset-0 should restart as replica to prevent duplicate primaries.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Container Image Tag: crunchy-watch:centos7-10.5-2.1.0 crunchy-postgres:centos7-10.5-2.1.0
 - PostgreSQL Version: 10.5
 - Platform (Docker, Kubernetes, OpenShift): Kubernetes
 - Platform Version: 1.9.9

**Comment by jmccormick2001** [comment]
yeah, crunchy-watch doesn't currently work with StatefulSets, only Pods.  There is a version about to be pushed that lets it work with Deployments, maybe 1 or 2 weeks away.  crunchy-watch only works with a primary (pod) and a replica (pod).  or with the upcoming version, primary (deployment), and a replica (deployment).  Hope that helps clarify its usage.

**Comment by jmccormick2001** [comment]
take a look at our crunchy postgres operator project 

github.com/crunchydata/postgres-operator

it handles a lot of things you would have to create for yourself using just the crunchy containers microservices.

cheers.
