### ISSUE TITLE
PostgreSQL readiness probe cannot connect

### ISSUE THREAD

**Issue by Driste** [CrunchyData/crunchy-containers#766]
**I'm submitting a ...**

 
 - [ ] bug report
 - [ ] feature request
 - [x] support request

**Do you want to request a *feature* or report a *bug*?**

Not sure what this could be considered. I believe this could possibly be a support request because the liveliness and readiness probes differ. This may be intentional, and I am just doing something wrong.

**What is the current behavior?**

The [PostgreSQL Readiness Probe](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/readiness.sh) will fail because it is looking for the unix socket in a different location than what is configured.

```
Wed Sep 26 17:56:10 UTC 2018 INFO: Setting PGROOT to /usr/pgsql-9.5.
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
```

**If the current behavior is a bug, please provide the steps to reproduce:**

1. Make sure `postgresql.conf` is set with the current configuration:
```
unix_socket_directories = '/tmp'
```
2. Run `/opt/cpm/bin/readiness.sh`

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

I cannot change the location of the unix socket to `/var/run/postgresql/` because of the current permissions in the container.

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

Change the [Readiness Probe](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/readiness.sh) to use the `-h` (host) flag like the [Liveness Probe](https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/liveness.sh)
```bash
# Current:
$PGROOT/bin/psql -f /opt/cpm/bin/readiness.sql -U $PG_USER postgres

# Proposed:
$PGROOT/bin/psql -h $HOSTNAME -f /opt/cpm/bin/readiness.sql -U $PG_USER postgres

# Or if we want to continue to use UNIX sockets
$UNIX_SOCKET_DIRECTORY = '/tmp'
# postgresql.conf
unix_socket_directories = UNIX_SOCKET_DIRECTORY
# readiness.sh
$PGROOT/bin/psql -h $UNIX_SOCKET_DIRECTORY -f /opt/cpm/bin/readiness.sql -U $PG_USER postgres
```

**Please tell us about your environment:**

 - Operating System: RHEL
 - Container Image Tag: crunchy-postgres:centos7-9.5.14-2.1.0
 - PostgreSQL Version: 9.5
 - Platform (Docker, Kubernetes, OpenShift): Openshift
 - Platform Version: v3.9

**Comment by jasonodonnell** [comment]
Hi @Driste, set the `PGHOST=/tmp` environment variable on the PostgreSQL pod.

**Comment by Driste** [comment]
Thank-you! Was overthinking it. lol
