### ISSUE TITLE
add backoff limit to example jobs

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#771]
add backoff limit to all job examples and configuration templates that specify a job (e.g. scheduler)

.spec.backoffLimit

"backoffLimit": 0

set to a value of 0 meaning no restarts will be performed if the container fails for some reason.

 
 - [ ] bug report
 - [x ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by cahoonpwork** [comment]
fixed in 2.3.1
