### ISSUE TITLE
add templates to openshift community template project

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#79]
see about adding our templates here

https://github.com/openshift/library#community

**Comment by manuelep** [comment]
would it be possible to easily use your template for installing a postgis image under an openshift project? How?

I tried the command:

```
oc new-app --docker-image=rhel7/9.6/Dockerfile.postgres-gis.rhel7 https://github.com/CrunchyData/crunchy-containers.git
```

without success obtaining the sequent output

```log
error: no match for "rhel7/9.6/Dockerfile.postgres-gis.rhel7"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
```

**Comment by jmccormick2001** [comment]
crunchy-containers/examples/templates/single-master

check out that template example, if you replace the image name in master.json with crunchy-postgres-gis instead of crunchy-postgres and use this image tag:  centos7-9.6-1.5.1

it should be a step in the right direction I think for what you want.

if you execute that example's run.sh script it will load the template into your openshift.

**Comment by manuelep** [comment]
Thank you Jeff,
I successfully installed the database but it seams inactive and the only message I obtain is a warning like this:

> The pod has been stuck in the pending state for more than five minutes.

It seams to have problems creating the container. I found this message under `Pods >> pgdatabase -> Logs` but no better or more detailed log I found:

> Container: pgdatabase — Create container error 

I just:
* assigned the right tag

    ```
    export CCP_IMAGE_TAG=centos7-9.6-1.5.1
    ```

* exported needed variables

    ```
    source examples/envvars.sh
    ```

* login into my account

    ```
    oc login https://api.pro-us-east-1.openshift.com --token=<my-token>
    ```

* edited the template configuration

    ```diff
    diff --git a/examples/templates/single-master/master.json b/examples/templates/single-master/master.json
    index 9c5aa4d..3a3afae 100644
    --- a/examples/templates/single-master/master.json
    +++ b/examples/templates/single-master/master.json
    @@ -2,7 +2,7 @@
         "kind": "Template",
         "apiVersion": "v1",
         "metadata": {
    -        "name": "crunchy-postgres-database-emptydir",
    +        "name": "crunchy-postgres-database",
             "creationTimestamp": null,
             "annotations": {
                 "description": "Crunchy PostgreSQL Single Database using EmptyDir",
    @@ -20,7 +20,7 @@
             "value": "master"
         }, {
             "name": "CCP_IMAGE_TAG",
    -        "value": "centos7-9.5-1.2.7",
    +        "value": "centos7-9.6-1.5.1",
             "description": "The image tag to pull with"
         }, {
             "name": "CCP_IMAGE_PREFIX",
    @@ -86,7 +86,7 @@
             "spec": {
                 "containers": [{
                     "name": "${SERVICE_NAME}",
    -                "image": "${CCP_IMAGE_PREFIX}/crunchy-postgres:${CCP_IMAGE_TAG}",
    +                "image": "${CCP_IMAGE_PREFIX}/crunchy-postgres-gis:${CCP_IMAGE_TAG}",
                    "imagePullPolicy": "IfNotPresent",
                     "readinessProbe": {
                         "exec": {
    ```


* created the template

    ```
    oc create -f examples/templates/single-master/master.json
    ```

* used the new template adding it to my project through the web gui

    ```
    add to project -> Browse catalog -> Data stores -> crunchy-postgres-database
    ```

    changing the environment variable values adapting them to my needs...

Is there something else to do?

Cheers
    Manuele

**Comment by manuelep** [comment]
Reading the [log](http://paste.debian.net/985094/) obtained with `oc get all -o json -n <namespace>` I can see that the container cannot be created because of permissions:

```json
{
    "image": "crunchydata/crunchy-postgres-gis:centos7-9.6-1.5.1",
    "imageID": "",
    "lastState": {},
    "name": "pgdatabase",
    "ready": false,
    "restartCount": 0,
    "state": {
        "waiting": {
            "message": "Error response from daemon: {\"message\":\"create 672e96643c38f418d73d7cdeefd46f6529f693a72b4bdc365a83b4de2ef9c91c: mkdir /var/lib/docker/volumes/672e96643c38f418d73d7cdeefd46f6529f693a72b4bdc365a83b4de2ef9c91c: permission denied\"}",
            "reason": "CreateContainerError"
        }
    }
}
```

> "create 672e96643c38f418d73d7cdeefd46f6529f693a72b4bdc365a83b4de2ef9c91c: mkdir /var/lib/docker/volumes/672e96643c38f418d73d7cdeefd46f6529f693a72b4bdc365a83b4de2ef9c91c: **permission denied**"

**Comment by jmccormick2001** [comment]
strange error, it seems to be having a problem creating an emptydir volume...if you see a log from the postgres container that would be interesting to look at....with emptydir volumes like this one is using, I don't normally see a file permission error like this...if it were NFS or Gluster or other volume types, I tend to see permission errors where the Postgres container can't have write access to the provisioned volume, but this looks odd to me given that its emptyDir which should always have the correct permissions.

**Comment by manuelep** [comment]
maybe it could be useful to know that there is no persistent storage included by default with OpenShift and I didn't create one. Now I tried creating two storages (called pgdata and backup) but nothing seams change... are there any particular needed configuration about storages to keep in mind?

**Comment by jmccormick2001** [comment]
typically when using emptyDir volumes, there is nothing you need to do for the permissions to work, this is odd...I'm guessing other containers work on this openshift and persist to emptyDir just fine?

**Comment by thesteve0** [comment]
Please specify your version and which "openshift" you are using - online,
dedicated, minishift, openshift container platform...
Thanks

**Comment by manuelep** [comment]
I'm using openshift service v.3 with a [PRO account](https://www.openshift.com/pricing/index.html) offered by [www.openshift.com](https://www.openshift.com/)

**Comment by jmccormick2001** [comment]
ok, after some digging I found this:

https://bugzilla.redhat.com/show_bug.cgi?id=1456015

To test this out, I created a test Online account this morning to test it out, and indeed this Openshift environment is set up different than most.

Based on that bug information I created a PVC, which worked, and then attempted to 
use that PVC in a simple example.  Sadly even after specifying the PVC in my example, I still get that docker volume permission error so I think this is a bug in Openshift Online, or perhaps they have some workaround that I've not been able to find.  But its clearly something peculiar about the Online configuration.

**Comment by manuelep** [comment]
@jmccormick2001 Have you manually created the 6 necessary storages accordingly to the [Dockerfile VOLUME directive](https://github.com/CrunchyData/crunchy-containers/blob/master/centos7/9.6/Dockerfile.postgres-gis.centos7#L56) as I said there is no persistent storage included by default with the service offered by openshift.com. (Consider I have still to try the procedure with all the necessary storages created... I'll give you information asap)

**Comment by jmccormick2001** [comment]
ah, you are correct, forgot about the others which will default to using emptyDir which won't work on the Free Online version...with Pro you could test that out...it will probably work then if each of them have a unique PVC created.

**Comment by jmccormick2001** [comment]
ok, I've confirmed that if you specify all 6 volumes even as emptyDir that it will work.  I'll close this one out now.  They appear to lock down volume usage quite a bit in that environment.  cheers
