### ISSUE TITLE
postgres-operator on Kubernetes Cluster

### ISSUE THREAD

**Issue by nchiluku** [CrunchyData/crunchy-containers#804]
1) The problem is reproducible on single master as well as multi master Kubernetes Cluster created using Kube-spray(Standalone VM cluster). 
2) I tried setting postgres-operator using https://crunchydata.github.io/postgres-operator/stable/installation/manual-installation/. Though postgres-operator installed properly, pg-test health check fails as a result cannot connect to postgres.
NAME                                 READY     STATUS    RESTARTS   AGE
pg-test-664467cc8d-lrmnt             0/1       Running   0          1d
pg-test-pgpool-64547c847f-fbfsl      1/1       Running   0          1d
postgres-operator-77f949bf58-lv8j6   2/2       Running   0          1d

Events:
  Type     Reason     Age                  From                    Message
  ----     ------     ----                 ----                    -------
  Warning  Unhealthy  2m (x15440 over 1d)  kubelet, ****-*****  (combined from similar events): Readiness probe failed: Sun Oct 14 18:59:14 UTC 2018 INFO: Setting PGROOT to /usr/pgsql-10.
psql: could not connect to server: No such file or directory
  Is the server running locally and accepting
  connections on Unix domain socket "/tmp/.s.PGSQL.5432"?
3) Tried installing after modifying 
./src/github.com/crunchydata/postgres-operator/examples/custom-config/pg_hba.conf
and added the below:
hostnossl all            all             0.0.0.0/0               trust
host      all            all             0.0.0.0/0                trust
It did not make any difference.
4) Tried 2.6.0 version too. 
https://medium.com/@spektom/postgresql-ha-cluster-in-kubernetes-ae0dbb86a3de
Same issue, encountered same health check issues.
psql -h 127.0.0.1 -U testuser postgres
psql: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?
psql -h 127.0.0.1 -U postgres postgres
psql: could not connect to server: Connection refused
	Is the server running on host "127.0.0.1" and accepting
	TCP/IP connections on port 5432?

 
 - [x] bug report
 - [ ] feature request
 - [ ] support request

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
kubectl exec -it pg-test-664467cc8d-lrmnt /bin/bash
bash-4.2$ psql -h localhost
psql: could not connect to server: Connection refused
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?

**If the current behavior is a bug, please provide the steps to reproduce:**
Please see above.

**What is the expected behavior?**
Should connect to postgres using psql

**What is the motivation or use case for changing the behavior?**
None

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)
Doesn't work on a standalone env.

**Please tell us about your environment:**

 - Operating System:
Centos7
 - Container Image Tag:
Can reproduce on 2.7, 3.3.0 and 3.2.0
 - PostgreSQL Version:
Tried 9 and 10
 - Platform (Docker, Kubernetes, OpenShift):
kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:00:59Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
 - Platform Version:
uname -a
Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jmccormick2001** [comment]
statefulsets are not supported by the postgres-operator, it uses Deployments currently when building out PG clusters.

**Comment by nchiluku** [comment]
You misunderstood me. I only said, there is nothing wrong with these type of standalone clusters as stateful sets worked properly. This bug is all about postgres-operator health check failure and unable to connect to postgres. Please let me know, how to make it work.

**Comment by nchiluku** [comment]
> statefulsets are not supported by the postgres-operator, it uses Deployments currently when building out PG clusters.

You misunderstood me. I only said, there is nothing wrong with these type of standalone clusters as stateful sets worked properly. This bug is all about postgres-operator health check failure and unable to connect to postgres. Please let me know, how to make it work.

**Comment by jmccormick2001** [comment]
sorry, I'm not understanding, but if you feel this is a postgres-operator problem, create this issue over on that repo's Issue list and I'll take a deeper look.
