### ISSUE TITLE
A few questions about 'crunchy-watch'...

### ISSUE THREAD

**Issue by testark** [CrunchyData/crunchy-containers#81]
I'd like to ask a few questions about this particular line:

https://github.com/CrunchyData/crunchy-containers/blob/1.2.6/bin/watch/start.sh#L121

1) Is there any reason for the fixed one-minute sleep period?
2) Could this be made configurable via an environment variable?
3) What would be the consequences of setting the label right away instead of sleeping?

**Comment by jmccormick2001** [comment]
Hi,  the sleep is necessary to give some time for the postgres slave to perform the failover, this takes a few seconds....if you didn't do that sleep before the label change, it would be possible for clients to start accessing the new master before it has finished the failover procedure, this would throw errors back to the client....but you are right, it would be a good thing to have that 60 be configurable via an env var.  I'll create an issue to track it.

**Comment by jmccormick2001** [comment]
you will see WAIT_TIME added into version 1.2.7 which is about to land, with that env var you will be able to override the 60 seconds.
