### ISSUE TITLE
Please provide us necessary documents for the crunchy-backup 

### ISSUE THREAD

**Issue by uhaani** [CrunchyData/crunchy-containers#816]
** Which example are you working with? **

**What is the current behavior?**

**What is the expected behavior?**

**Other information** (e.g. detailed explanation, related issues,  etc)

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:
 kubectl describe yourPodName
 kubectl describe pvc
 kubectl get nodes
 kubectl log yourPodName

**Comment by cahoonpwork** [comment]
Here is the link to the 2.2.0 documentation which describes the backup examples:
https://crunchydata.github.io/crunchy-containers/stable/getting-started/kubernetes-and-openshift/#_backup_and_restoration

If you are looking for something else, please let us know.

**Comment by cahoonpwork** [comment]
Closing issue, let me know if you need something on this one.
