### ISSUE TITLE
crunchy-watch on docker swarm

### ISSUE THREAD

**Issue by zlatkojosic** [CrunchyData/crunchy-containers#848]
I'm trying to run crunchy-watch on docker swarm. 

Crunchy-watch service never starts. In few seconds current state has message Complete x seconds ago and DESIRED STATE has status Shutdown. There are no any error messages.

docker-compose.yml:

---
version: "3.3"

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos7-10.5-2.1.0
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=100
    - MAX_WAL_SENDERS=5
    - PG_MODE=primary
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=happysix
    - PG_USER=happysix
    - PG_PASSWORD=mypassword
    - PG_ROOT_PASSWORD=password
    - PG_PRIMARY_PORT=5432
    volumes:
    - pg-primary-vol:/pgdata
    ports:
    - "5154:5432"
    networks:
      jj-qa:
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == manager
  replica:
    image: crunchydata/crunchy-postgres:centos7-10.5-2.1.0
    environment:
    - PGHOST=/tmp
    - MAX_CONNECTIONS=100
    - MAX_WAL_SENDERS=5
    - PG_MODE=replica
    - PG_PRIMARY_HOST=primary
    - PG_PRIMARY_PORT=5432
    - PG_PRIMARY_USER=primaryuser
    - PG_PRIMARY_PASSWORD=password
    - PG_DATABASE=happysix
    - PG_USER=happysix
    - PG_PASSWORD=mypassword
    - PG_ROOT_PASSWORD=password
    volumes:
    - pg-replica-vol:/pgdata
    ports:
    - "5155:5432"
    networks:
      jj-qa:
    deploy:
      placement:
        constraints:
        - node.labels.type == primary
        - node.role == manager
  watch:
      image: crunchydata/crunchy-watch:centos7-10.5-2.1.0
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        restart_policy:
          condition: on-failure
          delay: 5s
          max_attempts: 3
          window: 120s
      environment:
        - PG_MODE=docker
        - TZ = Canada/Eastern
        - PLATFORM=docker
        - PG_PRIMARY = primary
        - PG_REPLICA = replica
        - PG_PRIMARY_PORT = 5432
        - PG_USERNAME=primaryuser
        - PG_DATABASE=happysix
        - SLEEP_TIME=20
        - FAIL_OVER_WAIT=5s
      links:
        - primary:primary
        - replica:replica
      ports:
        - 10204:5432
      #volumes:
      #  - /var/run/docker.sock:/var/run/docker.sock
      #  - $PWD/hooks:/hooks
      networks:
        jj-qa:

networks:
  jj-qa:

volumes:
  pg-primary-vol:
  pg-replica-vol:

docker service ls:

q0ut6lc35jfr        pg-stack_primary    replicated          1/1                 crunchydata/crunchy-postgres:centos7-10.5-2.1.0   *:5154->5432/tcp
op0c8c5ud6w3        pg-stack_replica    replicated          1/1                 crunchydata/crunchy-postgres:centos7-10.5-2.1.0   *:5155->5432/tcp
1rc9p47lpa47        pg-stack_watch      replicated          0/1                 crunchydata/crunchy-watch:centos7-10.5-2.1.0      *:10204->5432/tcp

docker service ps pg-stack_watch:

ID                  NAME                IMAGE                                          NODE                    DESIRED STATE       CURRENT STATE             ERROR               PORTS
cbbq2d8x9ogz        pg-stack_watch.1    crunchydata/crunchy-watch:centos7-10.5-2.1.0   linuxkit-025000000001   Shutdown            Complete 21 minutes ago   

OS: MacOs
docker version:
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

**Comment by cahoonpwork** [comment]
Crunchy Watch was deprecated starting in January 2019.
