### ISSUE TITLE
Dockerfile for crunchy-pgdump and crunchy-restore

### ISSUE THREAD

**Issue by uhaani** [CrunchyData/crunchy-containers#863]
Can  you provide the dockerfile for crunchy-pgdump and crunchy-restore ?

Which example are you working with? 
Backup and restore

**Comment by cahoonpwork** [comment]
You can find the images you are looking for on DockerHub at https://hub.docker.com/u/crunchydata/?page=2 .

**Comment by uhaani** [comment]
Dockerfile is not there at  https://hub.docker.com/u/crunchydata/?page=2 .

**Comment by cahoonpwork** [comment]
https://hub.docker.com/r/crunchydata/crunchy-pgdump/
https://hub.docker.com/r/crunchydata/crunchy-pgrestore/

If you are looking for the source for the containers it will be in the PG version you need at:
https://github.com/CrunchyData/crunchy-containers/tree/master/centos7

**Comment by cahoonpwork** [comment]
Closing as it appears you have the files you need.  If not just let us know.

**Comment by uhaani** [comment]
Yes, I got the docker file for pgdump and restore.
