### ISSUE TITLE
Failed to pull image "crunchydata/pgo-apiserver:centos7-3.4.0"

### ISSUE THREAD

**Issue by gadelkareem** [CrunchyData/crunchy-containers#874]
**Describe the bug**
Getting `Failed to pull image "crunchydata/pgo-apiserver:centos7-3.4.0": rpc error: code = Unknown desc = Error response from daemon: manifest for crunchydata/pgo-apiserver:centos7-3.4.0 not found`

Any news on crunchydata/pgo-apiserver:centos7-3.4.0?

**Comment by jmccormick2001** [comment]
its not released yet, probably out in 2 weeks is my guess.
