### ISSUE TITLE
test harness debug info

### ISSUE THREAD

**Issue by cahoonpwork** [CrunchyData/crunchy-containers#879]
**What is the motivation or use case for the change? **
If a configuration is messed up, the test harness doesn't provide a way to see the output of the error as it cleans up everything.

**Describe the solution you'd like**
Add more logging of the output.
Add add a flag to be able to disable the additional debug logging.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by jasonodonnell** [comment]
We can add a `t.Log(out)` [right here](https://github.com/CrunchyData/crunchy-containers/blob/develop/tools/test-harness/utils_test.go#L20) so all examples show the script outputs.
