### ISSUE TITLE
investigate hard-coded waits in setup script

### ISSUE THREAD

**Issue by mpalmi** [CrunchyData/crunchy-containers#88]
@jmccormick2001 one of the scripts is using hard-coded waits for replica spin-up.

> This scenario is for loading a pg_basebackup into a master-slave replication setup with the crunchy container suite... the start.sh script contained in the crunchy-postgres container has a hard coded wait time of a few seconds, as opposed to checking the status of the master before proceeding.

**Comment by jmccormick2001** [comment]
I've merged in a change to bin/postgres/start.sh to use pg_isready in a loop instead of the 
previously hard-coded sleep.  This change will land in release 1.2.9.
