### ISSUE TITLE
filesystem metrics missing for PostgreSQL volumes

### ISSUE THREAD

**Issue by pmereddy1** [CrunchyData/crunchy-containers#891]
**Describe the bug**
no node_filesystem_* metrics for PostgreSQL mount points. However the metrics are available for mounts like (/conf, /etc/hostname, /run/secrets, etc).

**To Reproduce**
Use any crunchy-collect image 10.5-2.1.0 or previous release.

**Expected behavior**
filesystem metrics available for all PostgreSQL volumes.

**Screenshots**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:
openshift 3.10+

**Additional context**

**Comment by jmccormick2001** [comment]
need /pgdata and other mounted volume stats to be picked up by crunchy-collect for metrics.

**Comment by jasonodonnell** [comment]
Will look into it, however, we disabled all filesystem graphs in Grafana because they weren't correct.
