### ISSUE TITLE
The links to documentation in the README are broken

### ISSUE THREAD

**Issue by davecramer** [CrunchyData/crunchy-containers#903]
**I'm submitting a ...**

 
 - [ x] bug report
 - [ ] feature request
 - [ ] support request

For instance the installation docs https://crunchydata.github.io/crunchy-containers/installation/

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce:**

**What is the expected behavior?**

**What is the motivation or use case for changing the behavior?**

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, etc)

**Please tell us about your environment:**

 - Operating System:
 - Container Image Tag:
 - PostgreSQL Version:
 - Platform (Docker, Kubernetes, OpenShift):
 - Platform Version:

**Comment by cahoonpwork** [comment]
This is fixed on the develop branch currently.  As the default branch is Master, it won't be updated until 2.2.0 is released.
