### ISSUE TITLE
crunchy-collect data source from secret

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#918]
in the crunchy-collect examples, you see 
an env var set up like this:

                                "name": "DATA_SOURCE_NAME",
                                "value": "postgresql://ccp_monitoring:password@127.0.0.1:5432/postgres?sslmode=disable"
     
this issue is to convert crunchy-collect to pull in the pgmonitor credential from a Secret
instead of coding it like this string.                       },

**Describe the solution you'd like**

The examples, and container docs would be updated to pull in a Secret, the Secret
would be created in the example run.sh script.

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by cahoonpwork** [comment]
scheduled for 2.4.0 tracking in clubhouse.
