### ISSUE TITLE
Pgpool load balancing

### ISSUE THREAD

**Issue by holidaycottages** [CrunchyData/crunchy-containers#922]
Hi, more of a question about setup. 

If I had pgpool running in front of a primary/replica deployment of 1 primary and say 4 replicas, and ive told pgpool the primary service and replica endpoints (as described in issue #399), does pgpool load balance across the master and the replica and then the replica load balancer balance between all the other replicas?

What I am trying to achieve is a high read throughput and also a way of monitoring all of the replicas

Is it possible to sit pgbouncer in front of pgpool?

**Comment by jasonodonnell** [comment]
@holidaycottages 

> If I had pgpool running in front of a primary/replica deployment of 1 primary and say 4 replicas, and ive told pgpool the primary service and replica endpoints (as described in issue #399), does pgpool load balance across the master and the replica and then the replica load balancer balance between all the other replicas?

This is correct, pgpool would be configured to use the services for those containers which use a round-robin balancing scheme.

> Is it possible to sit pgbouncer in front of pgpool?

I tried this and it seemed to work okay, you will need to experiment with it on your end.

**Comment by holidaycottages** [comment]
@jasonodonnell thanks, I just tried pgbouncer > pgpool, and it worked, but looked like from the stats like pgpool wasnt load balancing, it was just targeting one of the pg instances. So I am assuming that pgbouncer only created one session to pgpool and therefore didnt balance.

When i tested pgpool direct it loadbalanced fine! hmmmm

**Comment by jasonodonnell** [comment]
Ah yes, I believe this would be the case.  

One thing I could think of is putting pgbouncer infront of the PostgreSQL services, but behind pgpool.  In this case you would have a bouncer for primary/replica pools and pgpool would direct traffic to each of those.  You lose the ability to globally pause/stop/drain traffic though.

Hope that helps, just an idea might not be good :)

**Comment by holidaycottages** [comment]
@jasonodonnell good idea that, I will try it out!

**Comment by cahoonpwork** [comment]
closing as nothing new since November, if you need something else just let us know.  thanks.
