### ISSUE TITLE
Update pgpool version to 4.0.2

### ISSUE THREAD

**Issue by holidaycottages** [CrunchyData/crunchy-containers#923]
**Describe the bug**
There is a problem in pgpool where it wont authenticate using md5 and not then set the primary correctly.

Bug was reported here 
https://www.pgpool.net/mantisbt/view.php?id=446

And is solved in the latest pgpool release here: 
http://www.pgpool.net/docs/latest/en/html/release-4-0-2.html

Please may you update the docker containers ?

**Comment by cahoonpwork** [comment]
It looks like pgpool is still 4.0.1 on pdgdg, repo: https://yum.postgresql.org/9.6/redhat/rhel-7-x86_64/ 

It will get update once it is available in our release.

**Comment by holidaycottages** [comment]
Cool, I built my own image for testing and got the latest package from here

http://www.pgpool.net/yum/rpms/4.0/redhat/rhel-7-x86_64/pgpool-II-pg10-4.0.2-1pgdg.rhel7.x86_64.rpm

And it works and fixes the issue

**Comment by ops18** [comment]
Hi all

pgo create cluster test2 --replica-count=2 --pgpool

I have created a 1 master 2 replica in crunchy data (version 3.4.0) with pgpool

when i run show pool_nodes 

postgres=# show pool_nodes;


 node_id |   hostname    | port | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay | last_status_change
---------+---------------+------+--------+-----------+---------+------------+-------------------+-------------------+---------------------
 0       | test2         | 5432 | up     | 0.500000  | standby | 3          | true              | 0                 | 2018-12-05 15:23:16
 1       | test2-replica | 5432 | up     | 0.500000  | standby | 0          | false             | 0                 | 2018-12-05 15:23:16
(2 rows)


(END)
################# LOGIN VIA PGPOOL VIP #############################

when i login with pgpool vip  I am able to do Update/Insert transaction

psql -h 10.98.0.126 -p 5432 -U postgres
Password for user postgres:

psql (10.6 (Ubuntu 10.6-0ubuntu0.18.04.1))
Type "help" for help.

postgres=# show pool_nodes;
postgres=# create database test2;
CREATE DATABASE

#########################LOGIN TO REPLICA POD##############################

and when i try for manually login to replica pods 
and try to do Update/Insert 

#kubectl exec -it test2-ulhb-977f8f598-6vhj9 /bin/bash
bash-4.2$ psql
psql (10.6)
Type "help" for help.

postgres=# create database test;
ERROR:  cannot execute CREATE DATABASE in a read-only transaction
postgres=# \q
bash-4.2$ exit

#########ANOTHER REPLICA POD#####################

#kubectl exec -it test2-zwhr-7949bf4744-4rjfp /bin/bash
bash-4.2$ psql
psql (10.6)
Type "help" for help.

postgres=# drop database userdb;
ERROR:  cannot execute DROP DATABASE in a read-only transaction
postgres=#


but in show pool nodes is show 

 node_id |   hostname    | port | status | lb_weight |  role   | select_cnt | load_balance_node | replication_delay | last_status_change
---------+---------------+------+--------+-----------+---------+------------+-------------------+-------------------+---------------------
 0       | test2         | 5432 | up     | 0.500000  | standby | 3          | false             | 0                 | 2018-12-05 15:23:16
 1       | test2-replica | 5432 | up     | 0.500000  | standby | 0          | true              | 0                 | 2018-12-05 15:23:16
(2 rows)

(END)

Is it correct behavior of this pgpool .

**Comment by jmccormick2001** [comment]
this new pgpool package will be included in the next pgpool container release, mid-January.  cheers.
