### ISSUE TITLE
capability to suppress the node exporter with crunchy-collect

### ISSUE THREAD

**Issue by kssikora** [CrunchyData/crunchy-containers#929]
**What is the motivation or use case for the change? **

Some Kubernetes environments already have exporters configured and running to gather host metrics. We would like to disable the Crunchy host exporter to avoid the redundancy.

**Describe the solution you'd like**

Please provide the capability to launch the crunchy-collect container in a way that only runs the Postgres metrics exporter.

**Please tell us about your environment:**

Operating System: CoreOS
Where is this running ( Local, Cloud Provider): Local VMWare VM
Storage being used (NFS, Hostpath, Gluster, etc): NFS
Container Image Tag: centos7-10.6-2.2.0
PostgreSQL Version: 10.6
Platform (Docker, Kubernetes, OpenShift): Kubernetes
Platform Version:
Kubernetes 1.11 , Docker 18.06-CE

Additional context
Add any other context or screenshots about the enhancement request here.

**Comment by cahoonpwork** [comment]
released in 2.3.0.
