### ISSUE TITLE
refactor Dockerhub documentation

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#931]
lets go with a minimal footprint on dockerhub for documentation, instead lets refer
users to our main documentation site with a logo and link.

**Describe the solution you'd like**

**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local, Cloud Provider)
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

**Additional context**
Add any other context or screenshots about the enhancement request here.

**Comment by cahoonpwork** [comment]
descriptions updated in dockerhub.
