### ISSUE TITLE
Crunchy-watch

### ISSUE THREAD

**Issue by swati-kale** [CrunchyData/crunchy-containers#938]
** Which example are you working with? **
crunchy-watch
https://github.com/CrunchyData/crunchy-watch

**What is the current behavior?**
currently when i delete primary pod..it gets deleted and primar service is get attached with replica with help of watch. But in case if I delete the replica also then the primary will never be reached.
**What is the expected behavior?**
How to handle the situation where we can have multiple replicas taking part in  failover and can be assigned to primary when one replica gets deleted.
*Other information** (e.g. detailed explanation, related issues,  etc)
Do you have any example or solution?
**Please tell us about your environment:**

* Operating System:
* Where is this running ( Local , Cloud Provider)
Openshift
* Storage being used (NFS, Hostpath, Gluster, etc):
* Container Image Tag:
* PostgreSQL Version:
* Platform (Docker, Kubernetes, OpenShift):
* Platform Version:

If possible please run the following on the kubernetes or Openshit (oc) commands and provide the result:

1)With the example below pods were created

pod "pr-primary" created
pod "pr-replica" created
pod "pr-replica-2" created
pod "watch" created

2)  $WATCH_CLI delete pod pr-primary
failover is handled

3) $WATCH_CLI delete pod pr-replica
Could not reach 'pr-primary' (Attempt: 1)

**Comment by cahoonpwork** [comment]
Crunchy Watch was deprecated starting in January 2019. For Kube/Openshift HA/failover we recommend the Crunchy Postgres Operator project (https://github.com/crunchydata/postgres-operator.git).
