### ISSUE TITLE
make sure PG_MASTER_HOST is set when PG_MODE is slave

### ISSUE THREAD

**Issue by jmccormick2001** [CrunchyData/crunchy-containers#94]
add a check in postgres/start.sh
that when PG_MODE is slave, that PG_MASTER_HOST env var is set to a value, if not
error.

**Comment by pvacca** [comment]
Hi, Jeff, is there any reason not to solve this by adding `set -u` to the top of start.sh? This will ensure that all variables have value when they are referenced.

**Comment by jmccormick2001** [comment]
this particular variable, PG_MASTER_HOST, is only required when PG_MODE is slave so some 'if' logic is required here to present a good error message.

**Comment by jmccormick2001** [comment]
change has been merged into bin/postgres/start.sh, will land in the 1.2.9 release.
