### ISSUE TITLE
Please create a crunchy-postgresql-cluster for CoreOS

### ISSUE THREAD

**Issue by sonamsamdupkhangsar** [CrunchyData/crunchy-containers#97]
Can you create a  crunchy-postgresql-cluster for CoreOS.  

It seems like it could almost work except for a CentOS specific docker image for Postgresql in the values.yaml file (PostgresImage: crunchydata/crunchy-postgres:centos7-9.5-1.2.5)    

Any help appreciated.

**Comment by jmccormick2001** [comment]
Hi,   just wanted to clarify your question, are you wanting the 
examples/kubehelm/crunchy-postgresql-cluster example to work on a CoreOS Kubernetes cluster?
if so, what errors are you getting?

**Comment by sonamsamdupkhangsar** [comment]
I am able to run it on CoreOS now.  But when I shell into the pod it seems
to take a lot of cpu resources and then the crunchy-master and replica
instances remain in unknown states.  I think I need to figure out whys of
it.

thanks
-Sonam

**Comment by jmccormick2001** [comment]
make sure your kube DNS pod is working properly is the first thing I would check, if that is working, you could send me your logs and I'll take a look.

kubeadm15 jeffmc~]: kubectl get pod --namespace=kube-system
NAME                                READY     STATUS    RESTARTS   AGE
dummy-2088944543-nbbd2              1/1       Running   5          9d
etcd-kubeadm15                      1/1       Running   5          9d
kube-apiserver-kubeadm15            1/1       Running   5          9d
kube-controller-manager-kubeadm15   1/1       Running   5          9d
kube-discovery-1769846148-ftwn1     1/1       Running   5          9d
kube-dns-2924299975-d4smn           4/4       Running   20         9d
kube-proxy-4p8rd                    1/1       Running   5          9d
kube-scheduler-kubeadm15            1/1       Running   5          9d
weave-net-fgnwl                     2/2       Running   10         9d

you'll want to see something like that for your kube DNS pod, 4/4.

**Comment by sonamsamdupkhangsar** [comment]
I don't have a dns setup.  My setup is on DigitalOcean with CoreOS.

When I launch a springboot app with 3 replicas the master-crunchy pod
disappears after like 1 hour.  How would I relaunch the master and still
use the same data created from previous session's nfsfileserver data?

thanks
-Sonam

**Comment by jmccormick2001** [comment]
if you can send me the master pod's log I'll take a look and see what is going on.

the pod normally creates a subdirectory on the PVC that you pass to it, that subdirectory
uses the pod's hostname by default...so if the master pod is 'master', you will see
a 'master' directory on the PVC.

if a pod called 'master' starts up and sees that a directory 'master' is already there with the postgres data files it will just start up and resume working.

if the pod can't write to the PVC directory you will see 'permission denied' errors in the logs.
