### ISSUE TITLE
How to set more than one slave db

### ISSUE THREAD

**Issue by restoreall** [CrunchyData/crunchy-containers#972]
Hi everyone, 

### I also try to add second slave's config to pgpool.conf like this: 

```
backend_hostname0 = 'master'
backend_port0 = 5432
backend_weight0= 1
backend_flag0= 'ALLOW_TO_FAILOVER'

backend_hostname1 = 'slave-db-1'
backend_port1 = 5432
backend_weight1= 1
backend_flag1= 'ALLOW_TO_FAILOVER'`

backend_hostname2 = 'slave-db-2'
backend_port2 = 5432
backend_weight2= 1
backend_flag2= 'ALLOW_TO_FAILOVER'`
```

###          So Anyone can tell me how to set more than one slave db if I want to use this image?

Thanks

**Comment by jmccormick2001** [comment]
Hi,

the pgpool configuration assumes that you have a single master Service and a single Slave Service.

The Slave Service load balances across multiple slave pods. 

cheers

**Comment by jmccormick2001** [comment]
yes, you should have a single Service for your master and a single Service for your slaves, the pgpool would then be configured to refer to those 2 Services.  If you have say 3 slaves, the slave Service acts as a load balancer itself to the 3 slaves, but pgpool sees just a single Slave service.  cheers.
