### ISSUE TITLE
run.sh does not error if storage not created

### ISSUE THREAD

**Issue by davecramer** [CrunchyData/crunchy-containers#973]
**Describe the bug**
If the storage cannot be created there is no error message

**To Reproduce**

in examples/kube/primary, remove primary-pvc-sc.json and try to create a simple primary pod
in common.sh we should return -1 if this file does not exist.

**Expected behavior**
return an error if storage cannot be created

**Comment by cahoonpwork** [comment]
this will be fixed in the next release 2.3.1

**Comment by cahoonpwork** [comment]
fixed in 2.3.1 which was released yesterday.
