### ISSUE TITLE
Custom configs order

### ISSUE THREAD

**Issue by lkhomenk** [CrunchyData/crunchy-containers#980]
**What is the motivation or use case for the change? **
Using custom configuration to enable extension leads to modifying postgres/start.sh. 
https://github.com/CrunchyData/crunchy-containers/blob/2fd0c1df831503c4a1850e2ecc38e646be330db9/bin/postgres/start.sh#L409
Line above executes custom setup.sql against default postgresql.conf . and line 425 puts custom postgresql.conf only after. some extensions need to be added into shared_preload_libraries before applying them
**Describe the solution you'd like**
Possible way to add extensions without breaking into original image

**Additional context**
maybe there's any other possible way adding extensions?

**Comment by jmccormick2001** [comment]
I see your point here, the ordering would matter, let me see what can be done here and do some testing, I'll mark this one for development to look into.  thanks.

**Comment by lkhomenk** [comment]
@jmccormick2001 we worked that out by using sed in our image to modify this line https://github.com/CrunchyData/crunchy-containers/blob/master/bin/postgres/start.sh#L299 . we add more options "-c shared_preload_libraries=<list_of_libraries> -c even_more_extension_options=<some_text>". it would just great to have some variable to be used for that purpose

**Comment by cahoonpwork** [comment]
This was release in 2.3.1 this week.
