### ISSUE TITLE
Docker pgadmin4 example fails: Could not create pgAdmin4 database

### ISSUE THREAD

**Issue by seilide** [CrunchyData/crunchy-containers#993]
** Which example are you working with? **

pgadmin4-http

**What is the current behavior?**

On clean Centos 7/Docker install - nothing else running, no existing images, no existing volumes. I run pgadmin4-http example and get unable to write to volume permission errors. It runs primary example without issue.

**What is the expected behavior?**

I've never seen this with crunchycontainers.

**Other information** (e.g. detailed explanation, related issues,  etc)

crunchy release 2.3.0  Also, see terminal log below.

**Please tell us about your environment:**

* Operating System: Centos 7 (selinux disabled)
* Where is this running ( Local , Cloud Provider) Dedicated Clound Server
* Storage being used (NFS, Hostpath, Gluster, etc): Docker local
* Container Image Tag: container exits on error
* PostgreSQL Version: 10.6
* Platform (Docker, Kubernetes, OpenShift): Docker
* Platform Version: 18.09.1

[pcady@server pgadmin4-http]$ ./run.sh
Cleaning up...
Error response from daemon: No such container: pgadmin4-http
Error: No such container: pgadmin4-http
Error: No such volume: pgadmin4-http-data
Starting the pgadmin4-http example...
pgadmin4-http-data
Unable to find image 'crunchydata/crunchy-pgadmin4:centos7-10.6-2.3.0' locally
centos7-10.6-2.3.0: Pulling from crunchydata/crunchy-pgadmin4
a02a4930cb5d: Pull complete 
18f2b6d7df5e: Pull complete 
3c5dc158310c: Pull complete 
05df8c49fe8a: Pull complete 
12db094a1b9b: Pull complete 
e2f943cf9535: Pull complete 
355a7ddcf46f: Pull complete 
22322fcb3f0f: Pull complete 
1030cad514be: Pull complete 
d45ee4fe2453: Pull complete 
b9138f9a6086: Pull complete 
Digest: sha256:31c9229ae1fed6adec2b5c2d227c873053e2ff7688469ce482dc455ce354a7b9
Status: Downloaded newer image for crunchydata/crunchy-pgadmin4:centos7-10.6-2.3.0
Wed Feb  6 18:36:39 UTC 2019 INFO: TLS disabled. Applying http configuration..
cp: cannot create regular file '/var/lib/pgadmin/pgadmin.conf': Permission denied
cp: cannot create regular file '/var/lib/pgadmin/config_local.py': Permission denied
sed: can't read /var/lib/pgadmin/pgadmin.conf: No such file or directory
sed: can't read /var/lib/pgadmin/config_local.py: No such file or directory
sed: can't read /var/lib/pgadmin/config_local.py: No such file or directory
Wed Feb  6 18:36:39 UTC 2019 INFO: Setting up pgAdmin4 database..
Wed Feb  6 18:36:39 UTC 2019 ERROR: pgAdmin4 Database Setup: Could not create pgAdmin4 database: 
Traceback (most recent call last):
  File "setup.py", line 410, in <module>
    setup_db()
  File "setup.py", line 345, in setup_db
    create_app_data_directory(config)
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/data_directory.py", line 26, in create_app_data_directory
    _create_directory_if_not_exists(os.path.dirname(config.LOG_FILE))
  File "/usr/lib/python2.7/site-packages/pgadmin4-web/pgadmin/setup/data_directory.py", line 15, in _create_directory_if_not_exists
    os.mkdir(_path)
OSError: [Errno 13] Permission denied: '/var/log/pgadmin'

**Comment by jasonodonnell** [comment]
Hi @seilide, thanks for the report!

This has been fixed in #998.  Our apologies for any inconvenience this has caused you. :)

**Comment by cahoonpwork** [comment]
@seilide  The fix is in the development branch now and will be in the 3.5.1 release later this month.

**Comment by seilide** [comment]
Brilliant! Thanks for the info, @jasonodonnell  and @cahoonpwork 

I'm glad the issue's been resolved - I was about to test a work-around, but mostly I'm glad that I wasn't losing my mind. I'm a SWE and depend on crunchydata containers to provide a reliable postgres ecosystem. Thanks!
